### ISSUE TITLE
Add new `syslog_parser` transform

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#1011]
# Motivation

As a user I'd like to ingest my logs via docker then parser the internal log message as syslog.

# Proposal

We should implement a `syslog_parser` transform which can take any field and parser syslog out of it. This should share the same syslog components from our `syslog` source but provide just the parser as a transform. This should be similar to our `json_parser`.

**Comment by binarylogic** [comment]
We've discussed this quite a bit in the past. The questions we need to answer:

1. How is this better than documenting common formats in the `regex_parser` transform?
2. Would a "native" parser like this outperform regex? In other words, is there a performance benefit to this?
3. Is https://github.com/timberio/vector/issues/334 a better approach since it would support other common formats (apache, nginx, etc)?

**Comment by LucioFranco** [comment]
> Would a "native" parser like this outperform regex? In other words, is there a performance benefit to this?

Yes, because you can optimize for that format specifically but I'm not sure how beneficial this is in practice.

> I think this relates more closely to #257. It'd be nice to decouple the parser implementations such that they could easily be used either as part of a source or later as a standalone transform.

This is mainly what I want, in setting up sources with kube, I've realized that I want more flexibility to decode inner message types. So similar to how we achieve json in json.

**Comment by binarylogic** [comment]
Closing in favor of #4710
