### ISSUE TITLE
[Help] coercer transform

### ISSUE THREAD

**Issue by romvarac** [timberio/vector#1031]
Hi team, I did [coercer transform guide](https://docs.vector.dev/usage/configuration/transforms/coercer) but result not the same.
I use timberio/vector:latest-debian docker image
(Vector is starting. version="0.4.0-dev" git_version="v0.5.0")
1. vector.toml
```
# TCP request
[sources.in]
  # REQUIRED - General
  type = "tcp" # must be: tcp

  # OPTIONAL - General
  address = "0.0.0.0:9000" # no default
  max_length = 102400 # default, bytes
  shutdown_timeout_secs = 30 # default, seconds

  # OPTIONAL - Context
  host_key = "host" # default

[transforms.coercer_transforms]
  inputs = ["in"]
  type = "coercer"
  
  [transforms.coercer_transforms.types]
    bytes_in = "int"
    bytes_out = "int"
    timestamp = "timestamp|%m/%d/%Y:%H:%M:%S %z"
    status = "int"

[sinks.out]
  inputs = ["coercer_transforms"]
  type = "console"
  encoding = "text"
  healthcheck = true
```
2. Result 
```
{
  "bytes_in": "5667",
  "bytes_out": "20574",
  "host": "5.86.210.12",
  "message": "GET /embrace/supply-chains/dynamic/vertical",
  "status": "201",
  "timestamp": "19/06/2019:17:20:49 -0400",
  "user_id": "zieme4647"
}
```
3. Expected
```
{
  "bytes_in": 5667,
  "bytes_out": 20574,
  "host": "5.86.210.12",
  "message": "GET /embrace/supply-chains/dynamic/vertical",
  "status": 201,
  "timestamp": <19/06/2019:17:20:49 -0400>,
  "user_id": "zieme4647"
}
```
So, how I do the same result in the above guide. Thanks

**Comment by lukesteensen** [comment]
Thanks for the report @romvarac! There are indeed a couple of issues here.

The first is that you've set up the `tcp` source to directly feed into the `coercer` transform. The `tcp` source doesn't do any parsing of fields on its own, so your event actually looks something like this when it gets to the coercer:

```json
{
  "message": "{\"bytes_in\": \"5667\", \"bytes_out\": \"20574\", \"host\": \"5.86.210.12\",  \"message\": \"GET \/embrace\/supply-chains\/dynamic\/vertical\",  \"status\": \"201\",  \"timestamp\": \"19\/06\/2019:17:20:49 -0400\",  \"user_id\": \"zieme4647\"},
  "timestamp": <generated timestamp from when data was received>,
}
```

To handle this, you can use the `json_parser` transform to parse the message field and extract the expected fields:

```toml
[transforms.json]
type = "json_parser"
inputs = ["in"]

[transforms.coercer_transforms]
  inputs = ["json"]
  type = "coercer"
...
```

This will get your data into the expected shape before it arrives at the `coercer` transform.

The second issue is one with the example config in the guide. The timestamp format is give as `%m/%d/%Y:%H:%M:%S %z`, but the actual timestamp is `19/06/2019:17:20:49 -0400`. This means we try to parse `19` as `%m` (month), which fails because there are only 12 months. I will have a PR shortly that fixes this bug in the guide.

The third issue made the second issue invisible. We should have logging when a field fails type conversion like that timestamp does, but we currently have it set to the `debug` log level which is not visible by default (you can see it by passing `-v` when you run vector). My PR will also fix this.

The fourth issue is actually a leftover from when we found https://github.com/timberio/vector/issues/806. Due to some complex logic around encodings in the `console` sink, we were actually not outputting anything for structured data (i.e. log events with structured fields) when the encoding option of the sink is set to `text`. We decided to simplify this logic, but apparently forgot to address it both for the `console` sink and the `file` sink. My PR cleans this up for both sinks.

Sorry for the trouble here! We really appreciate you helping us find and address issues like this, and we'll be sure to get the fixes merged promptly :heart:
