### ISSUE TITLE
Update `rusoto` version

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#1103]
We are currently a few versions behind the current rusoto release. We should update to the latest version. This seems simple but they reworked their error's in `0.38` and thus we can't upgrade without changing a bunch of code. So this task is a bit more mechanical.

**Comment by phyber** [comment]
I have a version of Vector locally which I have successfully run `cargo test` (all tests pass) with

```
rusoto_core = "0.38.0"
rusoto_s3 = "0.38.0"
rusoto_logs = "0.38.0"
rusoto_cloudwatch = "0.38.0"
rusoto_kinesis = "0.38.0"
rusoto_credential = "0.17.0"
```

I've done a conservative version bump first of all due to the change to the error types. Bumping the versions to `0.39.0` encounters some new issues with the wrapping of a few pieces of data in both the Elasticsearch and Kinesis sinks, so upgrading further should probably be a separate chunk of work.

I'm currently tidying up the `0.38.0` upgrade, and should hopefully have a PR ready for you later today.

**Comment by LucioFranco** [comment]
@phyber wonderful! Let me know if you have any questions! 😄

**Comment by phyber** [comment]
I have this completely upgraded locally now.
```
rusoto_core = "0.41.0"
rusoto_s3 = "0.41.0"
rusoto_logs = "0.41.0"
rusoto_cloudwatch = "0.41.0"
rusoto_kinesis = "0.41.0"
rusoto_credential = "0.41.1"
```
with `make check-code` passing.
Will submit an additional PR after the 0.38.0 work is merged.
