### ISSUE TITLE
[Feature Request] GCS Sink

### ISSUE THREAD

**Issue by ChethanUK** [timberio/vector#1353]
Having a GCP ecosystem[GCS, Stackdriver] will be helpful.

**Comment by Jeffail** [comment]
Hey @ChethanUK,

We have an existing ticket for GCS: https://github.com/timberio/vector/issues/822
And also Stackdriver: https://github.com/timberio/vector/issues/1304

There's also a PR for GCP pubsub which will hopefully be merged soon: https://github.com/timberio/vector/pull/1308, I suspect once that's finished it won't take long for more GCP connectors to be added.

In the meantime you could try configuring the interoperability API https://cloud.google.com/storage/docs/interoperability in order to use our `aws_s3` sink as a temporary work around.

I'm going to close this issue as it's a duplicate, but if you decide to try out the interoperability API then feel free to reopen if you need guidance.
