### ISSUE TITLE
Support the Kubernetes rudr implementation

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1398]
[Rudr](https://github.com/oam-dev/rudr) has come up in discussions and I'd like to think about supporting it for Vector. Before we begin I want to gauge demand and make sure this is worth doing.

**Comment by binarylogic** [comment]
@MOZGIII assigning this to you just to review. I'm unsure if we need to do this or if this is within the scope of v1, but it might be relevant for https://github.com/timberio/vector/pull/2222.

**Comment by MOZGIII** [comment]
- Should we use it or rely on OAM when deploying Vector?
No, we're a service-level component, we want to abstract from the deployment models.

- Should Vector work for people developing their apps with OAM?
Yes, and it'll come naturally since we're focusing on interfacing with `Pod`s, and not higher-level abstractions. Rudr creates `Pod` under the hood just like everything else - it's just another high-level abstraction.

I don't think we'll have to do anything specific to support Rudr, so I'm closing this for now.
