### ISSUE TITLE
Sorted json keys

### ISSUE THREAD

**Issue by anton-ryzhov** [timberio/vector#1428]
Now `json` (`ndjson`) encoders writes logs like that:
```
{"file":"test.log","host":"myhostname","message":"Some test message","timestamp":"2019-12-24T12:41:14.802375194Z"}
{"timestamp":"2019-12-24T12:41:14.802423354Z","message":"Some test message","host":"myhostname","file":"test.log"}
{"message":"Some test message","host":"myhostname","file":"test.log","timestamp":"2019-12-24T12:41:14.802427297Z"}
```

They are of course perfectly machine-readable, but rather unreadable by humans.

I'm not sure if it's possible to define keys order — that's obviously goes beyond json standards. But that will be super-useful to have keys sorted or even sorted by given order (like `timestamp` is the first key).

**Comment by binarylogic** [comment]
That makes sense. To clarify, you're referring to the `console` sink, correct?

**Comment by anton-ryzhov** [comment]
At least for `console`, `file` and `aws_s3`, but most likely this is useful for all json encoders.

**Comment by binarylogic** [comment]
👍 I'm going to add this to https://github.com/timberio/vector/milestone/23, which is being worked on now. We're making some improvements to our internal data model and this is somewhat related.

**Comment by LucioFranco** [comment]
I wonder if it makes sense to switch out https://github.com/timberio/vector/blob/master/src/event/mod.rs#L35 to be a `IndexMap` from https://docs.rs/indexmap/1.3.0/indexmap/ I don't think this should cause any performance issues. The biggest problem here will be to ensure the way that `prost` encodes hashmaps might swap the order out. Otherwise, we'd need to sort the hashmap but I believe this would require an allocate of the hasmap into a vec to produce a slice you can sort on.

**Comment by a-rodin** [comment]
`IndexMap` seems to me much better than sorting of the `HashMap`. For example, if the user feeds JSON-encoded events to Vector, then parses them, and then encodes them again, the order of the keys should not change, and `HashMap` with sorting cannot guarantee this.

**Comment by LucioFranco** [comment]
Right the biggest problem is that I believe `prost` will lose ordering going into protobuf then back out.
