### ISSUE TITLE
New `flatten` (`denormalize`, `canonical`, or `transaction`) transform

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1437]
The purpose of this transform is to flatten related events into a single event representing a single transaction. A transaction is defined by a set of join factors, such as all events with the same `request_id` value. (see example below)

## Motivation

An increasingly popular tactic for observing applications is the use of an event stream. This is not a new concept, logs are effectively an event stream, and the idea of logs as events has been outlined in rather old guides (such as [12 factor](https://12factor.net/logs)). This was also the basis for the original Timber hosted service. The problem in the past was the impractical nature of storing this data. Storage solutions did not exist to properly analyze this data. That is changing and the use of rich event streams is becoming more popular. A common tactic to further optimize the performance of analyzing this data is to flatten or denormalize multiple events into a single "transaction" event.

## The problem

This is an excellent use case for Vector because users should not be denormalizing data in their application with the use of special tools, like vendor-specific libraries. This just restarts the lock-in cycle. Instead, users should be emitting normalized events from their app and then transforming that data with a tool like Vector. This decouples their app from whatever downstream system they're using.

## Example

For example, let's take a common Rails app that emits the following logs (events):

```js
{"timestamp": "...", "message": "Received GET /path", "request_id": "abcd1234", "request_path": "/path", "request_params": "..."}
{"timestamp": "...", "message": "Executed query in 5.2ms", "request_id": "abcd1234", "query": "SELECT * FROM table", "query_duration_ms": 5.2}
{"timestamp": "...", "message": "Rendered partial _partial.erb in 2.3ms", "request_id": "abcd1234", "template": "_partial.erb", "render_duration_ms": 2.3}
{"timestamp": "...", "message": "Executed query in 7.8ms", "request_id": "abcd1234", "query": "SELECT * FROM table", "query_duration_ms": 7.8}
{"timestamp": "...", "message": "Sent 200 in 15.2ms", "request_id": "abcd1234", "response_status": 200, "response_duration_ms": 5.2}
```

This transform would reduce (flatten) these events on the `request_id` field:

```json
{
  "timestamp_start": "...",
  "timestamp_end": "...", 
  "request_id": "abcd1234",
  "request_path": "/path",
  "request_params": "...",
  "query_duration_ms": 13.0,
  "render_duration_ms": 2.3,
  "status": 200,
 "response_duration_ms": 5.2
}
```

A few things to notice here:

1. The timestamp range represents the first and last event (obviously).
2. Duplicate string fields are discarded (`message`, `query`, `template`).
3. Unique string fields are kept (`params`).
3. Numeric fields are aggregated (`query_duration_ms`).

## Final thoughts

There's a lot of details left to discuss here, but it sets the stage for some of our marketing efforts around how to observe your application with Vector. Emitting normalized events decouples your app from any specific downstream solution which offers a plethora of benefits (no lock-in, clean backups, etc).

## Prior Art

- https://brandur.org/canonical-log-lines

## Marketing

- Normalized events streams
- Stripe's canonical log lines (https://stripe.com/blog/canonical-log-lines)

**Comment by a-rodin** [comment]
If this is implemented, it would be nice to ensure that it works correctly when events come from multiple inputs (the `inputs` parameter contains multiple events).

This can be especially useful for the same use case, but when the application is scattered across multiple services, and the goal is to combine an aggregated log event using separate events from all of these services sharing identical `request_id`.

**Comment by binarylogic** [comment]
> If this is implemented, it would be nice to ensure that it works correctly when events come from multiple inputs (the inputs parameter contains multiple items).

Yep, we could also follow the [`stream_discriminants` pattern](https://vector.dev/docs/reference/transforms/merge/#stream_discriminant_fields) that @MOZGIII implemented in the `merge` transform.

**Comment by binarylogic** [comment]
Blocked by #1598

**Comment by Jeffail** [comment]
I think `transaction` fits well as a name here as it differentiates it from the `merge` transform and also signals as to its purpose.

The default behaviors seem sensible to me, although I'd maybe suggest setting the resulting timestamps as `timestamp` and `timestamp_end` so that the start timestamp automatically plays with other components and sinks.

I'd also want to offer alternative strategies for flattening on a per field basis, we can expose that as a `"<field>" = "<strategy>"` map:

```toml
[transforms.my_transform_id]
  type = "transaction"
  inputs = ["my-source-id"]

  stream_discriminant_fields = [ "request_id" ]

  strategies = {
    "message" = "append"  # Append strings (with a space delimiter)
    "verb"    = "array"   # Create an array of values
    "latency" = "highest" # Select the highest of a group of number values
    "foo"     = "lowest"  # Select the lowest of a group of number values
    "bar"     = "mean"    # Calculate the mean of a group of number values
    "baz"     = "sum"     # Calculate the sum of a group of number values (the default for numbers)
    "boo"     = "discard" # Discard subsequent values (the default for strings)
  }
```

The `array` strat is the most important as it allows for advanced use cases where certain fields can be flattened using custom logic, or even aggregated that way. When a field of an event doesn't match the strategy (a string value for a sum strat) it is dropped, that's why it might be useful to explicitly declare the strat for fields to the default behavior.

For `append` we can mostly get away with just a space delimiter, if we need to expand it then we can add the syntax `append(<delimiter>)`. Or, users can flatten with `array` and then use a subsequent transform to merge them with any delimiter.

In terms of flush behavior we will flush all pending transactions during shutdown. We will also need to continuously flush transactions that are "stale" (no new entries were received for a period of time). We should expose that period so that users can tune it, something like `"flush_after_ms" = 1000`.

These continuous flushes should happen during any event receipt since that's an easy and (most likely) constant trigger, but we also need to ensure flushes are periodically done regardless of whether new messages are received. We can probably get away with a hard coded 100ms timer (or use `flush_after_ms/2` or something). I don't think we need to expose this timer to users as it's an implementation detail, but since it does have an impact on the feed we could consider exposing it as `flush_period_ms`.

**Comment by binarylogic** [comment]
> although I'd maybe suggest setting the resulting timestamps as timestamp and timestamp_end so that the start timestamp automatically plays with other components and sinks.

👍 

> I'd also want to offer alternative strategies for flattening on a per field basis

I like this. Although, doesn't this feel like another use case where a simple sytanx would fit better? Similar to #1926. 

> In terms of flush behavior we will flush all pending transactions during shutdown

👍 

> These continuous flushes should happen during any event receipt since that's an easy and (most likely) constant trigger, but we also need to ensure flushes are periodically done regardless of whether new messages are received. We can probably get away with a hard coded 100ms timer (or use flush_after_ms/2 or something)

Yes, we will definitely need to flush stale transactions to prevent unbounded memory usage. 100ms is far too low though. The common use case is going to be web transactions where the typical timeout is 30 seconds.

> I don't think we need to expose this timer to users as it's an implementation detail, but since it does have an impact on the feed we could consider exposing it as flush_period_ms.

I think we should expose this, depending on how the user defines transaction this number will changes. Like the web transaction example above, a sensible default is 30s, but for a background job transaction, it might be 1s.

**Comment by Jeffail** [comment]
> I like this. Although, doesn't this feel like another use case where a simple sytanx would fit better? Similar to #1926.

The two could work hand-in-hand, since you need to have the events merged before you can map the values using custom logic. Unless we expanded #1926 to also allow event merging, which could be an interesting requirement to explore.

We should aim for the `transaction` transform to have default behavior that suits the vast majority of cases. For slightly more nuanced cases (I imagine mostly around numbers) we can offer the options like `mean`, `maximum`, etc, with a small addition of config. Then, finally, for cases where users really need a lot of power we can advise them to merge event fields into arrays and then map the arrays using a subsequent transform from #1926.

> Yes, we will definitely need to flush stale transactions to prevent unbounded memory usage. 100ms is far too low though. The common use case is going to be web transactions where the typical timeout is 30 seconds.

> I think we should expose this, depending on how the user defines transaction this number will change. Like the web transaction example above, a sensible default is 30s, but for a background job transaction, it might be 1s.

:+1:

> Also, we should define a transaction end condition that would immediately flush it.

If we use the actual condition type for that we can offer something like this:

```toml
[transforms.my_transform_id]
  type = "transaction"
  inputs = ["my-source-id"]

  stream_discriminant_fields = [ "request_id" ]

  [transforms.my_transform_id.ends_when]
    "response_status.exists" = true
```

**Comment by binarylogic** [comment]
Nice work on this @Jeffail and @lukesteensen.
