### ISSUE TITLE
Insert timestamps as native `DateTime` type to ClickHouse

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1443]
It is worth to consider insertion of the native `DateTime` type instead of generic string type for timestamp fields.

A caveat here is difference in precision: Vector's timestamps have nanosecond precision, while ClickHouse datetimes are defined only up to seconds.

**Comment by sundy-li** [comment]
Also Clickhouse has some http params to set the time parse mode. Such as `date_time_input_format` to be `best effort`.

So the Clickhouse sink should accept the parameters by users set. 
So [here](https://github.com/timberio/vector/blob/master/src/sinks/clickhouse.rs#L162) may need some improvement.

**Comment by Jeffail** [comment]
Since we lose precision with DateTime I think it's reasonable to expose this as a configuration field. That way users have the option of using a string column with higher precision, or a DateTime column that we populate with unix timestamps.

As for `date_time_input_format` @sundy-li, do you know of any disadvantages to setting `date_time_input_format` to `best_effort`? From looking at the docs it probably makes sense for us to always set that header as it simply makes it more accommodating to user added date strings.

**Comment by sundy-li** [comment]
Set `date_time_input_format` to `best_effort ` will try all possible formats to parse the date.
See 
 https://github.com/ClickHouse/ClickHouse/blob/b4ff2ce13b/dbms/src/IO/parseDateTimeBestEffort.cpp
