### ISSUE TITLE
Consistent names for line-delimited JSON encoding

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1462]
The `console` and `tcp` sinks supports `json` encoding, but `aws_s3` and `file` sinks support `ndjson` encoding, although it looks like there is no real difference between `json` and `ndjson` here.

Could it make sense to name the encoding `ndjson` for all sinks?

**Comment by binarylogic** [comment]
Yeah. I think we might have been a little too technical with the naming on the streaming sinks (`console`, `tcp`, etc). The thought process was from the perspective of the entire payload. Since the `console` and `tcp` sinks stream events, we encode them as `json`, and the `aws_s3` and `file` sinks batch events, so we encode the payload as `ndjson`.

Additionally, the `http` sink supports both `json` and `ndjson` and they differ in behavior. The `json` option encodes the payload as a JSON array:

```
[
  {...},
  {...}
]
```

And the `ndjson` option just new line delimits the events:

```
{...},
{...}
```

**Comment by ktff** [comment]
In short, it does make sense to name the encoding `ndjson` for all sinks.

Renaming this would be a breaking change, so we can accept both `ndjson` and `json` while documenting only `ndjson`. This way we would avoid breaking change, but it could be confusing for those that stumble on this.

@binarylogic what do think?

### Reason

We can separate sinks into two groups by their targets:
* Generic targets
   - `file`, `socket`, `console`, and `http`
   - For these sinks it is important to be clear about their API so that users know what to expect.
   - [ ]  `socket` and `console` are using `ndjson` encoding so their codec naming should be updated.
   - `http` as mentioned has both `json` and `ndjson` encoding which is fine because it is important to distinguish them.
* Specific targets
  - All of other sinks
  - They have a specialized API that they are using to communicate with their targets so it's fine to simplify things and rename `json` to `ndjson` since that API is constraining it. 
  - [ ]  None of these sinks have both `json` and `ndjson` so we can rename all to `ndjson`.
  - All of these sinks that I've checked use `ndjson` even if they are named `json`, so this is also technically correct for most of them.

With this all sinks will have `ndjson` encoding, and `http` with `json`.

**Comment by binarylogic** [comment]
> Renaming this would be a breaking change, so we can accept both ndjson and json while documenting only ndjson. This way we would avoid breaking change, but it could be confusing for those that stumble on this.

Works for me

> With this all sinks will have ndjson encoding, and http with json.

👍 . `http` would have both `json` and `ndjson` since both are valid, correct?

**Comment by ktff** [comment]
> http would have both json and ndjson since both are valid, correct?

Yes.

**Comment by jamtur01** [comment]
@ktff Can this proceed now?

**Comment by ktff** [comment]
@jamtur01 yes, somehow it just didn't get on my todo list, but it is now.

**Comment by ktff** [comment]
Closing in favor of #4058
