### ISSUE TITLE
Ability to sample entire transactions

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1470]
Note: a better solution might be to couple this with the transaction transform proposed in #1437.

---

Currently, the `sampler` transform operates on a per-event basis. For generic stream sampling, where events are not part of a larger transaction, this works fine, but for most use-cases, this creates gaps when you start to look at transactions as a whole.

## Usecase: Web server applications

The common example is a simple web server application, where a single request is a transaction. A request produces X number of logs all related with the `request_id` field. Users should have the ability to sample entire requests (transactions).

## Configuration

I propose that we expand the current `sampler` transform to take a `group_by` option:

```toml
[transforms.sample_requests]
  type = "sampler"
  group_by = "request_id"
  rate = 10
```

## Implementation

Instead of grouping logs in memory, we should implement a deterministic algorithm that allows us to know which request IDs should pass or be dropped. This avoids the need to hold entire transactions in memory or do any kind of grouping.

**Comment by a-rodin** [comment]
A possible alternative is to provide group/ungroup transforms for combining events from multiple transactions into single one and, if necessary, reverting it later.

This could allow to isolate all logic related to transactions in just one or two components.

**Comment by lukesteensen** [comment]
I could have sworn we already did this, but I must be losing my mind.

The sampler transform is already built to support this. Instead of generating a random number, it hashes a field on the event as the "coin toss" for whether an event is passed through or not. This means that events in which the hashed field has the same value will get the same sampling decision.

The only problem is that the sampler is currently hardcoded to look at the message field. All we need to do is make the field configurable so users can set it to their `request_id`.

**Comment by binarylogic** [comment]
Closing in favor #1778.
