### ISSUE TITLE
Unkown variant `socket`

### ISSUE THREAD

**Issue by silverdaz** [timberio/vector#1491]
I searched with the label `socket: udp` and could not find any related issue, so I create this new one.

I'd like to collect my python logs (multiple microservices running in docker containers) into a centralized place, a container itself.
For that I configured my python loggers to send UDP datagrams to a given location, and at that location, I have Vector running, with the following config:
```
[sources.my_source_id]
type = "socket"
address = "0.0.0.0:9000"
mode = "udp"

[sinks.out]
inputs   = ["my_source_id"]
type     = "console"
encoding = "text"
```
as described on the [documentation website](https://vector.dev/docs/reference/sources/socket/)

However, I get the following error:
```
INFO vector: Log level "info" is enabled.
Jan 08 17:16:14.241  INFO vector: Loading config. path="/etc/vector/vector.toml"
Jan 08 17:16:14.246  ERROR vector: Configuration error: unknown variant `socket`, expected one of `docker`, `file`, `journald`, `kafka`, `splunk_hec`, `statsd`, `stdin`, `syslog`, `tcp`, `udp`, `vector` for key `sources.my_source_id.type`
```

What am I missing or doing wrong?
Thanks for the help
Cheers,
-..-. ..-. .-. . -..

**Comment by Jeffail** [comment]
Hey @silverdaz, until only recently the `socket` source was split into two separate `tcp` and `udp` sources. The docs site is currently showing the state of Vector nightly builds rather than the latest stable release (which I assume you're running).

In order to use `socket` you can [grab a nightly build](https://vector.dev/releases/latest/download/), or in your case it might make more sense to use a `tcp` source (but you'll need to update to `socket` when you next upgrade).

Sorry for the confusion. We have an issue open for explicitly versioning the docs https://github.com/timberio/vector/issues/1291 which will hopefully prevent this in future.

**Comment by silverdaz** [comment]
Thanks very much for the answer. That explains the issue.

I followed the suggestion, and it's not raising the error with the nightly build.

Back onto the exploration of the tool now ;-)
