### ISSUE TITLE
Use sccache to improve compilation times on CI

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#1591]
We spend quite a bit of time compiling Vector on CI (Github Actions). It appears we spend about 25 minutes doing this. It would be worth it to experiment with [sccache](https://github.com/mozilla/sccache) to see if it could improve these times. [This Github action](https://actions-rs.github.io/) looks promising.

**Comment by a-rodin** [comment]
This is interesting. It seems that the Rust support [is experimental](https://github.com/mozilla/sccache/blob/master/docs/Rust.md), so it is necessary to ensure first that it is both correct and provides significant speed improvements for Vector code.

Also we should not use this for release builds because someone (theoretically) can use a hash collision to put arbitrary compiled code to the cache by creating a PR with this code, and then there is a chance for this code to end up in a release artifact.

**Comment by binarylogic** [comment]
Marking this as "should have" since it will improve compile times. The slow compilation times with the test harness Github Action really hinder productivity when benchmarking new versions of Vector.

**Comment by binarylogic** [comment]
Adding a note, it's looking like we won't need this after transitioning to Github Actions. We can revisit if compile times are causing productivity issues again.
