### ISSUE TITLE
Generated sink `md.erb` file requires sudo and needs newline

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#1621]
When generating a new sink the generated `md.erb` template for some reason requires `sudo` privileges and does not pass the fmt check on CI because it does not add a newline at the end of the file.

cc @binarylogic

**Comment by LucioFranco** [comment]
This could be related to running it inside the docker container which runs it as sudo.

**Comment by a-rodin** [comment]
> This could be related to running it inside the docker container which runs it as sudo.

Yes, that's the reason. When Docker runs inside a VM (such as on macOS) it's not a problem, but when runs on the same system it is. Ideally we need to use a user with the same UID as the one of the user who starts the generation process.

**Comment by a-rodin** [comment]
Basically, we need to add `--user=$UID` option to the arguments of `docker run` in `scripts/docker-run.sh`. If we proceed with the approach with `docker-compose` outlined in https://github.com/timberio/vector/issues/1613#issuecomment-579268809, we would need to add option `user: $UID` to each service defined in `docker-compose.yml`.

**Comment by a-rodin** [comment]
Note that there are two CI Docker images which do require root privileges. These are the ARM builders load `binfmt-qemu` kernel module. So we probably want pass an optional way to not pass `--user=$UID` in some instances. The same applies to the `--privileged` flag in `scripts/docker-run.sh` which is used only by ARM builders as well. When the images were used exclusively in CI, it was fine to have the root user and `--privileged` for all of them because of the sandboxing guarantees provided by CI, but it would be better to require privileges only when necessary.

**Comment by LucioFranco** [comment]
Just confirming this is still an issue, I had to recreate the file manually to make sure I could edit it without sudo access.

**Comment by Hoverbear** [comment]
Confirming I regularly experience this issue when using Docker on Linux and the workaround is to set `USE_CONTAINER=false` and set up a ruby toolchain.

**Comment by binarylogic** [comment]
Does adding your user to the `docker` group fix this?

```
sudo groupadd docker
sudo gpasswd -a $USER docker
```

I don't have this problem on Mac.

**Comment by Hoverbear** [comment]
Right because in Mac you're running Docker in a VM that has a share with the Mac. Windows with Docker Desktop (HyperV) would, in theory, also be able to avoid this due to their architecture. Linux or other 'true' Docker hosts (without a hidden away Linux VM backing them) with a group based access control will (correctly) have files created on a share with the UID of the running user in the docker container. (You can review the security surface of Docker here: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface)

Typically the way you fix this idiomatically is to image build as a user with the same UID as the executing user, run in rootless (https://docs.docker.com/engine/security/rootless/) as the user, or do your build etc as a running container with a non-root user (https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user)

But honestly, it's quite easy to set up a local toolchain on Linux, and there should be minimal barriers for Mac and FreeBSD. Windows is the only OS we can't support easily without containers, and it doesn't work anyways since our `Makefile` calls Docker through bash scripts that mingw doesn't support... and WSL2 is trivial to set up for this.

**Comment by binarylogic** [comment]
Closing as this is no longer an issue due to the recent dev environment changes.
