### ISSUE TITLE
Support running all checks and verifications locally

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1663]
This issue is about continuing https://github.com/timberio/vector/pull/1647 after it is merged, see the discussion there for more details.

The following steps can further us in the direction of making it possible to run all checks, tests, and verifications locally:

- [ ] Copy all Linux steps from `.circleci/config.yml` to `docker-compose.test.yml`/`Makefile.test`.
- [ ] Merge `docker-compose.test.yml` with `docker-compose.yml` and `Makefile.test` with `Makefile`.
- [ ] Ensure that all job have consistent naming. For example, there might be checks for DEB packages for x86_64, ARMv7, and ARM64 archives. It would be nice if these were named consistently.

**Comment by binarylogic** [comment]
@a-rodin I'm assigning this to you. Feel free to work on it as a low priority task.

**Comment by MOZGIII** [comment]
I saw this issue and realized that I have a few concerns I'd like to discuss, that may be relevant to approaching this.

- Can we move away from `Makefile`s? We only seem to be using them as a frontend to our `scripts`, and it's not very ergonomic. I'd suggest having a `bin/` dir with user-friendly frontends instead, for starters, or [`xtask`](https://github.com/matklad/cargo-xtask).
- It'd be great if we had separate concerns split into multiple files. I've started working on Github Actions and realized it'd be much easier to navigate if we split build/test, package verification and docs generation tasks into separate Github Action workflows. I think this translates naturally to the organization we could apply to run things locally.

**Comment by binarylogic** [comment]
> Can we move away from Makefiles? We only seem to be using them as a frontend to our scripts, and it's not very ergonomic. I'd suggest having a bin/ dir with user-friendly frontends instead, for starters, or xtask.

Sure, I'm indifferent to using a `Makefile`, but I do want a single front-end command interface that makes common tasks easily discoverable. Whether we use a `Makefile` or `xtask` is up to you all.

> It'd be great if we had separate concerns split into multiple files.

I'm not sure I follow. I feel like we've done that with the `/scripts` folder? And things like test are already frontend with `cargo test`, etc.

**Comment by binarylogic** [comment]
Also, to add to this. We've already invested in using a `Makefile` (https://github.com/timberio/vector/pull/1701). I think we should continue down this path and consider `xtask` as a follow-up improvement. I don't want to derail progress on this issue as a result.

**Comment by MOZGIII** [comment]
> > Can we move away from Makefiles? We only seem to be using them as a frontend to our scripts, and it's not very ergonomic. I'd suggest having a bin/ dir with user-friendly frontends instead, for starters, or xtask.
> 
> Sure, I'm indifferent to using a `Makefile`, but I do want a single front-end command interface that makes common tasks easily discoverable. Whether we use a `Makefile` or `xtask` is up to you all.

In that sense, having a `bin/generate` and `bin/package-deb` is even better because of the autocompletion. I do understand that a frontend that's easy to use is necessary, however `make` is just too archaic. It does work though.
`xtask` on the other hand is more heavy-weight than both `bash` scripts and `make` - so I'm not really sure if it's better for us.

> > It'd be great if we had separate concerns split into multiple files.
> 
> I'm not sure I follow. I feel like we've done that with the `/scripts` folder? And things like test are already frontend with `cargo test`, etc.

That's more representative compared to how we have the Circle CI organized currently. The `/scripts` dir is easy to navigate as is.

> Also, to add to this. We've already invested in using a `Makefile` (#1701). I think we should continue down this path and consider `xtask` as a follow-up improvement. I don't want to derail progress on this issue as a result.

I guess I'm a bit too late for the start of this work, but that's ok. Switching from `make` is definitely worth a separate issue. I just thought I could get some quick feedback while we're at this.

**Comment by a-rodin** [comment]
@MOZGIII 

> Can we move away from `Makefile`s? We only seem to be using them as a frontend to our `scripts`, and it's not very ergonomic. I'd suggest having a `bin/` dir with user-friendly frontends instead, for starters, or [`xtask`](https://github.com/matklad/cargo-xtask).

It seems like the only easy way to install `xtask` is using `cargo`, which means it would be necessary to install entire Rust toolchain on the host machine (and not inside a container) to use it. So even to make changes in the documentation and run `make generate` it would be necessary to install entire Rust toolchain on the host machine, which I think is too much of a dependency.

GNU `make` might be not perfect, but it is omnipresent. That's why in my opinion it might have sense to stick with it. Also, if we move to having the Rust compiler executed in Docker (like it is done now in `tests`), then there seem to be no reason to require `cargo` to be present on the host machine at all.

**Comment by MOZGIII** [comment]
> It seems like the only easy way to install `xtask` is using `cargo` from sources, which means it would be necessary to install entire Rust toolchain on the host machine (and not inside a container) to use it. So even to make changes in the documentation and run `make generate` it would be necessary to install entire Rust toolchain on the host machine, which I think is too much of a dependency

Yes, in that sense I don't like `xtask` either. It'll also require us writing the scripts in rust, which is not the best tool for the job - most of what we do is achievable much easier with shell scripting.

> GNU `make` might be not perfect, but it is omnipresent. That's why in my opinion it might have sense to stick with it. Also, if we move to having the Rust compiler executed in Docker (like it is done now in `tests`), then there seem to be no reason to require `cargo` to be present on the host machine at all.

`make` is indeed available everywhere, but so is `bash`. My point is `make` is just another extra tool we don't need. In fact, we don't even use make for what it's good for - managing execution graphs. In our case, it's merely just a frontend to the stuff that lives at `scripts` dir. From my perspective, ditching `make` in favor of a `bash` script frontend looks pretty logical. Plus, `make` is not installed on the popular linux distributions out of the box (Debian, Ubuntu), but `bash` is. And we rely on `bash` anyway for our `scripts`.
Since we're not using GNU build system, the fact that we're using `make` command doesn't contribute to the tooling familiarity - i.e. people (and tools) who expect `./configure && make && make install` to work will be disappointed. That's ok, but the only compelling reason to use `make` here, imo, is to integrate with GNU build system, which we're not doing anyway.

As I side note, if you're considering putting the vector development process in docker exclusively - please keep in mind that I'd be most interested in doing all of my local development outside of docker. I don't oppose supporting that use case for docker, but for me, it'll definitely be not feasible to do local development in docker.

**Comment by binarylogic** [comment]
> As I side note, if you're considering putting the vector development process in docker exclusively

We would never do that. 😄
