### ISSUE TITLE
Avoid cross-dependencies between components

### ISSUE THREAD

**Issue by a-rodin** [timberio/vector#1940]
Currently some components of Vector import and use code from other components. The list of such dependencies is the following:

* `sources-kubernetes` depends on `sources-file`, `transforms-json_parser`, `transforms-regex_parser`;
* `sources-syslog` depends on `sources-socket`;
* `sources-vector` depends on `sources-socket`;
* `sinks-humio_logs` depends on `sinks-splunk_hec`;
* `sinks-new_relic_logs` dependes on `sinks-http`;
* `sinks-sematext_logs` depends on `sinks-elasticsearch`.

I think in long term this might make it harder to refactor individual components, as change is one component might break some other (seemingly) unrelated component. So ideally we need to identify the common code and factor it out to `lib` crates or, if the code is too specific, at least as util modules.

The above relates only to implementation of components, but not to their tests. Using other components in tests I think is less an issue, although some tests for components might be changed to not depend on other components. In particular, I think most of the tests depending on `json_parser` can be modified to avoid such a dependency.

See also https://github.com/timberio/vector/pull/1924.

**Comment by ktff** [comment]
These have already been resolved:
* `syslog` source
* `vector` source
* `honeycomb` sink

- [ ] although some of their feature dependency can be updated to reflect this. 

---

`kubernetes_logs` source uses transforms:
* `merge` whole so there is little to gain in separating common code.
* `regex` partially so there is common code that could be extracted, although it would be quite specific.
     - [ ] To extract common `regex` or not?
* `json_parser` partially so there is common code to be extracted, and it's something that can be shared, even specialized since tests use it in same/similar way as `kuberentes_logs` source.   
     - [ ] Extract 

---

Others: 
* `humio_logs` sink uses whole `splunk_hec` sink
* `new_relic_logs` sink uses whole `http` sink
* `sematext_logs` sink uses whole `elasticsearch` sink

They are using whole of the other sink, as they are basically wrappers with some extra/default configuration. Their common code would be the whole sink so we wouldn't gain much.

cc. @binarylogic
