### ISSUE TITLE
Reloading configuration causes a port conflict error

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2011]
From our community chat:

Hey - I have a small problem with reloading configurations. If the source is http / logplex / splunk_hec (all of which use Warp) and you change the configuration, but don't change the port, I get a configuration error (address already in use) and the reload fails. Workaround is to just change the port to a new value. After a successful reload you can then change the port back to the original.
It's not a huge issue, but I wanted to see if it was known.

```
ERROR vector::topology: Configuration error: Source "in": Address already in use (os error 48)
ERROR vector: Reload was not successful.
```

**Comment by ktff** [comment]
It's a product of our procedure for updating the topology. It goes like this:
1. Create new sources/transforms/sinks.
2. If we failed in building any of them, then the config file is considered invalid, otherwise continue.
3. Shutdown replaced/removed sources/transforms/sinks.

In this case `http / logplex / splunk_hec ` sources are trying to use port, in step 1., of old sources who will only release them in step 3.

I'm only getting some wild ideas on how to fix this, all of which have to large of a cost to be worth it.

Most generic solution would be to move 3. step before 1. step, but then we would have a time for which vector wouldn't work which would only grow larger if 2. step fails. Not to mention the complexity of completely rewriting 3. step. 

Other group of solutions are based on an idea of a resource which can be acquired/released during step 3.. `port` would be such a resource. 


@LucioFranco do you see some simpler solution?

**Comment by binarylogic** [comment]
Yep. This case makes it evident that we need to change this. I agree with your suggestion of moving step 3 up. To be clear, we should:

1. **Validate the new config.**
   We want to detect errors before making changes. This should lint the config, check the topology references, and perform health checks (if enabled). Exactly as if they were starting Vector.
2. **Determine how the topologies differ.**
3. **Send the shutdown signal to any sources that need to be replaced.**
4. **Wait for sources to shutdown.**
   The new shutdown sequence should have a deadline that'll force kill. I'm also assuming that shutting down the sources will shutdown connected transforms and sinks.
5. **Make changes**

I'm assuming we are currently performing a diff to determine the exact topology changes we need to make. In order to simplify this, I'd be in favor of shutting everything down and then restarting with the new config entirely, not performing a diff.

**Comment by LucioFranco** [comment]
So the time difference between step 4 and 5 can be up to 10 seconds, which I think is reasonable but is a bit long.

One issue with step one here is that we do sometimes do validation at build time that can unfortunately also mean it attempts to bind a socket. So that may not work as expected. 

I think overall @binarylogic how you have it laid out seems like the ideal solution for now without doing anything super crazy. I'd still be very cautious about unknown assumptions we have in the code.

**Comment by ktff** [comment]
Moving the step 3. has it's problems, mainly this

> One issue with step one here is that we do sometimes do validation at build time that can unfortunately also mean it attempts to bind a socket

It is possible to extract some of this validation to step 1 , but even then we can't extract all of it. For example we can't check if the ports are free since we will only release them in 4, so it's possible for everything to pass, to shutdown to succeed and then in 5, during the actual binding of the port, to determine it's in use by something else. In such scenarios the time difference between 4 and 5 will grow larger, this is what I mentioned in the first comment regarding failure of 2 step. 

So I'm not really for moving the steps around until we see if there are some simpler options.

**Comment by LucioFranco** [comment]
The other option, which is quite complex, is to detect what config options are changing. If none of them affect the listener (which realistically should only be the address config option) then we can just pass the fd from one sink to another and not lose any events. But this would require a lot of work.

**Comment by binarylogic** [comment]
What is the problem with?

1. Validate new config (linting + topology _only_)
2. Determine how topologies differ.
3. Gracefully shut down changed components.
4. Start the new components (only perform health checks if they were enabled originally).

That's simpler. I'd also be open to forgoing #3 to simplify this even further. My concern about that is that the process won't be different than simply shutting Vector down and restarting it. The goal of a "hot reload" is to reduce disturbances the best we can. What do you think?

**Comment by binarylogic** [comment]
> So I'm not really for moving the steps around until we take some time to see if there are some simpler options and potentially exploring them.

I'm open to this too. The only idea I have is what @LucioFranco pointed out. If we can do that, and that's simpler, I'm open to trying it. The end result is much better than what I outlined, but it sounds more complicated.

Additionally, we could flag options that warrant a shutdown. Such as the `address` option, and document it as such (this option cannot be changed on the fly and requires a full restart of the component).

Let's pick a direction and try it though. I don't want to leave this issue hanging.

**Comment by ktff** [comment]
Then we should move with

>     1. Validate new config (linting + topology _only_)
> 
>     2. Determine how topologies differ.
> 
>     3. Gracefully shut down changed components.
> 
>     4. Start the new components (only perform health checks if they were enabled originally).

and try to achieve it by refactoring current code. If that won't be possible, we can start considering how to rewrite it.

**Comment by LucioFranco** [comment]
It would be good to test also using `SO_REUSEADDR`:

```
SO_REUSEADDR
              Indicates that the rules used in validating addresses supplied
              in a bind(2) call should allow reuse of local addresses.  For
              AF_INET sockets this means that a socket may bind, except when
              there is an active listening socket bound to the address.
              When the listening socket is bound to INADDR_ANY with a spe‐
              cific port then it is not possible to bind to this port for
              any local address.  Argument is an integer boolean flag.
```

http://man7.org/linux/man-pages/man7/socket.7.html

**Comment by ktff** [comment]
I tested with `SO_REUSEADDR` turned on and off, nothing changed. I suspect that even when turned off the rules allow reuse, it's just that this flag signals that it `should` allow reuse.
