### ISSUE TITLE
`cd tests && make` makes `target` dir owned by `root`

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#2125]
After and while I run `cd tests && make`, the `target` dir gets owned by `root`. This must be an artifact of using docker as our test runner environment.

This is annoying, and I'd like to see if we can do something about it.

**Comment by a-rodin** [comment]
I agree that it's annoying, but unfortunately it is because some checks do require root permissions. For example, `package-rpm` requires root because RPM does, or `build-aarch64-unknown-linux-musl` needs to set up `binfmt` handlers. It might be possible to rework it to not require root, but it would require significant additional changes.

Actually, the jobs which can run without root, such as `check-generate`, already run without it (note the `user` parameter): https://github.com/timberio/vector/blob/ff4a6dccefc16f56910d49b996f797ef75de1759/docker-compose.yml#L136-L144

If these tests run in CI, then requiring root access is not an issue because the whole job already runs in an isolated VM.

**Comment by MOZGIII** [comment]
Maybe the ones that require `root` could just use an ephemeral volume instead of the `target` dir form the host?

**Comment by a-rodin** [comment]
I think having it as a directory in the source tree is nicer because it is easier to inspect the artifacts. Furthermore, as we plan to to use it in CI, it should also be possible to extract the artifacts produced by jobs like `build-archive`.

If from the arguments above it is preferable to have the target directory in the source tree, but it is still desirable to make it possible for the host toolchain and the toolchain running inside Docker to not clash, there are at least three possible solutions:

1. Mount `target` inside the containers to a different directory, for example `target_` (similar to the proposal from https://github.com/timberio/vector/issues/2125#issuecomment-603284431).
2. Set environment variable `CARGO_TARGET_DIR` to `target_` in the host shell, which would make `cargo` commands to use another directory.
3. Set `CARGO_TARGET_DIR` inside the containers (some care is necessary because some of the scripts in `scripts` assume that the `CARGO_TARGET_DIR` is always `target).

However, I personally just run `sudo chown -R $(whoami) target` if I want to make the `target` directory writable after touching it from a container running under the `root` user. Changing the owner of the target directory doesn't invalidate `cargo` cashes. Nonetheless they frequently do become invalidated, which is caused not by the ownership by the `root` user, but the fact that the toolchain in the container is different from the one on the host and thus overwrites some of the intermediate files produced by the host.

But I feel that the option 2 is the easiest way to deal with the problem.

**Comment by MOZGIII** [comment]
I would prefer that no files owned by root ended up on my host machine by default.

What if we make it configurable whether to use the directory from the host or ephemeral volume as `target` in docker via host environment variable? In a CI environment, we'll make it so it creates directories, and on my local environment, I'm almost never using artifacts directly from the target directory.

In some of my work environments, evaluating privileges in under an additional safeguard, so it becomes very annoying to do `sudo chown -R $(whoami) target` or `sudo rm -rf target`. Having files that are owned by root under the development directory makes no sense in the first place.

Also, we probably can get rid of the need to use root in the containers altogether if we do the execution more granularity. For example, we don't need to `root` to build an archive and the RPM - only to verify that it installs properly. That task never produces artifacts, and in that sense, we should have no tasks at all that would actually require writing files to host as `root`.

I personally am on the verge of setting up a local VM to run our docker tests. It kind of negates the benefits of a container-based test environment altogether.
