### ISSUE TITLE
Tutorial on https://vector.dev/guides/getting-started/your-first-pipeline failed

### ISSUE THREAD

**Issue by mesmez** [timberio/vector#2307]
The tutorial on:

https://vector.dev/guides/getting-started/your-first-pipeline

Here's what went wrong:

> Apr 12 10:47:45.305  INFO vector: Log level "info" is enabled.
> Apr 12 10:47:45.305  INFO vector: Loading configs. path=["vector.toml"]
> Apr 12 10:47:45.307 ERROR vector: Configuration error: "vector.toml": unknown variant `codec`, expected `text` or `json` for key `sinks.bar`

Changing the vector.conf resolved the error:
`encoding.codec = "text" --> encoding = "text"`

**Comment by Hoverbear** [comment]
Hey @mesmez ! Turns out this is because the docs have been updated to reflect a new feature, while you're still using an older version of vector.

We're working on versioning our docs in #1291 .

I'm sorry you stumbled into this, and super glad you figured  it out! Thanks for reporting this issue and don't hesitate to report any others you find!
