### ISSUE TITLE
Fix broken install script

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#2358]
Current our [install script](https://github.com/timberio/vector/blob/master/distribution/install.sh) (sh.vector.dev) is broken attempting to add the downloaded binary into the `$PATH`. But this prompted some questions, and I need some feedback on the best behavior. For background:

1. Previously, the install script detected package managers (`dpkg`, `rpm`, `brew`, etc) and attempted to install Vector using those. Unfortunately, some of these require `sudo` privileges, `dpkg` specifically. So the script would error unless it was invoked with `sudo`, which is crazy for script downloaded from the internet. Definitely not something I want to tell users to do, even if it is our own script.
2. #1265 removed packager managers as a result.
3. So now, currently, the install script installs solely from our `*.tar.gz` archives into a `$PWD/vector` directory. This, I think, matches the `sh.rustup.rs` behavior?
4. This also has the added benefit of producing a consistent end state which is useful for step-by-step tutorials. Ex: install vector -> modify `$PWD/vector/config/vector.toml`.

So my questions are:

1. Do we all agree this is the best user experience? For example, do we want someone on say, Debian, to use this script when we have a `.deb` package that likely offers a better UX? In other words, should we drop the script all together?
2. If we want to keep the script, does it make sense for this install script to attempt to modify the `$PATH`? Are there any good examples of how to do this across multiple platforms?

**Comment by Hoverbear** [comment]
There are a number of usability  reasons for us to push for being included in official repos once we hit 1.0.

I think the vast, vast majority of users who can, will opt for one of the following whenever they can:

```bash
apt install vector #ubutu/debian
rpm install vector #rhel
pacman -S vector #arch
scoop install vector #windows
choco install vector #windows
brew install vector #mac
pkg add vector #Freebsd
docker run timberio/vector #docker
```

It's good that we don't try to magically call them, since most users who have those and do end up at our site without Vector installed probably already tried using their package manager.

The FHS standard suggests `opt` on Linux : https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard
