### ISSUE TITLE
New `azure_blob_storage` sink

### ISSUE THREAD

**Issue by perfectayush** [timberio/vector#2402]
Vector already supports AWS S3 and Google cloud storage as sinks. Are there any plans to support azure blob storage? 

Although I have limited experience in rust, I am willing to contribute for this one.

**Comment by binarylogic** [comment]
Thanks @perfectayush, yes, we definitely want to support it given that Azure is popular. It's just been a matter of priority. We'd love for you to contribute, and the `aws_s3` and `gcp_cloud_storage` sinks should provide good examples. I will warn you, these sinks are a little more complicated due to the fact that they can partition data across dynamic keys/paths. For example, the [`key_prefix` option](https://vector.dev/docs/reference/sinks/aws_s3/#key_prefix) in the `aws_s3` sink allows for templated values. We're happy to help. The best way to do that would be to open a draft pull request and we can comment on there.

**Comment by elsesiy** [comment]
We'd love to use vector but the lack of azure storage support is hard sell today. @perfectayush have you done any work on this? I'm happy to take a stab at it or co-author, let me know. Thanks!

**Comment by ArtemTrofimushkin** [comment]
@perfectayush 
Here is a draft version for AzureBlobSink, that I tried to implement.  
Please, leave some comments about this

https://github.com/timberio/vector/pull/6861

**Comment by perfectayush** [comment]
Hi @ArtemTrofimushkin , @elsesiy I had taken a jab at it but couldn't move past due to inexperience in Rust and other work priorities. At that time, we decided to go ahead with azure file storage instead due to time constraints.

Also, I am not working on Azure Services anymore, so can't test this. I will give it a look, but core vector team is better suited to review it.

**Comment by ArtemTrofimushkin** [comment]
@perfectayush Thanks for help!
Hi @binarylogic, can you take a look and give some comments about implementation, please?  

https://github.com/timberio/vector/pull/6861

**Comment by jszwedko** [comment]
Closed by https://github.com/timberio/vector/pull/6861
