### ISSUE TITLE
Review all sinks to ensure tls settings are set correctly

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#2445]
Looks like with a lot of the movement that we've had with tls types and http clients over the past month or so has caused some confusion around when tls settings are enabled or not by default. We should do a re-review of our sinks and if some sink should have tls settings enabled by default.

**Comment by binarylogic** [comment]
Noting, we need a simple requirements list before we start work on this. Basically, decided on which sinks should be enabled by default and verifying their settings.

**Comment by binarylogic** [comment]
@jamtur01, just to clarify, I am assigning you just for building the requirements so we can then assign the work.

**Comment by jamtur01** [comment]
The sinks that have TLS capabitilities are, with their statuses:

- [ ] Vector (optional - defaults off)
- [ ] Socket (optional - defaults off)
- [ ] Papertrail (required)
- [ ] Kafka (optional - defaults off)
- [ ] The GCP sinks (optional - defaults on)
- [ ] Loki (optional - defaults on)
- [ ] Clickhouse (optional - defaults on)
- [ ] Elasticsearch (optional - defaults on)
- [ ] HTTP (optional - defaults on)
- [ ] Splunk HECS (optional - defaults on)
- [ ] New Relic logs (required)
- [ ] All AWS sinks (required)

**Comment by binarylogic** [comment]
Thanks! I think we can eliminate the HTTP-based sinks since TLS is based on the protocol provided in the endpoint. This is why they don't have a `tls.enabled` setting. That leaves us with socket-based sinks, which we need to change in a couple of places:

- [ ] `papertrail` sink - optional - defaults to on
- [ ] `datadog_logs` sink - optional - defaults to on

I'm drawing the line on hosted/service-based integrations, since data will travel over the public internet. A case could be made for also securing internal communications since cloud environments are shared. If we want to go that direction then we'll need to add more to this list.

cc @jszwedko, I'm curious what you think.

**Comment by jszwedko** [comment]
:+1: I think that distinction is reasonable. I'd prefer to default to TLS for sinks that typically travel over the internet to provide a more secure default even if it does differ from other sink defaults.

**Comment by binarylogic** [comment]
@ktff assigning this to you. It appears we only need to default to enabling the `papertrail` and `datadog_logs` sink.
