### ISSUE TITLE
Develop automated behavior tests for request limiting

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#2531]
Follow up to #2529 

In order to ensure that the automated rate limiting achieves the required behavior and does not regress, Vector needs tests that can verify these behaviors under a variety of well specified conditions. These tests should become part of the standard test framework. Depending on the time required to run the tests, they might need to be relegated to a nightly test run instead of happening on every pull request.

**Comment by binarylogic** [comment]
@jszwedko if you could start by posting ideas on how we'd go about this, that would be a good first step.

**Comment by bruceg** [comment]
I think a first step might be to rework the tests in `src/sinks/util/auto_concurrency/tests.rs`. All of those tests are based on how the limiter responds to various levels of concurrency and delay. A better metric, based on the actual goal of this feature, would be to test based on request rates. The existing framework could be reused, as it provides statistics on at least some of the things we want to measure.

**Comment by jszwedko** [comment]
For this, it seems like the options are:

* Extending the integration tests in Vector
* Rely on the output from the `http_test_server` concurrency tests (#3255). I think this would involve extending it some to output measures like average throughput that we could use to check for regressions from expected behavior.

I think the pros/cons are:

Integration tests in Vector:
* Pro: More deterministic with tighter control
* Pro: Easy to implement in existing test suite
* Con: Duplicates some of the tests from `http_test_server` suite

Running `http_test_server` tests:
* Pro: reuse same test suite we use to measure black-box behavior of vector and other tools
* Pro: `http_test_server` suite is exercised more often
* Con: More work to extend and integrate into CI than Rust-based tests

I think either one would be workable, but would lean towards:

* Extending the integration tests in vector
* Running `http_test_server` suite in CI, but just upload the plots and data as artifacts

**Comment by binarylogic** [comment]
I'm deferring this work until we have time/resources. This way we can close the initial auto concurrency epic.
