### ISSUE TITLE
Change config types in docs to appropriate types in code

### ISSUE THREAD

**Issue by fanatid** [timberio/vector#2592]
Based on https://github.com/timberio/vector/pull/2590#issue-417441145 & https://github.com/timberio/vector/pull/2590#issuecomment-628153215

Gonna take it after https://github.com/timberio/vector/pull/2493#issuecomment-628155209

**Comment by fanatid** [comment]
Before done this, some questions after first review:
- `f32` => `float`
- `f64` => `double`
- `i32` => `int`
- `i64` => `long`
- `u32` => `uint`
- `u64` => `ulong`
- `usize` => ?

Or types in docs should be just changed to: `f32` / `f64` / `i32` / `i64` / `u32` / `u64` / `usize`?

**Comment by lukesteensen** [comment]
TOML only has `integer` and `float`, so it probably makes sense to stick with that terminology. We can add the concept of signed/unsigned since that's meaningful for us.

* `f32` => `float`
* `f64` => `float`
* `i32` => `int`
* `i64` => `int`
* `u32` => `uint`
* `u64` => `uint`
* `usize` => `uint`

It may even be nice in the future to decouple the TOML types from the Rust types a bit. For example, it's convenient to use `-1` as a shortcut for `usize::MAX`. But for the time being, I think the above is fine.

**Comment by fanatid** [comment]
OK, I changed `int` to `uint` where type is not `i32`/`i64`.
