### ISSUE TITLE
[RFC] Make SinkConfig::build async

### ISSUE THREAD

**Issue by Keruspe** [timberio/vector#2687]
In the next version of the pulsar-rs library, creating the Pulsar object that we use for the sink will be async, thus we'll need to run some async code in SinkConfig::build.

We can either make that async or maybe pass around the runtime so that we can block_on there?

You can see current wip update here: https://github.com/CleverCloud/vector/tree/pulsar-update which currently errors in SinkConfig::build

**Comment by lukesteensen** [comment]
Yep, this is something we've talked about for a while and agree needs to change. I'm planning to address this in #2625.

**Comment by fanatid** [comment]
@Keruspe @Geal do you have any ETA for stable `pulsar-rs` 1.0.0?

**Comment by Geal** [comment]
not yet, but there's not much to do: API cleanup, documentation, and a bit of testing (if you already have feedback on usage in Vector it would be a big help)

**Comment by fanatid** [comment]
Thanks! We did not tried new version in vector yet, but I planning try it on next week.

**Comment by Keruspe** [comment]
We have a port of vector available fwiw. I worked around this issue by
spawning the future on the executor and waiting on a channel

**Comment by fanatid** [comment]
@Keruspe @Geal we updated pulsar to `1.0.0-alpha-2` (#2977), but noticed one strange thing.
[Producer](https://docs.rs/pulsar/1.0.0-alpha-2/pulsar/producer/struct.Producer.html) implement traits `Sync + Send`, but in same time need `&mut self` for [send method](https://docs.rs/pulsar/1.0.0-alpha-2/pulsar/producer/struct.Producer.html#method.send) (and for `create_message` too). As a result, we need wrap Producer into Mutex, because otherwise, we can not get `mut` object.
At a first quick glance there two possible solutions:
- add Mutex to `producers` field: https://github.com/wyyerd/pulsar-rs/blob/57247b817ecfa6616ac04a5cbad77310cb3d9949/src/producer.rs#L333 (preferred)
- remove `Sync` trait
