### ISSUE TITLE
The LOG file of disk buffer becomes very large.

### ISSUE THREAD

**Issue by panpan-wu** [timberio/vector#2925]
```
ubuntu@ip-192-168-20-141:/var/lib/vector$ ls -alh sink_tcp_log_buffer
total 21G
drwxr-xr-x 2 vector vector 3.6M Jul  1 02:49 .
drwxr-xr-x 4 vector vector 4.0K May 26 07:55 ..
-rw-r--r-- 1 vector vector  426 May 28 03:44 001249.ldb
-rw-r--r-- 1 vector vector    0 Jul  1 02:49 31102680.log
-rw-r--r-- 1 vector vector  827 Jul  1 02:49 31102681.ldb
-rw-r--r-- 1 vector vector   16 May 28 03:44 CURRENT
-rw-r--r-- 1 vector vector    0 May 26 07:53 LOCK
-rw-r--r-- 1 vector vector  20G Jul  1 02:49 LOG
-rw-r--r-- 1 vector vector 368K May 28 03:29 LOG.old
-rw-r--r-- 1 vector vector 1.7G Jul  1 02:49 MANIFEST-001238
```
Could I delete the LOG file?

vector.toml

```
[sinks.sink_tcp_log]
  inputs = ["src_tcp_log"]
  type = "socket"
  address = "the_address_of_vector_cluster"
  mode = "tcp" # required
  healthcheck = true # optional, default

  buffer.type = "disk"
  buffer.max_size = 1073741824 # 1G
  buffer.when_full = "block" # optional behavior: drop_newest

  encoding.codec = "text"
```

**Comment by binarylogic** [comment]
@lukesteensen I'm curious if this is expected behavior?

**Comment by lukesteensen** [comment]
I did a little [digging](https://tracker.ceph.com/issues/5175) and it looks like leveldb maintains its own log file (i.e. for log messages, not data being stored). That means it should be perfectly fine to delete that file. It also seems to be cleared on restart.

That being said, it's possible our frequent compactions will regularly cause to file to become larger when Vector is run continuously for a long period of time. There doesn't seem to be a good way to turn off this logging, which is unfortunate. So I think there are two options if we want to try to address this:

1. Add some kind of management of this file to Vector itself and actively try to keep it small
2. Assume that this rarely becomes an issue and wait until we eventually move off of leveldb to a different implementation that does not create its own log files

I lean towards option 2, but only because we've seen this reported a single time. If more users are encountering this, or we're able to reproduce it easily in a realistic scenario, we can consider taking a stronger approach.
