### ISSUE TITLE
The Elasticsearch sink drops events when a 429 is returned from one of multiple indexes

### ISSUE THREAD

**Issue by djensen1997** [timberio/vector#2968]
Vector's Elasticsearch sink prints the message `WARN vector::sinks::util::retries2: request is not retryable; dropping the request. reason=some messages failed` when a bulk insert returns with a 200 status for the base request, but individual inserts returned a `429` because the individual node insert queue is full.  This is causing vector to drop all the data from that bulk request that did not get queue correctly.

My elasticsearch sink config is as follows:
```yaml
sinks: |
  [sinks.elasticsearch]
  type = "elasticsearch"
  inputs = ["input"]
  index = "logstash-topic-{{field}}-ingest"
  host = "https://elasticsearch-master:9200"
  [sinks.elasticsearch.batch]
  max_size = 20490000
  timeout_secs = 2
  [sinks.elasticsearch.auth]
  strategy = "basic"
  password = "${ELASTIC_PASSWORD}"
  user = "${ELASTIC_USERNAME}"
  [sinks.elasticsearch.tls]
  ca_path = "/etc/secret/elastic-cert/elastic-stack-ca.pem"
  [sinks.elasticsearch.request]
  in_flight_limit = 20
  rate_limit_num = 10
  rate_limit_duration_secs = 5
  retry_initial_backoff_secs = 5
  retry_max_duration_secs = 20
  timeout_secs = 120
```

This setup splits the data into one of 3 different indexes based on the value that {{field}} has, which increased stability of the elk stack itself and reduced shard size, but is causes the response from elasticsearch to contain multiple results, one for each index attempted to insert into

**Comment by ktff** [comment]
It's as @djensen1997 said, the whole request is OK, but the individual operations may fail, so when we check for errors in retry logic we determine that there are failed operations for which we say are not retryable and by extension the whole request. 

### Solution
We can use `At-Least-Once` guarantee of `elasticsearch` sink and retry the whole request if any of the individual operations fail with retryable error. This would solve the issue, but there are consequences:
- Retried successful operations would have it's version updated. This shouldn't be an issue since this can already happen.
- Retrying with all operations can have kind of magnifying effect, in a sense that successful operations now have a chance to also fail, causing additional retries. But our retry logic should be able to take care of this.

### Alternatives
* Propagate information, on which individual operations failed, back to point of encoding, and retry from that point. Alternatively we could get away with propagating it to the point of sending the request and then `decoding`-`filtering`-`rencoding` it. 
   - Would require significant changes to signatures of our `http` stack, and used libraries.

**Comment by binarylogic** [comment]
> We can use At-Least-Once guarantee of elasticsearch sink and retry the whole request if any of the individual operations fail with retryable error. 

I've worked quite a bit with Elasticsearch, both internally and with customers. We should avoid retrying _entire_ requests with partial failures. Partial failures are _very_ common in the logging use case with Elasticsearch. This would cause a lot of duplicate data and unintended side effects for most users. This is why [Logstash itself does not do this](https://www.elastic.co/guide/en/logstash/master/plugins-outputs-elasticsearch.html#_retry_policy).

The proper solution is to parse the response and only retry individual records whose errors suggest a retry might resolve the issue. As you noted, this would require a significant amount of work so I'd like to defer the fix and close this in favor of https://github.com/timberio/vector/issues/140.
