### ISSUE TITLE
The `humio_logs` sink timestamps should include fractional seconds

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3082]
Following up on https://github.com/timberio/vector/issues/2568#issuecomment-659354566. I'd be surprised if this is accurate. We should verify that logs include fractional seconds for the `humio_logs` sink.

**Comment by jszwedko** [comment]
So it looks to me like the issue here is actually that we started sending `sourcetype` to in the humio sink as part of https://github.com/timberio/vector/pull/2318. For a syslog source, we end up sending something like:

```
POST /services/collector/event HTTP/1.1
content-type: application/json
authorization: Splunk REDACTED
user-agent: Vector/0.10.0 (v0.10.0 x86_64-unknown-linux-gnu 2020-07-27)
host: localhost:8081
content-length: 319

{"event":{"appname":"CORP\\jesse","facility":"user","host":"a-8cktst39ij0a","hostname":"a-8cktst39ij0a","message":"Hello world 105","severity":"notice","source_ip":"127.0.0.1:45296","source_type":"syslog","timeQuality":{"isSynced":"0","tzKnown":"1"},"version":1},"fields":{},"sourcetype":"syslog","time": 1595882540.555}
```

With `sourcetype` = `syslog`, humio appears to to parse the JSON event as a syslog message, resulting in an error:

```
Error parsing timestamp. errormsg="Text '**redacted**' could not be parsed at index 0" zone="Some(UTC)" \| timestamp was not set to a value after 1971. Setting it to now
```

If I leave out `sourcetype`, it parses our timestamp correctly including the milliseconds.

I think the correct thing to do here is not to send a `sourcetype` to humio when we are sending already structured data. If there are cases where we'd send a string (I don't believe there are any?), we could set the sourcetype appropriately to let humio do the parsing.

**Comment by binarylogic** [comment]
Good find. Yes, we should remove the `source_type` field altogether. That was, unfortunately, a change that we realized was fundamentally flawed along the way (#2147). A better solution for this is in the form of metadata which we don't currently have support for. I'll open issues to remove this field and reset our approach to this.

**Comment by jszwedko** [comment]
@binarylogic to be clear, I think the `source_type` in `event` is fine. This is about sending `sourcetype` at the top-level for the HEC sink.

Formatting the humio payload to make it easier to see:

```json
{
  "event": {
    "appname": "CORP\jesse",
    "facility": "user",
    "host": "a-8cktst39ij0a",
    "hostname": "a-8cktst39ij0a",
    "message": "Hello world 105",
    "severity": "notice",
    "source_ip": "127.0.0.1:45296",
    "source_type": "syslog",
    "timeQuality": {
      "isSynced": "0",
      "tzKnown": "1"
    },
    "version": 1
  },
  "fields": {},
  "sourcetype": "syslog",
  "time": 1595882540.555
}
```

**Comment by binarylogic** [comment]
Got it. That was introduced in https://github.com/timberio/vector/pull/2318 which was instigated by #2142 and #2116. Notice in #2116 this is used to route data effectively for Splunk HEC. If we did remove this field, we should remove it specifically for the `humio` sink, and not `splunk_hec`.
