### ISSUE TITLE
Add `multiline`options for the `docker` source

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3307]
We have users requesting the ability to merge logs within the `docker` source in the same exact way we offer it in the `file` source via the `multiline` options.

## Implementation

I have spoken with numerous people on the team, and we would like to implement this in the simplest way possible. The [line aggregation code](https://github.com/timberio/vector/blob/master/src/sources/file/line_agg.rs) has already been extracted from the `file` source. We would like to simply add it to the `docker` source in the same way.

## Requirements

- [ ] Add the same `multiline` options in the `file` source to the `docker` source
- [ ] Use the same [line aggregation code](https://github.com/timberio/vector/blob/master/src/sources/file/line_agg.rs) across both sources.
- [ ] Ensure that merging is scoped to a single stream using the `container_id` metadata (or combination of metadata if this isn't sufficient).
- [ ] Do NOT introduce any generic concepts across sources like pre-processors, new traits, or anything like that. Once we get this implemented across 2 sources we can consider it then.

**Comment by MOZGIII** [comment]
It seems like we need to parse the message (not nesessarily into an event, but maybe into an intermediary format) before we can properly apply merging logic. The reason for this is docker source received the raw messages "wrapped" with docker metadata - like timestamp and labels.

Also, docker source has streams that are already scoped by the container, so there's no need to apply any filtering by `container_id` - we can just consume the stream.

One of the downsides is though that since we sometimes have to emit more two messages after the line aggregation logic kick in, and we need to carry-on the extra context that docker provides - like the `container_id`, `timestamp` and labels - for the first message (for the second message one those two the context is typically available at the calling point).

I've created a PR to prepare `LineAgg` to allow passing the extra context around - #3561.

The next step would be to refactor the `docker` source a bit to allow working with context, and to more naturally apply the `LineAgg` (and lay it atop of the partial event merging). This should be relatively trivial once we merge the #3561.

Does this plan sound good?
