### ISSUE TITLE
Vector won't run - Mac OS X - 10.13.6

### ISSUE THREAD

**Issue by michaelwilde** [timberio/vector#3336]
My Homebrew installation is now pretty clean, I've upgraded to Xcode 10.1 (I'm on Mac OS 10.13.6).  Cant get vector to run.  Here's some output that might help

> thewilde at xyz ~ : brew config
> HOMEBREW_VERSION: 2.4.9
> ORIGIN: https://github.com/Homebrew/brew
> HEAD: e6b066a3d9fc5435009428fcd2855fddf9b455c0
> Last commit: 7 days ago
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: 2ef541230ffbe4e5e6795564848bfdbea24d569c
> Core tap last commit: 11 minutes ago
> HOMEBREW_PREFIX: /usr/local
> HOMEBREW_MAKE_JOBS: 8
> CPU: octa-core 64-bit sandybridge
> Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
> Clang: 10.0 build 1000
> Git: 2.28.0 => /usr/local/bin/git
> Curl: 7.54.0 => /usr/bin/curl
> Java: 1.8.0_60, 1.8.0_51
> macOS: 10.13.6-x86_64
> CLT: 10.1.0.0.1.1539992718
> Xcode: 10.1
> thewilde at xyz ~ : vector
> dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
>   Referenced from: /usr/local/bin/vector (which was built for Mac OS X 10.15)
>   Expected in: /usr/lib/libSystem.B.dylib
> 
> dyld: Symbol not found: ____chkstk_darwin
>   Referenced from: /usr/local/bin/vector (which was built for Mac OS X 10.15)
>   Expected in: /usr/lib/libSystem.B.dylib
> 
> Abort trap: 6
> thewilde at xyz ~ :

**Comment by michaelwilde** [comment]
I could just try building from source.

**Comment by Hoverbear** [comment]
Hey @michaelwilde ! I suspect that's because we use Github Actions to build our Mac builds now, and they use OS X 10.15. (Ref: https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources)

I'm afraid in order have a version of Vector support OS X 10.13 we might need to make a modification.

I think we might be able to use a technique like this on our CI to resolve this: https://users.rust-lang.org/t/compile-rust-binary-for-older-versions-of-mac-osx/38695/5

**Comment by michaelwilde** [comment]
Yep, don't do anything extra for me, building from source is just fine!
