### ISSUE TITLE
Handle explicit backpressure in auto-concurrency layer

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#3424]
The auto-concurrency layer detects backpressure based on RTT timing increases or retriable errors. Additional logic should be added to handle explicit backpressure notifications such has HTTP 429 responses.

This will proceed by either adding a method to `RetryLogic` to indicate the backpressure status of either a response or error or, if possible, by adding a new trait implemented by all responses and errors indicating the same:
```rust
pub trait IsBackPressure {
  fn is_back_pressure(&self) -> bool;
}
```

**Comment by binarylogic** [comment]
@bruceg it's worth considering recognizing [common rate limit headers](https://tools.ietf.org/id/draft-polli-ratelimit-headers-00.html#header-specifications) as part of this work, since they can hint at the exact wait time necessary. A good example of this in the wild is [Github's rate limit headers](https://developer.github.com/v3/rate_limit/).
