### ISSUE TITLE
Configurable `level` for the `internal_metrics` source

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3529]
Like logs, some of our internal metrics can be noisy and high volume. It may be advantageous to ignore these metrics with a configurable level, as opposed to white/blacklisting them.

## Example

```toml
[sources.internal_metrics]
type = "internal_metrics"
level = "info"
```

## Requirements

- [ ] Add a `level` option to the `internal_metrics` source that is an enumeration of `trace`, `debug`, `info`, `warn`, and `error` (the same levels as our logs).
- [ ] Classify metrics accordingly. (this will require some discussion around implmentation)

## Open Questions

1. How will this affect the upcoming admin UI?
2. Is this even necessary? I mostly opened this to control the volume of metrics written downstream, because I don't think this will have much effect on performance (I could be wrong).

**Comment by binarylogic** [comment]
Tend to agree with both of you. I think this will become more obvious as we add more metrics. I'll leave the `needs: approval` label on and we can re-evaluate at a later date.

> I might suggest maybe by domain, or allowlist/denylist patterns to be more familiar.

Also agree with this.

**Comment by JeanMertz** [comment]
Since `internal_metrics` is a source in and of itself, there's no reason why filtering can't happen by a set of downstream transforms, right?

I guess the only two reasons for this to exist then are:

* It's a nicer way to filter than using a filter that ignores JSON messages with field `level` set to `error`, for example.
* It allows us to filter at the _source_, which might be beneficial to Vector's performance, as the internal events don't have to be passed along to the transform that would normally filter them.

I also think this feature wouldn't have any impact on the admin UI, as this is about the end-user wanting to filter Vector's internal metrics for their own use, while the Vector UI will read internal events from an internal system — the same system that feeds the `internal_events` source, but any transforms applied by the user (either through configuration of this source, or through downstream transform components) would not apply to the events sent to the Vector UI.

**Comment by binarylogic** [comment]
Closing for now, we can reopen if users request a way to select specific metrics.
