### ISSUE TITLE
Drop `*_key` options in favor of new `remap` option

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3633]
Once #3463 is done, we should drop the various `*_key` options and allow users to remap events to their liking with the new `remap` option.

- [ ] Preserve backward compatibility by deprecating these options and removing them from our docs.
- ... will fill out with specific options.

**Comment by lukesteensen** [comment]
This is an interesting idea but I do think it's missing one facet of the `*_key` options. Those were very much intended to point out the location of well-known fields (e.g. message, host, timestamp) so that downstream components that use those well-known fields would access them correctly. The current implementation happens to accomplish that by mapping them to specific field names, but a more sophisticated implemenation could have simply recorded some metadata.

If we switch to simply using `remap` for this, it's not clear how downstream components should know which field to read. It can be just convention around the names, but that seems more brittle and error-prone than the metadata-based solution.

**Comment by binarylogic** [comment]
Closing since this will be handled as part of solving schemas.
