### ISSUE TITLE
Add `multiline` support for the `journald` source

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3758]
Same as #3307, but for the `journald` source.

**Comment by johntdyer** [comment]
This would be amazing

**Comment by jszwedko** [comment]
Hey @johntdyer . We've actually started pushing towards having users use [`reduce`](https://vector.dev/docs/reference/configuration/transforms/reduce/) which can be chained after any source rather than adding multiline options to the sources themselves. Would that suffice for you?

I'm actually going to close this out as I don't _think_ it is something we'll be doing unless we find journald multiline can not be supported by `reduce`.
