### ISSUE TITLE
 New URL functions for the remap syntax 

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3762]
Similar to #3761, I wanted to open an issue to represent a set of URL related functions. This should cover:

- [ ] Parsing URLs into the various parts (scheme, host, port, path, etc)
- [ ] Easily extracting a specific part.
- [ ] Easily removing a specific part.

I'm not necessarily looking for individual functions for each of these, but more of an agreement around how a user would accomplish the above. This might be a set of functions and syntax changes.

**Comment by binarylogic** [comment]
@JeanMertz, I'm assigning this to you to outline the requirements first. Basically, propose one or more functions that would address this use case.

**Comment by JeanMertz** [comment]
I think the best way forward for this would be to have a `parse_url` function which returns a `Map<Value>`, that contains the syntax components as described in [RFC3986](https://tools.ietf.org/html/rfc3986#section-3).

We can then have a `format_url` function, which takes that same object, and converts it to a string.

Changing (or removing) parts of the URL is then just a matter of manipulating the paths, e.g.:

**input**

```json
{
	"url" : "https://vector.dev/foo?hello=world"
}
```

**remap source**

```js
.url_parts = parse_url(.url)

.url_parts.path = "bar"
.url_parts.scheme = "http"
.url_parts.port = 4333 + 10
.url_parts.fragment = "baz"
del(.url_parts.query)

.url = format_url(.url_parts)
del(.url_parts)
```

**output**

```json
{
	"url": "http://vector.dev:4343/bar#baz"
}
```

The upsides to this approach are:

* no need to specify specialized functions to manipulate URLs
* availability of all other remap functions and arithmetic to manipulate URLs

The downside is that you have to remember to delete the path that contains the parts of the URL if you don't want it to be part of the final event. The latter can be avoided if/when we introduce variables to the language, e.g.:

```js
var parts = parse_url(.url)
parts.path = "bar"
.url = format_url(parts)
```

Here's the function signatures to be introduced:

```rust
parse_url(value = string) -> object
format_url(value = object) -> string
```

We can extend `format_url` in a future iteration to add convenience flags, such as defining if the port should be included in the final output or not.

**Comment by jszwedko** [comment]
This seems like a good approach to me. I can see that variables would make this less confusing for the user than temporary fields.

What is the behavior if the URL cannot be parsed?

**Comment by JeanMertz** [comment]
> What is the behavior if the URL cannot be parsed?

Similar to all other functions that can fail: they will produce an error line, and the transform itself can be configured to either drop an event, or keep the original event if the script (meaning any function within it) fails.

**Comment by FungusHumungus** [comment]
I agree with @jszwedko, we need to think about the error path. 

Will path be an array, or a string? It probably doesn't matter too much, but might be handy if format could cater for both.

**Comment by JeanMertz** [comment]
I would like to be able to have more fine-grained error handling (e.g. define on a per-function basis what should happen if it fails), but I'd rather punt on that for a follow-up PR, since there are many other functions right now that can fail (basically all `parse_` functions, and more), but which you might not want to completely error if they do.

**Comment by FungusHumungus** [comment]
I think a simple, `is_valid_url` could be used if people really did want to do something different for unparseable data.

**Comment by JeanMertz** [comment]
That's true, but I think we want to have a more generic solution to solve this, since many other functions can be written to fail in the future.

The problem we have here is that right now, transforms can be configured to act on failures in a specific way, but with a transform that embeds its own language, you want more fine-gained control over failure conditions.

For Wasm and LUA, this isn't an issue, since those languages themselves support handling error cases, but Vicscript/remap language does not.

I can see us introducing a `try` block or something else to give control to the user on what to do.

But regardless, I think we should move that discussion into a separate issue (I'll create one 👍)

**Comment by JeanMertz** [comment]
Added https://github.com/timberio/vector/issues/4409

**Comment by JeanMertz** [comment]
Closing this as we have `parse_url` which seems to have solved the need of operators.
