### ISSUE TITLE
Prometheus source to support TLS configuration and authorization

### ISSUE THREAD

**Issue by langecode** [timberio/vector#3797]
### Current Vector Version

```
0.10.0
```

### Use-cases

The Prometheus source of Vector supports scraping endpoint support the Prometheus metrics format. Some endpoints, e.g., the Kubernetes control pane components, expose metrics protected by TLS with a self-signed certificate. Currently it is not possible to do any TLS configuration for the Prometheus source, i.e., it is not possible to configure a CA to validate the TLS connection.

Furthermore some of the Kubernetes control pane components requires authentication in the form of a bearer token which can be read from a file mounted into the containers of the Pod.

These configurations are supported by Prometheus but since they are not currently part of the Prometheus source in Vector it is hard to scrape data off the Kubernetes control plane using Vector.

### Proposal

I would propose the following additions:
* Support the same TLS configuration as other sources and sinks
* Allow for specifying a file containing a bearer token to be used in authorization header

Additional configuration properties could be along the lines of:
```
# TLS
tls.ca_file = "/path/to/certificate_authority.crt" # optional, no default
tls.crt_file = "/path/to/host_certificate.crt" # optional, no default
tls.enabled = false # optional, default
tls.key_file = "/path/to/host_certificate.key" # optional, no default
tls.key_pass = "${KEY_PASS_ENV_VAR}" # optional, no default
tls.verify_certificate = false # optional, default

bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
```

### Attempted Solutions

I am attempting a PR for adding this into the Prometheus source of Vector.

**Comment by binarylogic** [comment]
Thanks @langecode. @MOZGIII would this be helpful for the Kubernetes use case?

**Comment by langecode** [comment]
You're welcome. As I digged deeper into this it turns out that this gets more complex. At least for our use case what we really need is the discovery mechanisms of Prometheus where it communicates with the Kubernetes API.

So my conclusion is that instead of re-inventing all this functionality from Prometheus in a new tool like Vector I would much rather deploy Prometheus in my cluster (possibly with a short retention) and use Vector as a "channel" to transfer metrics out from the cluster by having a Vector source supporting the Prometheus `remote write` protocol (see also #2058 ).

**Comment by MOZGIII** [comment]
We've had the same conclusions, and we are aiming to work with Prometheus rather than replace it.

While it seems like an easy task from the first sight, collecting metrics directly like Kubernetes does it is probably a difficult task. We should still probably add support for this mechanism of TLS credentials lookup.
Better if we add it universally (in all TLS-aware places), cause I myself sometimes deploy things with mutual TLS authorization, and Vector is currently lacking the support there.

We're working towards integrating with Prometheus out of the box in the Kubernetes environment.

I'm currently working on additional deployment roles for Vector, focusing on the aggregator role currently, and the collector role will come next - and then we'll work on implementing the Prometheus scraping.

**Comment by langecode** [comment]
Yeah I totally agree having TLS support in a uniform way would be very nice. It seems the primitives is already there in your code base :-)
