### ISSUE TITLE
New `contains` remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#3838]
The `contains` function determines if a string contains a substring.

## Example

```
.error = contains(.message, "error")
.error = contains(.message, /error/)
.error = contains(.message, "error", casesensitive=false) # disables case sensitivity
```

## Requirements

- [x] Case-insensitive by default
- [x] Accepts strings
- [ ] Accepts regular expressions

**Comment by jszwedko** [comment]
I'm unsure if this has already been discussed, but I think keyword options would help with legibility. That is: `.error = contains(.message, "error", casesensitive=false)` (or `casesensitive: false`) instead of `.error = contains(.message, "error", false)`.

This is somewhat similar to Liquid: https://shopify.dev/docs/themes/liquid/reference/filters/additional-filters#default
