### ISSUE TITLE
Consider safeguards for prom sink memory use

### ISSUE THREAD

**Issue by lukesteensen** [timberio/vector#387]
As of #374 the prometheus sink will collect and aggregate all metric events it receives. The aggregation is done by key, so it relies on there being a finite, reasonable number of total keys that it will see. In the case of a misconfiguration or bad input data, this might not be true (e.g. a user could accidentally parse a timestamp into a field intended as a service name and then use that as part of a metric key).

There are a couple things we could do in this area:
1. Expire metric aggregations after a given period of idleness. This could be desirable even in a correct configuration that simply changes the naming scheme of certain metrics over time. However, it likely wouldn't keep up with a pathological case like that of a timestamp key.
2. Set an upper limit on the number of metrics the sink will aggregate. It's hard to know what a reasonable value here would be, so we'd probably want to work backwards from what we'd consider problematic memory use. 
3. Nothing. We could decide this isn't likely enough to worry about, and just let users rely on normal debugging to figure out the issue should it happen (or maybe add some logging that would lead them in the right direction).

**Comment by loony-bean** [comment]
I'm leaning towards doing nothing. Few considerations:
1) Prometheus team [has decided](https://github.com/prometheus/pushgateway/issues/83) that metrics should be deleted only in user-controlled fashion (agent restarts or special http requests).
2) I don't feel that pathological case is a real threat, and even if it will happen, the issue will be visible to operator/alerting and relatively easy to debug.
3)  In case we receive metrics from some legitimate ephemeral short-lived sources (like containers) which put their unique `id`'s into tags (ex. [Gitlab runner](https://docs.gitlab.com/runner/monitoring/#embedded-prometheus-metrics)), the answer should be to drop the `id` tags, because ephemeral metrics are [not a good](https://stackoverflow.com/questions/48324007/how-do-i-deal-with-old-collected-metrics-in-prometheus) fit for timeseries based monitoring in general.

**Comment by lukesteensen** [comment]
That sounds reasonable! Feel free to close this issue if you think it's best to leave things as they are.
