### ISSUE TITLE
Handle multi-line messages

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#388]
It's common for logs to contain `\n` characters. This presents a problem since it causes individual log events to be parsed as multiple events. There are 2 common cases with this:

1. A JSON value contains a `\n` character:

```
{"message": "First line\nSecond line\n"}
{"message": "First line\nSecond line\n"}
```

2. A raw text event uses multiple lines but subsequent lines are typically white-space prefixed.

```
Runtime Error "Boom!"
  /path/to/file.rb:42
  /path/to/file.rb:42
  /path/to/file.rb:42
  /path/to/file.rb:42
  /path/to/file.rb:42
```

This would be a nice problem to solve, and it contributes to the high-quality UX that Vector is after. It's exactly these kinds of details that Vector should handle well.

A couple of ways to solve this:

1. JSON: For any sink configured with a `json` decoder, we could attempt to read lines up to a configurable limit, parsing the accumulated payload until it is valid.
2. Text: We could take the same approach with text lines prefixed with white-space. If a line is prefixed with white-space we would append it to the previous line up to a configurable limit.

Bonus points if we can abstract this out as a general "reader" so that we could front any streaming source with this.

**Comment by karlseguin** [comment]
I think the whiteline prefix idea will miss a lot of cases, for example multiple lines from stacktraces (which you generally have no control over).

Datadog's approach is the opposite: pattern that specifies what a newline starts with.  Anything that doesn't start with this is considered part of the previous line.

You might need to support both approach to cover all cases, but I think a lot of loggers let you specify the log format which lets you control what goes at the start (but not the content/body of the log itself).

**Comment by binarylogic** [comment]
Thanks @karlseguin that actually makes a lot of sense. We'll firm up the requirements on this before we begin work. I added the `needs review` label for that.

**Comment by bittrance** [comment]
Indeed, e.g. the docker awslogs agent does both https://docs.docker.com/config/containers/logging/awslogs/#awslogs-multiline-pattern though limited to datetime format. A version that has a "start-new-log-entry-regex" and a "log-entry-continuation-regex" would probably do the trick.

The other question is whether this is a feature of the file, stdin and syslog sources or a separate transform? The general issue is that you need to read line `n+1` to know if line `n` can be emitted, with the accompanying timeout. With a transform you can choose whether or not you want this. The downside with implementing it as a transform (above requiring explicit configuration of something that is likely to be very common) is that you would need to tell it what to aggregate/concatenate on, since you would normally want the aggregation to be per-source-file.

UX tradeoffs 😒 .

**Comment by lukesteensen** [comment]
I've been playing with a couple of different approaches to implementing this and there are some tradeoffs.

The most obvious is to replace the `b'\n'` in the file watcher with something like a regex indicating the start of a new message. This is relatively straightforward, but wouldn't be immediately sharable with other sources like TCP, stdin, etc. There are also some complications with things like max line length and max read since when you can't assume that the delimiter is a single byte. The larger issue, however, is that there's not currently a good way from the file watcher to flush the last event on shutdown since we can't necessarily expect to receive the full marker after each line (e.g. if it's `^INFO`).

The other path I went down for a bit was to build a stream adapter that buffers lines and combines those that don't begin with a `message_start_indicator` with the last one that did. This would be relatively easy to reuse across the different sources, but a bit more complex and duplicative with the existing framing logic in each source. The other issue is that you'd need to make sure you pushed it to a layer within the sink where you can't get interleaved events from different sub-sources (e.g. different files or different incoming TCP connections), which is possible for things like TCP but would require significant rework of the file source since we don't use streams at the per-file level there.

In both solutions, there's the issue of buffering data for an unbounded amount of time when you can only flush by seeing an independent subsequent message. This shouldn't be a huge deal in practice, but we'd want to be careful of edge cases. The stream adapter solution could potentially implement some time-based limit on the aggregation, which could be nice.

Overall, I'm leaning towards the first solution since it feels simpler to expand the existing framing logic than add a second layer of it. Either seems like it will require some rework of the file source, so I'm going to start digging into that more.
