### ISSUE TITLE
Write an overview all the metrics landscape of the Kubernetes

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#4021]
There are a number of Kubernetes ways to collect metrics in Kubernetes. They have their own differences, and there's no single definition of "system" metrics or "app" metrics. To pose the problem properly, we need a high-level overview of what's there. This should allow us to observe the possible options and reason about them, thus allowing prioritization of the ones bringing in the most value higher.

**Comment by MOZGIII** [comment]
Preliminary verdict - we should just start with scraping the data from https://github.com/prometheus-operator/kube-prometheus. It provides the stack that covers all of the monitoring needs.

**Comment by binarylogic** [comment]
@MOZGIII if you agree with https://github.com/timberio/vector/pull/4098#issuecomment-699549393, let's close this. Based on your comment above it seems that the `prometheus-operator` might expose a central metrics source upstream from the actual Prometheus database. Even if it does, I think #4162 is likely a better approach since we don't couple Vector with an opinionated operator. As long as they get metrics to Prometheus we can ingest the data, we don't care how they do it.
