### ISSUE TITLE
Wait for sinks to finish on reload

### ISSUE THREAD

**Issue by ktff** [timberio/vector#4031]
Currently during reload we are only waiting for sources to finish, but we should also wait for sinks to finish for two reasons:
* Some sinks hold user defined ports so we need to wait for the sinks to release them.
   * Currently the only sink that does this is `prometheus` sink which will panic, and cause vector to shutdown, if we try to change it without changing the address port.
* If the old and the new sink with the same destination are allowed to run at the same time, their event streams can be intermingled from the point of view of the destination which can cause out of order events.

It's probably the cause of #3727.

**Comment by ktff** [comment]
I see two ways to address this:
* Wait for sink `Task` to finish.
   + Simple and non intrusive to implement.
   - Reload can hang on hanged sink.
   - This can take a while if there are a lot of events in the pipeline.
* Wait for sink `Task` to finish for a limited time, after which we force shutdown it.
   + We can't hang
   - There is no sane wait limit that we can hardcode. And to determine that limit dynamically we would need to know max capacity of the pipeline which can vary greately depending on the size of the buffers, and also throughput of the pipeline would need to be known, and even then we would have large variance to account for. 
   - This can take a while if there are a lot of events in the pipeline.

Neither of them seem like a good option, considering that the reload could end up with a long duration, which isn't the case at the moment, and would be replacing one problem with another. 

---

So it's makes sense to only consider the problem with ports for now, and for the ordering problem to be considered seperately.

The problem with the ports can at least be stopped from shutting down process by refusing to change `prometheus` sink. Just binding the port during build phase in the sink won't help, so that the reload fails then, since we would end up rebuilding the old version of the sink which has the same port, which would again shutdown the process.

--- 

@lukesteensen do you have some idea? Am I overestimating the time to empty the pipeline?

**Comment by lukesteensen** [comment]
I agree that the time to empty the pipeline is essentially unbounded. Even without high throughput, sinks like S3 can intentionally wait a very long time to finish sending data. It makes this a very tough problem.

One approach I've been thinking about is to have some idea of component conflicts that can be detected from the configs during reloading and inform how we do the reload. For example, if a new source has a port conflict with an old sink, we'll know we need to shut down the sink first. It doesn't solve the problem of how to shut down the sink, but it will hopefully limit the problem to cases where we know we need to do something.

I think the best place to start for how to shut down sinks is just to wait. Examples like S3 shouldn't be a problem in practice since they don't actually hold resources that will be needed by anything else. And components that do hold resources tend to be able to shut down more promptly. If we can limit the waiting to cases where we actually have a conflict, hopefully that will reduce cases where waiting is problematic.

**Comment by ktff** [comment]
>  the best place to start for how to shut down sinks is just to wait.

@lukesteensen I agree. Now the question is how are we going to detect conflicts. 

Detecting it from config seams complex, especially with cross dependency, where one type of sink is replaced with different type of sink that has the same port.

An alternative is to use concept of `ShutdownSignalToken`, pass it through `SinkContext` from which any `Sink` that has a resource, like port, can clone it and hold onto it until it has freed that resource. Then in reload code we can wait on those tokens.

**Comment by ktff** [comment]
cc @lukesteensen

**Comment by lukesteensen** [comment]
> Detecting it from config seams complex, especially with cross dependency, where one type of sink is replaced with different type of sink that has the same port.

Yes it could definitely be tricky. One idea was to add a method to sink configs to return any potentially conflicting items (e.g. an enum where variants include ports, paths, etc). Default implementation would be to return nothing.

**Comment by ktff** [comment]
That's a great idea, it solves the problem, it has a minimal effort default, and it has nice extensions that can be added on top.

Let's go with that.
