### ISSUE TITLE
RFC for topology schema

### ISSUE THREAD

**Issue by leebenson** [timberio/vector#4083]
Following #3860, it's a good time to start defining the GraphQL schema around observing topology.

This should include some decisions around:

- Flat vs. graph data
- Considerations around what makes sense for the UI / `vector top` to parse
- Requirements for potentially filtering / sorting data
- Limiting results, and the situations that may requirement
- Mapping sources, transforms and sinks, and the relationships between each

**Comment by binarylogic** [comment]
Thanks, @leebenson. I just want to reiterate that all of this is experimental. If possible, we should do the absolute minimum to solve for `vector top` and make changes as we make more progress on features that use the GraphQL protocol. For your points:

* Whatever works best for `vector top`, we can always change if we need.
* Whatever you think is best for a `vector top` MVP.
* Defer this, we can solve this when we need it.
* Defer this, we can solve this when we need it.
* Defer this, we can solve this when we need it.

There is going to be an initial period where we learn and put in place more requirements. Let's just accept that it's going to be messy. Once we get a little further down the roadmap we can step back and adjust the schema. I want to optimize heavily for speed during this phase though since we are still learning.

Given that, do you think we need an RFC?

**Comment by leebenson** [comment]
It only needs an RFC if others care to chime in. Our GraphQL tooling is conducive to rapid changes. We can change the schema by changing the signature of a single function, so this is easy to move around as we see fit.

If you'd rather I just take this to the finish line and leave discussions for later, I'm certainly happy to do that.

**Comment by binarylogic** [comment]
Yep, and all of the awesome type checking you've added will afford us the privilege to do this.
