### ISSUE TITLE
Expose line_agg as a transform

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#4210]
## Motivation

Currently, we implement multiline aggregation support at the source level.

The rationale for doing it this way, rather than with a transform, is that:
1. We can implement some low-level optimizations, that are not possible with a transform-level implementation.
2. Within the source, we have an additional context about the data streams, and thus we can rely on that and eliminate the need for the user to configure the streams.

However, there's a number of reasons to, nonetheless, implement a transform that would expose the `line_agg`:

1. We don't have all the sources covered yet, and for such sources users currently simply lack the functionality. Generally, users would appreciate a manually configurable and less optimized solution more than nothing.
2. In some cases, you need to apply advanced logic for the multiline aggregation. For instance, consider a Kubernetes cluster, that runs Java and Ruby apps. We collect logs from it via a single `kubernetes_logs` source, but want to configure the multiline aggregation differently for each kind of stacktrace. This could be solved by splitting the logs at a swimlane (based on a pod label value `java`/`ruby`) and applying a multiline aggregation transform with the relevant settings atop of each swimlane arms.

## Proposal

Take the `line_agg`, wrap it with a transform in a simple way using the `EventDiscriminant` as key, and also using some of the machinery originally implemented for the `merge` transform. Users will have to manually specify the `stream_discriminant` field (typically this would be `file`, or `container_id`, or something similar).

## Alternatives

Improve the `reduce` transform to be capable of delivering the same functionality as the `line_agg`. It's currently like `line_agg` in a `halt_with` mode, but has a lot more fine-tuning to configure what to do with the fields of the events.

**Comment by binarylogic** [comment]
We've had this discussion before, so I'd like to record our response for posterity.

The reasons we want to merge lines within the source are:

1. We must merge data within it's originating stream. For example, in the `file` source, we must merge data coming from the same file. By providing these options at the source level we can handle this for the user and it "just works". If we provide this as a transform, the user would be required to provide fields that identify each stream correctly. This is not only error-prone, but it's complicated to implement since the transform now has to hold state.
2. Doing this within the source means we can avoid creating events in certain sources, making it simpler and faster.

Is it exceptionally difficult to implement this within each source? I know it's not entirely cookie cutter, but it would deliver a much better UX.

cc @lukesteensen in case I missed something.

**Comment by lukesteensen** [comment]
My recommendation is to improve the `reduce` transform. It seems like there is very little needed to bring it up to the same level of functionality as `line_agg` (namely joining strings with newlines instead of simple concatenation), and it has the benefit of being much more flexible.

**Comment by MOZGIII** [comment]
Yep, closing in favor of https://github.com/timberio/vector/issues/4258
