### ISSUE TITLE
Local variables in the Remap language

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4419]
Ability to set values to local variables.

## Example

```
url_parts = parse_url("http://vector.dev/path")
.host = url_parts.host
```

Would produce:

```json
{
  "host": "vector.dev"
}
```

**Comment by JeanMertz** [comment]
I'm definitely a fan of this. I've been thinking about this before.

**scoping**

I would propose we _don't_ introduce scoping into the language.

That is to say, this works:

```js
if .foo == "bar" {
	foobar = "foobar"
}

.foobar = foobar
```

**undefined variables**

If we don't introduce scoping, we should also allow using undefined variables (and treating them as `null`). There is a downside to this, however, which is that this example wouldn't return an error:

```rust
.foobar = "foobar"
.foo = foobar // null, meant to reference `.foobar`
```

**syntax**

Which brings me to the syntax used for variables.

The above two examples expose two problems with the currently proposed syntax:

1. defining a variable vs updating an event field is one typo away

    ```rust
	.foo = "bar" // { "foo": "bar" }
	foo = "bar"  // {}
	```

2. referencing a variable vs an event field is one typo away

    ```rust
	.bar = "bar"
	.foo = .bar // { "foo": "bar" }
	.foo = bar  // { "foo": null }
	```

To solve this, I think it makes sense to add a special variable prefix, both for assignments and referencing. This would fit nicely with the existing dot (`.`) prefix to assign and reference fields, and prevents accidental typo's (assuming the prefix we choose is far enough away from the dot on most keyboard layouts).

I would probably propose the dollar `$` prefix. While I'm not the biggest fan this one, it does solve the typo issue (`.` and `$` are far enough away on most (all?) keyboard layouts that a typo is unlikely), and it follows a precedence set by other languages, including the very relevant [`jq` language](https://stedolan.github.io/jq/manual).

So tying it all together, you'd get:

```rust
.foo = "foo"

if .foo != $foo {
	$bar = "bar"
}

.foobar = .foo + $bar
```

**operators**

An alternative that doesn't introduce syntax changes, is to add `get` and `set` operators, which would allow you to do:

```rust
set("url_parts", parse_url("http://vector.dev/path"))
.host = get("url_parts", default = ...)
```

It has a couple of advantages:

* It doesn't require syntax changes
* It allows dynamically referring to variable names (e.g. `get(.foo + "bar")` where `.foo` resolves to a string)
* It allows setting a default value if a variable is missing

But it also has downsides:

* It's less ergonomic (more verbose) compared to dedicated syntax
* It makes it more difficult (but not impossible) to have nice variable-related error messages
* It's less clear that this can't be used to get/set fields, unless we make the operator names longer (e.g. `get_var`), making it even less ergonomic

It doesn't have to be either/or, we can start with the operators and add dedicated syntax later, or vice versa, but I'm also not convinced that dynamic variable name referencing is something people want (they probably want dynamic field referencing first), so I'd start with dedicated syntax, simply because it's way more ergonomic.

**Comment by binarylogic** [comment]
> I would propose we don't introduce scoping into the language (or; there's one scope — the global scope).

Brings me back to the good ol' Ruby 1.X days.

I tend to agree because I don't see any advantage of supporting scopes. This should be a simple and safe language, and scopes promote these principles for the mapping use case.

> If we don't introduce scoping, we should also allow using undefined variables (and treating them as null)

What happens if a user specifies a non-existent field? We should be consistent with how we treat that. Ex:

```
.key = .non_existent_field
```

> I would probably propose the dollar $ prefix.

I tend to agree, but I don't think it'll be the user's natural inclination which is why I dislike it. The onramp for this language should be smooth like butter and the `$` feels like an insider's trick. So my vote would be to start without it.

**Comment by JeanMertz** [comment]
> So my vote would be to start without it.

Whatever we pick is fine by me, we can always iterate on it, but I do believe that having a prefix avoids more confusion than the prefix introduces (especially since languages such as `jq` also have a prefix, and I'm fairly certain it's for the same reason).

> What happens if a user specifies a non-existent field?

Referencing a non-existent field results in an error (unless a function swallows that error, e.g. `to_string(.nope, default = "yes")`).

I'm okay starting with error'ing on undefined variables, it does have the advantage of catching typo's in variables names. I think both situations come with trade-offs, and it's a matter of finding which causes the least amount of friction.

**Comment by binarylogic** [comment]
Ah, didn't realize `jq` went with the `$` prefix. Then I'm fine either way, your pick.
