### ISSUE TITLE
Drop the automatic `kubernetes_logs` source in the Kubernetes integration

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4459]
As I write the Kubernetes installation docs, I find the automatic `kubernetes_logs` source to be non-obvious and restrictive. I'd like to propose we remove it, but I feel like I might be missing the bigger picture here, so I want to verify this is the right move.

### For removing

1. Installing Vector will require configuration of some sort; there is no "configuration free" path. Therefore, it is more intuitive to configure the entire pipeline, including the source.
2. How will users customize the `kubernetes_logs` source? Such as filtering which logs are collected. How they configure the `kubernetes_logs` source should not deviate from how they configure other components in their pipeline.
3. Vector aims to collect metrics and traces in addition to logs. Therefore, users might not want to collect logs.

### For not removing

1. We can freely change and maintain the source without breaking backward compatibility for users.
2. Point 1 above might not be accurate if we want to deploy a Vector topology. For example, deploying Vector as both an agent and aggregator. The agent configuration could automatically use the `kubernetes_logs` -> `vector` sink. But I'm not sure this is accurate because this sounds like it would be better handled by operators (#3923). I'm sure we'll handle configuration differently when we approach those.

## Conclusion

Given the above, I propose that we remove it and let the user explictly configure the `kubernetes_source`. We can just as easily include it as part of the installation docs.

**Comment by MOZGIII** [comment]
> 1. Installing Vector will require configuration of some sort; there is no "configuration free" path. Therefore, it is more intuitive to configure the entire pipeline, including the source.

True.
In general, this is right - vector has to have some user-provided configuration -  but we can provide some built-in defaults to reduce the footprint of the user-provided configuration. In essence, Helm's main purpose as a project is exactly this.

> 2\. How will users customize the `kubernetes_logs` source? Such as filtering which logs are collected. How they configure the `kubernetes_logs` source should not deviate from how they configure other components in their pipeline.

This is done via `kubernetesLogsSource.rawConfig`, very similar to how rest of the sources are configured. The approach has the same issues with mixing YAML/TOML, those are discussed at https://github.com/timberio/vector/issues/4463. Other than that it's very similar.

> 3\. Vector aims to collect metrics and traces in addition to logs. Therefore, users might not want to collect logs.

This can be oped out via `kubernetesLogsSource.enabled: false`.




> 1. We can freely change and maintain the source without breaking backward compatibility for users.

This is true, but only to a certain degree. A very good thing to have nonetheless, especially early on.

Especially, given that users can opt-out from using the built-in source, and configure their own custom source.

> 2\. Point 1 above might not be accurate if we want to deploy a Vector topology. For example, deploying Vector as both an agent and aggregator. The agent configuration could automatically use the `kubernetes_logs` -> `vector` sink. But I'm not sure this is accurate because this sounds like it would be better handled by operators (#3923). I'm sure we'll handle configuration differently when we approach those.

I'm revisiting this already for the #3227.


> Given the above, I propose that we remove it and let the user explictly configure the `kubernetes_source`. We can just as easily include it as part of the installation docs.

I'd like to gather some feedback on this first. I've had some mixed feelings about a built-in source like this first this myself, but then it turned out very practical.

I propose that we leave it in for this first release and gather some more feedback from the users. It might be that we want to revisit the whole approach of passing vector configuration in a bit, and we'll be able to get all the benefits of this special-cased source.

There's also a practical concern of mine here - I currently have some branches that introduce other changes to the configuration (#4257, #4404), and I'd like to avoid introducing more changes to the `master` branch until the 0.11 release to constrain the complexity of maintaining that code. It's not a big deal, but a bit less overhead this way.

To be honest, this is something I wanted to experiment a bit with before we start with an operator - there might a less demanding solution at hand that's easy to land in-between the full CRD-powered configs support and manual configuration file wiring. So, I kind of have high hopes for the user feedback on this small experiment.

---

On a separate note, we want to set the expectations of our users straight, that the next *couple* (maybe more) of releases will be introducing significant backward-incompatible changes to the Helm chart configuration, so the upgrade path will likely require moving values around.

**Comment by binarylogic** [comment]
Ok, let's leave it then.

> On a separate note, we want to set the expectations of our users straight, that the next couple (maybe more) of releases will be introducing significant backward-incompatible changes to the Helm chart configuration, so the upgrade path will likely require moving values around.

I really want to avoid this if we can. We're about to officially release our Kubernetes integration, is there anything we can do now to avoid that?

**Comment by MOZGIII** [comment]
> I really want to avoid this if we can. We're about to officially release our Kubernetes integration, is there anything we can do now to avoid that?

Currently, we already have some backlog of the changes to the configuration that are planned for after 0.11. I don't see a reasonable way to make the transition between 0.11 and 0.12 (or whatever the release we'll be rolling those out will be), other than stalling the release to include those changes now.

Implementing some kind of backward-compat layer will be way too much overhead for maintenance and will probably constrain further progress, it'll also take time to implement, so we might just as well focus on implementing the features instead, and just stall the releases. I don't want that though, in my opinion, the current plan for releases/changes is reasonable, and I think our users will understand the value of both shipping what we have for them now without delay and, in the next release, new features that necessitate changes to the configuration.

These are just my concerns for the compat for the closest releases (0.11-0.12), but it seems like we *might* want to deliver similar level changes in the 0.12-0.13 and, probably, one release after.

Of course, even though we're pre-0.1, I'm doing my best effort to preserve compat where possible, cause I know it matters. But I also expect some turbulence early on, and the best thing to do now, I'd say, is to notify our users in advance that some changes are to be expected.
