### ISSUE TITLE
Ensure that regexes in the Remap language are pre-compiled

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#4503]
See https://github.com/timberio/vector/issues/4473#issuecomment-706267627

**Comment by binarylogic** [comment]
@JeanMertz @FungusHumungus can you chime in here? I'm a little concerned that we aren't precompiling regex patterns which would be very bad for performance. The Remap Language should be safe and performant, we shouldn't open the door to slow performance with this language if we have th choice.

**Comment by FungusHumungus** [comment]
It is very worth checking over this to make sure I have done it correctly. I have been working on regexes as a part of #4290.

I think the pertinent parts are in the [`DynamicRegex`](https://github.com/timberio/vector/blob/052945fcf0fd693f25116db0dddfb9d41fd7cb89/src/mapping/query/dynamic_regex.rs#L30
) struct (the name may not be the best one).

Once parsed it is compiled here:

https://github.com/timberio/vector/blob/052945fcf0fd693f25116db0dddfb9d41fd7cb89/src/mapping/parser/mod.rs#L339-L341

This is compiled just at load time.

The plan was to make it so that users could go on and dynamically build up a regex, say by using a value of another field in the event as the regex pattern. These regexes would potentially need to be compiled every time. However, if you are sure that this is never going to be necessary, then we don't need to make this possible and can ensure that all regexes are compiled at parse time.

**Comment by lukesteensen** [comment]
> The plan was to make it so that users could go on and dynamically build up a regex, say by using a value of another field in the event as the regex pattern. These regexes would potentially need to be compiled every time. However, if you are sure that this is never going to be necessary, then we don't need to make this possible and can ensure that all regexes are compiled at parse time.

I would not add this feature unless it seems like users really want it. Better not to open that particular avenue for confusing runtime errors if we can avoid it.

**Comment by JeanMertz** [comment]
Regex support has been added to Remap. Regexes are compiled when Vector starts. They can only be provided as function arguments for the functions that accept them, there are no other ways to use regexes in the language right now (e.g. you can't assign them to variables or return them as values).
