### ISSUE TITLE
`sampler` transform does not really sample according to the `rate`

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#4682]
This is at `vector` `0.10.0`.

When using `sampler` transform, I found out that setting `rate` to `10` reduces the amount of data way beyond 1/10th, and setting it to `9` results in an immediate spike of the amount of data (not adequate for 10->9 transition). I don't have exact proportions, but it's definitely broken.

**Comment by Hoverbear** [comment]
@jamtur01 this might be worth slipping into 0.11?

**Comment by jamtur01** [comment]
@Hoverbear Agreed. @ktff I am going to throw into your next sprint.

**Comment by lukesteensen** [comment]
@MOZGIII were you testing this with synthetic data?

The way the sampler works is that it hashes the message field instead of just generating a random number. This makes the sampling "consistent" so that (in theory) a user could specify a field like `request_id` and get a consistent sampling decision for every log line with a given value of that field. But that also means it's not precise if event contents are not random.

We should at the very least document this, but we should also make it more useful by letting the user configure which field to hash. In the absence of that config, we could also rethink the current default of the message field.

**Comment by MOZGIII** [comment]
@lukesteensen I tested with `flog --format json`, so the output should be rather typical.

I checked the code and noticed this hashing mechanism, however, I have high doubts that this hashing will produce a uniform distribution when we do `% rate == 0` over it. That's pretty much the pinnacle of the issue. I guess we could just switch to the counter and `% rate == 0` that as a condition.

**Comment by ktff** [comment]
For `seahash` it is claimed that 
> The hash value of a sequence of uniformly distributed bytes is itself uniformly distributed.

so 
> But that also means it's not precise if event contents are not random.

is the main issue, but the user should take care of it. 

> we should also make it more useful by letting the user configure which field to hash

We introduced that option. 

Although counter would provide more uniformity and less pitfalls, having 
> sampling "consistent" 

seams useful for the example @lukesteensen provided. 

----

Considering all that, we can:
* Add option to choose between rating by hash or count.
* Document behavior and use cases for both option.

**Comment by MOZGIII** [comment]
The proposed solution sounds good! I'd also use `count` by default to allow zero-configuration.

**Comment by MOZGIII** [comment]
https://en.m.wikipedia.org/wiki/Benford%27s_law - this might be relevant
