### ISSUE TITLE
Add vector user-agent header to _all_ outgoing HTTP requests

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#501]
All outgoing HTTP requests should include a `User-Agent` header:

```
User-Agent: Vector/#{vector_version}
```

This should _only_ be added if there is not already a `User-Agent` header set. For example, a user could set a custom `User-Agent` header as part of their sink configuration.

**Comment by binarylogic** [comment]
@LucioFranco while you're working on the HTTP sinks I'm curious if you could do this as well? It's important from a sale/marketing standpoint. Services reporting on user-agent activity and it would be nice to have Vector show up in that data.

**Comment by LucioFranco** [comment]
@binarylogic I think the fix for this is orthogonal to the work going into the http sinks. This is more related https://github.com/timberio/vector/issues/1370 and making all our rusoto sinks use the same http client instead of the default http client.

For the http, splunk, es and non aws sinks this should be easy. Its just our aws sinks will need some more work.

**Comment by binarylogic** [comment]
Cool, then I think it's worth addressing #1370 as part of our tech debt project. Please let @lukesteensen know.

**Comment by lukesteensen** [comment]
Do we think this is valuable for the AWS sinks? My assumption is that it would be most valuable for the other HTTP-based services.

**Comment by binarylogic** [comment]
Yep. They monitor user-agents.
