### ISSUE TITLE
Document built-in metrics pipeline that we ship with the Helm charts

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#5043]
Each if the Helm charts provide an `internal_metrics` source and `prometheus` sink out of the box (#3799). Agents also expose `host_metrics` (#4163) via the same `prometheus` sink.

Charts come with options to enable Prometheus integration via `annotations` or Prometheus Operator integration via `PodMonitor`. 
We need to document this, and make it clear on how to enable these integrations, and what's the difference.

We also need to explain that the `node_exporter` is not required when the `host_metrics` is enabled.

**Comment by jamtur01** [comment]
@MOZGIII @eeyun What's the status of this?

**Comment by eeyun** [comment]
I don't believe this has been done. I'm in the cue docs for another documentation thing right now so I'll try to get this in as well.

**Comment by eeyun** [comment]
Actually @jamtur01 looking at this closer I'm not sure what the documentation strategy should be - do we want this content rendered on the web-site or documented alongside our readme/etc?

**Comment by jamtur01** [comment]
I think rendered on the website.

**Comment by binarylogic** [comment]
@eeyun you should be able to expand on the data [here](https://github.com/timberio/vector/blob/3a9f7e6ceebff6c06f95d17bf93b3636df0f8351/docs/reference/installation/platforms/kubernetes.cue#L12). Right now it inherits from the `kubernetes_logs` source since that is the only source installed, but you'll probably need to document metrics separate since that is not related to `kubernetes_logs`.
