### ISSUE TITLE
Ability to selectively enable Kubernetes metadata enrichment

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5047]
A piece of feedback we received was the ability to granularly control which Kubernetes metadata is included in logs. I see two ways to go about this:

1. Configuration options on the `kubernetes_logs` source.
2. Assuming there is no performance difference, users could remove the field via the `remap` transform.

cc @MOZGIII

**Comment by MOZGIII** [comment]
What's their use case? If they want to remove the field not because of some perf issues, but just to have tighter control - I suggest they remove the fields via the `remap` transform, as the performance implication of just adding and removing a field is negligible.

It's a different story if they have a field that's too large and causes issues - we have carefully designed the system to avoid such issues out of the box, but it may be that something was not accounted for.

**Comment by jmealo** [comment]
We're having major issues with Kubernete API server request volume on our Azure AKS clusters. Metadata enrichment fails so often that we only rely on the filename to determine pod/namespace and don't need the enrichment for anything (since we cannot rely on it). It would be helpful not only to be able to turn it off, but, to provide a metric on the volume of outgoing requests for metadata enrichment, latency/failures.

**Comment by pront** [comment]
> We're having major issues with Kubernete API server request volume on our Azure AKS clusters. Metadata enrichment fails so often that we only rely on the filename to determine pod/namespace and don't need the enrichment for anything (since we cannot rely on it). It would be helpful not only to be able to turn it off, but, to provide a metric on the volume of outgoing requests for metadata enrichment, latency/failures.

This issue was closed 5y ago. if you want to request a feature, please consider opening a new one. Please keep it as minimal as possible, e.g. in this case we probably would want two different tickets, one for disabling enrichment and one for adding new telemetry.
