### ISSUE TITLE
The `aws_s3` sink `key_prefix` default should end with a `/`

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#517]
The `key_prefix` default is `date=%F`, but it should be `date=%F/`

**Comment by a-rodin** [comment]
It looks like in fact the trailing slash is not needed for version 0.3.0. When it is there, it creates an additional empty "folder", that can be seen in S3 console. Maybe the documentation should be updated correspondingly.

**Comment by binarylogic** [comment]
Interesting, it definitely should be required since this would allow users to not use folders if they do not want to. @LucioFranco are we adding a `/` as part of the file name?

**Comment by binarylogic** [comment]
@LucioFranco is this still an issue?

**Comment by LucioFranco** [comment]
@binarylogic Yes, I believe the top issue was originally fixed but there was an issue where if you added the `/` to the key_prefix at the end it would cause a generated key like so `key_prefix//file.log`. This was fixed by formatting the key _without_ the `/` https://github.com/timberio/vector/pull/596/files#diff-362150fe34a45de2c4c727bbb0fb7539R339

So that said, I think this can be closed.
