### ISSUE TITLE
Add values.schema.json to our Helm charts

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#5253]
Helm now supports `values.schema.json` to aid users by validating their custom `values.yaml` files against the chart-provided schema.

See https://helm.sh/docs/topics/charts/

We don't currently ship schemas for our `values.yaml` files, but we need to start doing that.

Once it's done, we should be able to generate advanced documentation on our website, which is tracked by https://github.com/timberio/vector/issues/5036.

**Comment by binarylogic** [comment]
This issue is blocked by the lack of JSON schema support in cue. If we want our CUE data to be the source of truth, we'll need to translate that data to a `values.json` and `values.json.schema` file. Currently, that is not very straightforward given CUE's lack of support for exporting to these formats, making this issue's cost outweigh the value.

Additionally, command line tools for achieving this require heavy runtimes (javascript and python) that we do not want to introduce into our runtime.

**Comment by spencergilbert** [comment]
https://github.com/cuelang/cue/issues/929 <- cue issue for exporting support

**Comment by spencergilbert** [comment]
Issue moved to [timberio/helm-charts #12](https://github.com/timberio/helm-charts/issues/12) via [**ZenHub**](https://www.zenhub.com/)
