### ISSUE TITLE
Qualify failable Remap functions with ! suffix

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5474]
After reading https://github.com/timberio/vector/pull/5469 it made me think about qualifying failable Remap functions with a `!` suffix. This would make it obvious when a function should be wrapped in `ok` in contexts where a failure should be handled.

For example, instead of `parse_json`, the function should be `parse_json!`.

cc @JeanMertz and @FungusHumungus for input.

**Comment by FungusHumungus** [comment]
I think it is a very good idea. It also allows us to have two versions of functions that handles errors in different ways. `parse_json` without `!` could return a `Null`, for example.

My only slight concern is that Scheme uses functions ending with a `!` to indicate that the function has a side effect. Changing the meaning could potentially confuse some people. It's probably not that much of an issue, but might be worth bearing in mind.

**Comment by JeanMertz** [comment]
> I think it is a very good idea. It also allows us to have two versions of functions that handles errors in different ways. `parse_json` without `!` could return a `Null`, for example.

That's basically (partially) what I proposed in #4840, but I would caution against that, especially if we also go with #5469.

> After reading #5469 it made me think about qualifying failable Remap functions with a ! suffix. This would make it obvious when a function should be wrapped in ok in contexts where a failure should be handled.

There is an alternative here, and that's to use the type system. We already know if an expression is fallible or not. What we could do is check the root expressions and see if any of them are fallible, if so, we can either report a warning, or an error at boot-time.

The inverse is also possible: we check if one of the `ok`, `err` or `ok_or` functions wrap an infallible expression, in which case there's no need to use one of these functions, which we can again either warn against at boot-time, or refuse to boot at all.

On one level, it might be bordering on being pedantic if someone doesn't care if their script errors (maybe because they know exactly what their events will look like), but on the other hand it strongly plays into the "safety guarantees" we want to provide with TRL.

Another added benefit is that we avoid cluttering our syntax with `!`'s all over the place.

I'd personally vote for the type-system level approach as opposed to changing the function identifiers, but I get that this is a quick change and might be less "invasive" (although, again, I think warning people about potential failures is the good kind of invasiveness)

**Comment by binarylogic** [comment]
> parse_json without ! could return a Null, for example.

True, although, I don't think the non-`!` variant is necessary with the new error handling functions. I think it's clear to _just_ have a `parse_json!` function.

> I'd personally vote for the type-system level approach as opposed to changing the function identifiers

Why not both? I agree that the type system check would be nice, but the `!` makes it obvious I need to handle errors as I'm _writing_ the script.

There is a larger discussion to be had if we want to force users to handle all errors, making it impossible for remap scripts to fail, which is sounding really attractive.

**Comment by JeanMertz** [comment]
> Why not both?

I'd say if we have the type-system and documentation to guide a user, then I'm not really sure what the `!` adds. I get where you're coming from though, I just worry that it makes _reading_ scripts more annoying, and you usually only write a script once, but it's read many more times.

If we have a type-system check (and we enforce it), then the reader already knows the function can fail because it's wrapped in an `ok` (or similar) function and the writer knows by either checking the documentation, or fixing the compiler error messages as the script is written/tested.

But yes, doing both is definitely possible, I'm just sad we'll have `!`'s all over the place 😄 

> There is a larger discussion to be had if we want to force users to handle all errors, making it impossible for remap scripts to fail, which is sounding really attractive.

Agreed. As I said, it can become a bit pedantic, but I'm definitely a fan of the safety it provides (also, it would work really well with a future addition to Vector to support schema's and event metadata to build up type information as the event flows through Vector, since more type information means less runtime checks (and thus potentially runtime errors)).

**Comment by binarylogic** [comment]
Closing in favor of #5479. And since the majority of functions can fail I can see why we don't want to include `!`. I still prefer it, since it makes it clear when to handle errors, but other languages haven't done this and it hasn't been a glaring oversight, so let's punt.
