### ISSUE TITLE
Kafka batch configuration error

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5602]
Reported from a user:

```
buffer.max_bytes = 100000
```

Produces:

```
{"timestamp":"Dec 18 15:21:04.264","level":"ERROR","message":"Configuration error.","error":"Sink \"common-kafka\": creating kafka producer failed: Client config error: No such configuration property: \"batch.size\" batch.size 100000","target":"vector::topology"}
```

Looks like vector translates its own parameter to the librdkafka one but it fails for some reason.

**Comment by Hoverbear** [comment]
So, this property is listed in https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md, and I did test this with our integration test kafka instance. I wonder if they're using an old kafka server which doesn't support it?

**Comment by jamtur01** [comment]
@binarylogic Can we confirm versions with the user?

@Hoverbear We shouldn't probably warn rather than fail on unknown properties?

**Comment by Hoverbear** [comment]
Agreed!

**Comment by Hoverbear** [comment]
I managed to replicate this!

**Comment by Hoverbear** [comment]
I suspect this is resolving from this line creating a consumer instead of a producer in the healthcheck:

https://github.com/timberio/vector/blob/3a48a0a47dd1e1b59113041a96cdced29937cc19/src/sinks/kafka.rs#L351

This is evidenced by 
![image](https://user-images.githubusercontent.com/130903/102808418-253e3300-4375-11eb-8b45-8174081dcdf7.png)

Since we did not check the healthcheck in tests, I'll add a healthcheck to tests and resolve this.

**Comment by Hoverbear** [comment]
So this **particular** setting is related to https://github.com/timberio/vector/issues/3372.

**Comment by Hoverbear** [comment]
In #5652 this gets unblocked by the change that allows for `Producer`/`Consumer` specific settings. But the problem of #3372 remains and would need to be solved to address this.
