### ISSUE TITLE
Document function fallibility in VRL

### ISSUE THREAD

**Issue by lucperkins** [timberio/vector#5611]
Function fallibility is an extremely important topic in VRL and cuts to the heart of its usability. We need to:

- [ ] Give an in-depth description of fallibility in the core VRL docs
- [ ] Update the VRL function CUE schema to enable us to indicate which functions are fallible and under which conditions they error
- [ ] Update each function's docs

**Comment by binarylogic** [comment]
> Update the VRL function CUE schema to enable us to indicate which functions are fallible and under which conditions they error

I'd prefer that we achieve this by listing the possible errors as opposed to a simple `failable` boolean.

**Comment by lucperkins** [comment]
That's a little bit tricky because I believe @JeanMertz has opted to make errors simple strings instead of an enum with discrete error types. So from what I gather the error "story" for VRL is that functions are either fallible or infallible and, if fallible, the error needs to be caught, lest you get a clear and to-the-point compile-time error message. So it's not clear that error types can or should be explicitly documented. Jean, please correct me if any of that is wrong.

**Comment by JeanMertz** [comment]
That's correct @lucperkins. Internally we use enums with discrete error types, but they are converted to regular strings once the error is surfaced in VRL itself.

I didn't see a need for typed errors, as it would only add more complexity to the language for little gain (because we want to keep the language simple, so having to enumerate over multiple error types should rarely be needed, and for the very few cases where it is, one can match against the error string itself).

**Comment by jamtur01** [comment]
Done.
