### ISSUE TITLE
Vector has 6 definitions of the `map!` macro

### ISSUE THREAD

**Issue by FungusHumungus** [timberio/vector#5695]
```
src/test_util/mod.rs
533:macro_rules! map {

src/sources/prometheus/parser.rs
168:    macro_rules! map {

lib/prometheus-parser/src/line.rs
383:    macro_rules! map {

lib/remap-lang/src/test_util.rs
73:macro_rules! map {

lib/remap-functions/src/util.rs
48:macro_rules! map {

src/sources/apache_metrics/parser.rs
456:    macro_rules! map {
```

I would suggest this is excessive and should be tidied up. Most of the definitions are a shortcut to creating a BTreeMap. We could get rid of all the other definitions of this and move the main definition into `shared`.

The definition in `lib/remap-lang/src/test_util.rs` creates a Remap expression that returns an `expression::Map`. We should get rid of this one completely. I have seen a number of times now where this version of the macro should be used, but due to code reorganisation the other version is pulled in - leading to considerable confusion.

For remap we now have the `value!` macro which can work for all Remap value types, not just maps. Remap should use this macro instead.

Instead of:

```
map! [ "key": "value" ]
```

we can write:

```
value!({"key": "value"})
```

which does the same thing.

**Comment by fanatid** [comment]
Related with https://github.com/timberio/vector/issues/4651

**Comment by JeanMertz** [comment]
At least in remap, there's a difference (I'm not sure if I merged the relevant PR yet though).

Here's the use-cases in remap:

* `map!` creates a _map expression_, which is different from `Value::Map` (there's also an `array!` to create an array expression)
* `value!` crates a `remap::Value`, and `value!({ foo: "bar" })` creates a `Value::Map`
* and finally, in some cases, you want to create a `BTreeMap` (since they are so pervasive in Vector), which is why another impl of `map` (maybe should rename this to `tmap` to make it more explicit) does the same as before, except that it creates a `BTreeMap`.

Also, I should note that _some_ duplication is intentional: we don't want the `remap-lang` crate to depend on `vector` or `shared`, and so it copies the map implementation.

Still, the point stands, and there's some clean-up we can do, it just won't be "let's only define this once", type of cleanup.

**Comment by FungusHumungus** [comment]
> At least in remap, there's a difference

This is the main problem, because quite often during a refactor the other version of `map!` gets pulled in and the compiler errors start complaining about `remap::Expression` etc.. which doesn't give any clue that it's just the wrong version of the macro.

I would argue that if the macro does a different thing then it should also be named something different to avoid the confusion.

**Comment by JeanMertz** [comment]
> I would argue that if the macro does a different thing then it should also be named something different to avoid the confusion.

Agreed. I'd propose `bmap` for the `BTreeMap` variant (but whatever name works, as long as they differ)
