### ISSUE TITLE
Counter metrics are not being reported to InfluxDB

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5698]
From our community chat:

> counter metrics are not reported anymore into InfluxDB ?

We should investigate if this is an actual error and fix if so.

**Comment by bruceg** [comment]
I wrote a reproduction script and bisected this down to: 95f767d02f92cb6e320b8dc51371dd02959f9499: chore: use PartitionBatchSink in BatchSink (#5076)

I am looking at that to see why it might have broken counter metrics. CC @fanatid

**Comment by bruceg** [comment]
Note that reverting 95f767d02f92cb6e320b8dc51371dd02959f9499 on top of the master branch resolves the problem.

**Comment by bruceg** [comment]
This appears to be closely related to #5589. With 95f767d reverted, the `internal_metrics` (and possibly other metrics sources) ends up sending its metrics through the metrics batch buffer *twice* before the batch is flushed to the sink. This allows the counter handling in the metrics batch buffer to generate the required incremental record in the batch, which then persists after the batch is reset. Without it, the metrics are sent once, no record is added to the batch, and it is never added later.

This is why the self tests for influxdb don't directly catch this, as they do not pass the test records through a batch buffer. I am uncertain the best way to make a test directly for this outside of ensuring the metrics batch buffer does its thing right.

I think the short-term fix to this one is going to be to revert 95f767d, since nothing appears to actually depend on it, and then reintroduce it once the metrics batch buffer issues are resolved. However, it looks like the current batch sink behavior is the *correct* behavior, so reverting it will reintroduce a (admittedly insignificant) defect.

**Comment by jamtur01** [comment]
+1 - Let's revert and open a new issue to address the defect.
