### ISSUE TITLE
New `parse_query_string` Remap function

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5772]
Parses a URL encoded query string.

## Example

```json
{
	"query": "foo=1&bar=2"
}
```

And remap:

```js
.parsed = parse_query_string(.query)
```

Would result in:

```json
{
	"query": "foo=1&bar=2",
	"parsed": {
		"foo": "1",
		"bar": "2"
	}
}
```

**Comment by jszwedko** [comment]
@binarylogic I think this example is not quite right. It should be:

```json
{
	"query": "foo=1&bar=2"
}
```

And remap:

```js
.parsed = parse_query_string(.query)
```

Would result in:

```json
{
		"foo": "1",
		"bar": "2"
}
```

Rather than manipulating `.` as your example has. I think that sort of implementation would not fit with the other `parse_*` functions we have.

**Comment by JeanMertz** [comment]
> @binarylogic I think this example is not quite right. It should be:

I think you both mean the same thing.

@binarylogic's example would be what happens if you use VRL inside the remap transform, and then use a sink to expose the manipulated event.

@jszwedko your example is what happens if you run that program in VRL's REPL (for example), in that the assignment expression would assign the object with keys `foo` and `bar` to the root object key `parsed`, and _then_ return the value that was assigned to the key, which is – as you point out – the object with fields `foo` and `bar`..

So all this is to say, I think we're on the same page here.

**Comment by jszwedko** [comment]
Aha, yes, thank @JeanMertz . I misread the original example. I think we are on the same page here 😄
