### ISSUE TITLE
Potential very slow memory growth due to old Tokio version

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5839]
We have identified a [very slow memory growth](https://users.rust-lang.org/t/slow-memory-creep-in-long-running-tokio-process/44115) (~1mb per day) due to a memory leak that potentially could be caused by an older Tokio version (0.2). We are working to upgrade Tokio versions to resolve this.

Relevant issues #5774, #5777, #5776, #5175

**Comment by jszwedko** [comment]
@blt noting that this might be the same as the other slow memory growth issue. We have finished the tokio upgrade. I don't see another issue for the slow growth, but I know you are looking at it so I'll assign this one to you.

**Comment by blt** [comment]
Oh cool, thank you @jszwedko. I do have a massif run going now that I'll stop near EoD. So far for the workloads I've tested there's a few kb per day of what I _suspect_ is fragmentation growth (we'd need a cooperating allocator to be sure).

**Comment by blt** [comment]
I feel more confident now that what we're looking at in vector, at least in the workloads I tested, is fragmentation. The growth is very small but present and not addressable except in long-term efforts, per #6831. I will close this out since there's nothing to do other than what we're doing already.
