### ISSUE TITLE
Identify encoding/decoding format for Vector to Vector communication

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#5843]
This is an issue that keeps popping up (#5809, #5124, #5341). It's important enough that we solve this separately since it'll be carried throughout all of Vector's sources and sinks.

## The problem

How do we transmit data from one Vector instance to another while being mindful of the public contract we create? For example, sending metrics data from one Vector instance to another should preserve all metric data upon ingestion in the downstream Vector instance, but we don't want to expose a proprietary format over public mediums that could be used for consumption with custom consumers.

## Precedence

We currently have precedence for this in the `vector` source and sink, which uses our Protobuf definitions as a way to encode and decode data. For the `vector` source and sink this is a fine first step since these components are explicitly designed to work together (they are not designed for public consumption). Things get more complicated when we start considering open mediums like HTTP or Kafka since we do not want to create a public contract with our internal Protobuf definitions. There are a couple of reasons for this:

1. We'd like to avoid introducing yet another observability format into the world.
2. We will have to maintain backward compatibility.

This is not to say that we cannot use our Protobufs, but we should consider an open format before doing so, as well as ways to enforce a user-friendly public contract with these Protobufs.

## Open questions

1. Is there an open format that would not lose information? In other words, encoding and decoding Vector logs and metrics events in these formats should recreate the Vector event exactly as it was before.
2. Will metadata need to be preserved?
3. Are some formats better for streaming or batching?
4. Should we consider using our Protobufs if the format is clearly documented for Vector to Vector communication?

**Comment by eeyun** [comment]
CC-ing @lukesteensen here for discussion as well since I think he probably has opinions on this too!

**Comment by eeyun** [comment]
Adding a few high level thoughts here real quick.
In my experience it's always a little bit difficult to compare (even with benchmarking) encoding/decoding libraries due to the diversity of features offered.  I've always had vague guiding principle (that can easily be ignored) with these that aligns things around how the message is used and consumed which puts things into two buckets for me:

1. Messages that might mutate at runtime or schemas that change frequently.
E.G. if theres no schema for the message or if your data types aren't fully compiled into your application or if youre changing your schema frequently then JSON, BSON, MessagePack, CBOR all kind of make sense.

2. Messages with fixed schemas that won't be mutated at runtime or where you compile all your message data types into your application (e.g. all data/buffers are fully end-to-end trusted) is where you'd consider like Flatbuffers, Protobufs, CapN Proto

WITH THAT IN MIND - I would also argue that if a schema based encoding library _can_ be made to work, it probably _should_ be.  Performance is pretty much always better with  schema'd formats like flatbuffers etc. All of that to say - maybe we should consider benching the new vector http sink/source with a few different libs to see what gives the best performance?
