### ISSUE TITLE
Consider not mutating the event if a remap script fails

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#6025]
This has come up a few times, most recently here: https://github.com/timberio/vector/pull/5958#discussion_r556382337. @spencergilbert also mentioned it in discord: https://discord.com/channels/742820443487993987/764187584452493323/788163053405208626.

For example, given the script:

```
.foo = 2
.bar = parse_json!("not json") # fails
```

The event will still have `foo = 2` set even though the script fails.

As a user, I'd have expected the remap script to be all-or-nothing rather than applying all changes up until it fails.

This is open for discussion though; I'm curious if others disagree. It could also be exposed as configurable behavior.

**Comment by spencergilbert** [comment]
I'm curious if this is still needed now that there are more powerful tools to handle errors and failures per function.

**Comment by jszwedko** [comment]
There has been improved error handling support to let you do things like `.foo = parse_json("not json") ?? null`, but we still support failing the entire script via `.foo = parse_json!("not json")` so I think this is still relevant.

**Comment by JeanMertz** [comment]
We could start simple, and clone the event before the remap transform starts processing the event, and then update the existing event if the processing succeeds, or keep the original unmodified event if it fails.

This obviously has a performance cost, as we need to do an extra allocation for every iteration of the event, but it might not be too much, and might be worth starting with, as the improved ergonomics of what happens if parsing fails probably outweighs the extra allocation.

**Comment by jszwedko** [comment]
Agreed, I think it'd be worth starting with just cloning.
