### ISSUE TITLE
Allow easier error checking in VRL

### ISSUE THREAD

**Issue by lucperkins** [timberio/vector#6060]
Currently in VRL, handling an error looks like this:

```js
json, err = parse_json(.message)
if err != null {
  log(err, level: "error")
}
```

It might be nice convenience to streamline error checking to `if err { ... }`, provided that it's consistent with other language constructs.

**Comment by JeanMertz** [comment]
> Currently in VRL, handling an error looks like this:

I wouldn't say this is accurate, since there are other ways to _handle_ errors. But yes, the `..., err =` assignment is the only way to actually get the actual error string.

I do think this will be a niche use-case though, so I'm not sure it's worth changing the semantics of the if-statement over, which is obviously a much more used language construct.

If we were to do this, we'd have to update the if-condition checker to expand its list of accepted types to include `null` (it currently only accepts booleans). I'm not saying we _shouldn't_ do this, but I'm also not convinced yet this specific use-care warrants doing so.

It's probably good to write up some more (more common) examples that would benefit from allowing `null` as a value, and/or a counter-case for why accepting null as a value in the conditional might be a bad idea (e.g. accidentally not triggering a branch because an expression always returns null at runtime where you thought it would return a boolean).

For the record can also write:

```js
if (json, err = parse_json(.message); err != null) {
  log(err, level: "error")
}
```

Which is a bit more idiomatic in Go, but I'm not saying it's better or worse in this specific case.

**Comment by JeanMertz** [comment]
I'm going to close this for now, as this hasn't come up as an issue so far. We can revisit it later if there's more demand for it.
