### ISSUE TITLE
Simplify BatchSink: use PartitionBatchSink as inner

### ISSUE THREAD

**Issue by fanatid** [timberio/vector#6062]
Was added in https://github.com/timberio/vector/pull/5076
Then reverted in https://github.com/timberio/vector/pull/5922 due to https://github.com/timberio/vector/issues/5698

Before we return BatchSink simplification we need resolve https://github.com/timberio/vector/issues/5589 and https://github.com/timberio/vector/issues/5894

**Comment by bruceg** [comment]
I think the problem with this has been identified in https://github.com/timberio/vector/pull/6251#discussion_r567476683: `BatchSink` uses `Batch::fresh_replace` to produce a new batch buffer, but `PartitionBatchSink` simply drops the batch buffer. Metrics sinks that use `MetricsBuffer` rely on the state being maintained between batches in order to handle metric kind conversion and aggregation properly.

I don't see a way to resolve this issue without maintaining partition state between batches instead of just dropping it. This unfortunately raises the possibility of a memory "leak" if there are an increasing number of partitions.

Another possibility is to move the metrics state out of the batch buffer and into the sink. This requires a more complex interaction between the batch sink and the buffer, and it is not obvious to me that it removes the need to maintain partition state.
