### ISSUE TITLE
Move docs to their own repo

### ISSUE THREAD

**Issue by LucioFranco** [timberio/vector#607]
I would like to bring up for discussion to move all docs and generators to their own repo. My main motivation for this is I use a lot of fuzzy searching functionality when I search say for the cloudwatch sink it actually brings up around 5-6 files where I only need the rust one. This can cause confusion and possibly slow down the development process especially for newer contributors.

cc @binarylogic

**Comment by binarylogic** [comment]
Sure, I'm indifferent. If it's affecting development in a negative way then I absolutely want to move them out. But here are the pros and cons as I see it:

**Pros:**

* Code and docs changes are coupled. This is much better than trying to sync changes in a separate repo.
* As a benefit of the above, tags are also coupled with docs, which means we can offer docs for each version of Vector seamlessly. I have Gitbook configured to do this which you can see in the top left when viewing our docs.
* I can use the same auto-generating tools for files outside of the /docs folder. For example the `/README.md` and all of the files in the `/config` folder are autogenerated.

**Cons:**

* The one you listed, although that should be easily solved with an exclusion rule in your editor.
* It adds a lot of noise to the commit history, since I can't preview docs in Gitbook until they hit master, which is very annoying.

I don't care how we do it, but I want to offer high-quality documentation that reflects the UX we are striving for. I'm open to any suggestions.

**Comment by binarylogic** [comment]
I'm going to close this, feel free to reopen if you want to discuss further.
