### ISSUE TITLE
Cleanup VRL function examples

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#6123]
The [examples](https://deploy-preview-272--vector-project.netlify.app/docs/reference/vrl/functions/) for the VRL functions are inaccurate and need some cleanup. In order to do this, I have a few open questions:

1. How should we demonstrate error handling? We could default to the `result, err = ...` style for fallible functions, or we could demonstrate both that and the `!` variation.
2. Should we remove the event intput and output? This can be a distraction from the function behavior. We can demonstrate the function without all of that. Ex:

	```js
	downcase("HELLO WORLD")
	=> hello world
	```

	This is sufficient to demonstrate the function behavior. On the other hand, it's very unlikely someone would use a function this way and the inclusion of event data makes it real-world.

cc @FungusHumungus and @JeanMertz for input on the above questions.

**Comment by FungusHumungus** [comment]
1. Another option once #6054 lands is `result, _ = ....`. I think this would be the cleanest way that avoids any excess clutter. Naturally, we are going need an extra section to document all the different ways to handle errors and the scenarios they apply to.

2. Personally I like the event input and output. It makes it clear what is happening. Certain functions have side effects and don't return anything (`del`, `merge`) - that needs to be demonstrated. A lot of the examples are demonstrating multiple facets of a particular functionality, storing the results in different variables. These would need to be separated out.
   To keep things cleaner we could ensure we use the same variable for input and output eg.. `.message = downcase(.message)`.

**Comment by JeanMertz** [comment]
> 1. How should we demonstrate error handling? [...]
> 
> 2. Should we remove the event intput and output? [...]

I think these two questions go hand-in-hand.

My proposal would be that for functions without side effects (e.g. everything but `del` and `merge`), use the most simplistic example possible:

```ruby
downcase("FOO") # "foo"
split(["foo,bar"], ",") # ["foo", "bar"]

# etc...
```

Doing this, means we no longer have to handle errors in those examples to make them parseable.

Then, error-handling can be delegated to the relevant section in our documentation, with sufficient examples and context. This way we don't _need_ to decide between `!` and `ok, err =` because both will be demonstrated alongside each other, as will all other error-handling features.
