### ISSUE TITLE
Require type information for fields with unknown types in Remap programs

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#6146]
I wanted to open this up for discussion before 0.12 since this would be a major breaking change if we decided to implement it afterward.

## Problem

I find the following VRL program cumbersome (taken from https://github.com/timberio/vector/pull/6144/files#diff-bb7210a52865718d818e9e36fb0f2d56b0d7bb822a7309106adc493217addf16R117-R119):

```js
if (is_critical, err = contains(.message, "Great Scott!"); err != null) {
  log(err, level: "error")
}

.critical = is_critical
```

Specifically the error handling for argument type errors. It's not intuitive since other languages do not require handling argument type errors at runtime. Typed languages catch this at compile-time, and untyped languages don't care about types 😁 . I fear that because of this, failure to handle argument type errors will be a common "gotcha" for programmers writing VRL programs.

## Solutions

To improve this we really only have 2 options:

1. Force users to tell us the type of fields with unknown types.
2. Abort at runtime for type errors.

2 is off the table since it makes VRL fragile in production environments; we've already decided to solve this with the requirement of error-handling. So that leaves us with 1, which is something I'm starting to come around to.

## Proposal

I propose that we implement solution 1 (require users to specify types). Out of context, requiring types for every single field feels overly cumbersome, but in practice, it isn't. If the user doesn't specify the type, then they must handle the error, so there is no getting around doing _something_. I would argue that handling type errors at runtime is less intuitive, and more cumbersome, than requiring the user to specify a type upfront. And if we're going to require the user to do _soemthing_, then we might as well guide them towards a solution that will improve their entire script.

Therefore, we should:

1. Raise a compile-time error for any field whose type is unknown.
2. Provide facilities that make type enforcement easy.

Note: this will be even easier when we support schemas throughout Vector.

### Example

Let's work through the above example:

```js
.critical = contains(.message, "Great Scott!")
```

Results in:

```
error: unhandled error
  ┌─ :1:1
  │
1 │ .critical = contains(.message, "Great Scott!")
  │                      ^^^^^^^^
  │ │
  │ `.message` is an unknown type, please specify the type
  │ hint: Add `.message = to_string!(.message)` at the top of your script
  │
  = see type safety documentation at: https://vector.dev/docs/reference/vrl/
```

To fix this, as noted in the hint, the user could do this:

```js
.message = to_string!(.message)
.critical = contains(.message, "Great Scott!")
```

As you can see, this 2 line program is quite a bit better than the original example:

1. It reads much better.
2. Errors will be clearer since they will happen at the explicit type coercion step.
3. It forces the user to think about type mismatches and how to handle them, instead of being surprised by a runtime error. For example, the user could decide to default the value instead of aborting: `.message = to_string(.message) ?? ""`.

I have other ideas, like type sigils, that could further improve this, but that feels out of scope for this issue.

**Comment by binarylogic** [comment]
Just noting, if there isn't a clear consensus then we should defer this. My intent is not to bog us down with a big type safety discussion before 0.12. But if we do have clear consensus then we should move forward with implementing this.

**Comment by JeanMertz** [comment]
Thanks for the write-up @binarylogic.

First, to get this out of the way, I don't consider this to be an idiomatic way to write such an example:

```js
if (is_critical, err = contains(.message, "Great Scott!"); err != null) {
  log(err, level: "error")
}

.critical = is_critical
```

I haven't done a deep review of the post yet, but I wouldn't advocate we add this the way it is.

Here's how I would write it:

```js
.critical ??= contains(.message, "Great Scott!")
```

Obviously, we don't have `??=` yet (but we will before 0.12 ships).

Now, the most significant difference is that we accept the fact that if `.message` isn't a string, we don't set this message as being critical.

This brings me to your proposal.

_If_ `.message` not being a string is such a problem, that it warrants logging an error, I would definitely advocate for using `to_string!` to enforce this check at the start of my program. So in that sense, I whole hardly agree with your proposal.

_However_... the biggest problem I have with this proposal is the fact that our `to_*` functions just _aren't sufficient to enforce type safety_.

I'm glad you used `to_string` because it's actually the worst of them all, but none of them have the property we need to enforce type safety satisfyingly. Namely, these are _coercion_ functions, _not_ type checking functions. For this specific example that might not matter, but `to_string` will happily take null, an integer, a float, a boolean, even a regular expression, and turn it into a string. The fact that it takes null is further amplified by the fact that non-existing path queries return null as well, so basically a call to `to_string!(.my.missing.field)` will always pass, and always return an empty string.

If we were to go this route (and — depending on how we do it — I'm generally a fan of this), I would definitely propose we either (1) add syntax checking as a built-in language feature, or (2) add purpose-built functions to check types, such as `assert_<type>` (fallible), and `is_<type>` (infallible). I'd also note my (rough draft) idea posted in https://github.com/timberio/vector/issues/5261#issuecomment-762086364 which would allow the compiler to deduce scoped type information using `if is_string(.message) { ... }`.

**Comment by lucperkins** [comment]
@JeanMertz FYI, I'm aware that that's not super idiomatic. In general I've just been only providing examples that I can independently verify. Happy to change later.

**Comment by FungusHumungus** [comment]
>  I'd also note my (rough draft) idea posted in [#5261 (comment)](https://github.com/timberio/vector/issues/5261#issuecomment-762086364) which would allow the compiler to deduce scoped type information using `if is_string(.message) { ... }`.

If you run `parse_syslog(...)` depending on the message, for example the result may or may not include an `appname`. When #6002 lands we will know that `appname` will either be a string or null.

So given this code:

```
.parsed = parse_syslog(.message)
if !is_null(.parsed.appname) {
  # We should know now that .parsed.appname is a string
  .bart = contains(.parsed.appname, "bart")
}
```

We should know that the call to `contains` will be infallible. I think that rough idea posted would be a big win for scenarios like here. Without that idea we will be forcing people to handle an error that will never be able to occur.

It would be unreasonable for us to expect them to call `to_string` on `.appname` to avoid handling the error that can never happen.
