### ISSUE TITLE
Vector Sinks Splunk HEC (Time / Timestamp) 

### ISSUE THREAD

**Issue by modularinput** [timberio/vector#6185]
I would like to outline a few issues I am experiencing, and request a feature for the Splunk HEC sink. If this needs to be broken into two requests just let me know.  

Issues:

Currently Splunk HEC supports the following metadata fields time, host, source, and sourcetype. 

Splunk HEC Event - Metadata Reference Only :

{
    "time": 1437522387,
    "host": "myserver",
    "source": "file",
    "sourcetype": "ids",
    "event": { 
        "message": "Something happened",
        "severity": "INFO"
    }
}  

The Vector Splunk HEC sink allows you to configure host_key, source, and sourcetype. Currently I can only get the source, and sourcetype configs to work correctly for this sink. The host_key config has not worked for me to this point. Is this a known issue?  

I'm also experiencing the unexpected removal of a JSON key called "timestamp" when sent via the Splunk HEC sink (see below). I can remap the field to "ts" or "time" via a Vector transform and it will show up in Splunk. Please note that the field is still available when I use a sink to write the event to file. I currently suspect that the Vector Splunk HEC sink is removing it. Thoughts / suggestions?                

Sample Data - Timestamp Field:

{"dest_ip":"192.168.0.20","dest_port":53,"dns":{"answers":[{"rdata":"172.217.22.74","rrname":"safebrowsing.googleapis.com","rrtype":"A","ttl":108}],"flags":"8180","grouped":{"A":["172.217.22.74"
]},"id":9308,"qr":true,"ra":true,"rcode":"NOERROR","rd":true,"rrname":"safebrowsing.googleapis.com","rrtype":"A","type":"answer","version":2},"event_type":"dns","file":"/var/log/suricata/eve.jso
n","flow_id":1463212928391824,"in_iface":"ens33","proto":"UDP","source_type":"file","src_ip":"192.168.0.60","src_port":63947,"time":"2021-01-22T08:10:43.858716-0500","timestamp":"2021-01-22T08:1
0:43.858716-0500"}

Feature Requests:

Please define which Splunk HEC endpoint Vector is sending to in the docs (Event|Raw). 

https://docs.splunk.com/Documentation/Splunk/8.1.1/Data/FormateventsforHTTPEventCollector

Please provide a way for users to format and set the Splunk HEC "time" metadata value based on a value in the event data. It is the only major Splunk metadata token Vector does not allow the user to define / set.  

Thanks!

**Comment by jszwedko** [comment]
Hi @modularinput !

Thanks for the report!

`host_key` should work. Can you share your configuration? You can set this to the key of any field that you'd like to use as the `host` metadata field in Splunk. This defaults to `host`; a field that is often assigned by the source component the events came from.

Regarding the timestamp, `vector` does pull the `timestamp` field, by default, from the event to use as the `time` field in Splunk. This field is removed from the event itself given that it is set as a first-class metadata field for Splunk. It sounds like you'd prefer this not to happen though, so that the event ends up in Splunk with the `timestamp` key as well as the Splunk `time` field set. Is that correct? I'm curious to hear more about why you prefer that. We could modify the behavior of the sink, or make it configurable.

We use the `/services/collector/event` HEC endpoint: https://docs.splunk.com/Documentation/Splunk/8.1.1/RESTREF/RESTinput#services.2Fcollector.2Fevent . I'll add that to the documentation.

**Comment by modularinput** [comment]
Hello @jszwedko 

Thanks for the reply!

Here is my config. I've also included a screenshot of the host value. 

```
[sources.src_suricata_01]
type = "file"
include = ["/var/log/suricata/eve.json"]

[transforms.t_suricata_01]
type = "remove_fields" 
inputs = ["src_suricata_01"] 
fields = ["host", "file","source_type"] 

[transforms.t_suricata_02]
type =  "filter"
inputs = ["t_suricata_01"]
condition.type = "check_fields"
condition."message.regex" = "\"event_type\":\"dns\"" 

[transforms.t_suricata_03]
type = "json_parser" 
inputs = ["t_suricata_02"] 
drop_field = true 
drop_invalid = false 
field = "message" 

[sinks.file]
type = "file"
encoding.codec = "ndjson"
inputs = ["t_suricata_03"]
path = "/tmp/vector-%Y-%m-%d.log"

[sinks.splunkt1]
type = "splunk_hec" 
inputs = ["t_suricata_03"] 
compression = "none" 
endpoint = "https://192.168.0.20:8088" 
host_key = "dev"
source = "junk"
sourcetype = "suricata_dns" 
token = "7ece7bc6-1123-4b83-b3d3-7ac910f012f9" 
encoding.codec = "json" 
tls.verify_certificate = false
```
Host value seen in Splunk.
 
![screenshot01](https://user-images.githubusercontent.com/49796843/106658575-c4259400-659d-11eb-96c4-f6a2bcca8af9.png)

#### Time Stamp
At the moment I do not see the behavior you are suggesting regarding timestamps. I've attached some data written to disk by the `sinks.file` section above.  

```JSON
{"dest_ip":"192.168.0.20","dest_port":53,"dns":{"answers":[{"rdata":"licensing.md.mp.microsoft.com.akadns.net","rrname":"licensing.mp.microsoft.com","rrtype":"CNAME","ttl":3237},{"rdata":"licensing-europeeap.md.mp.microsoft.com.akadns.net","rrname":"licensing.md.mp.microsoft.com.akadns.net","rrtype":"CNAME","ttl":118},{"rdata":"db5eap.licensing.md.mp.microsoft.com.akadns.net","rrname":"licensing-europeeap.md.mp.microsoft.com.akadns.net","rrtype":"CNAME","ttl":118},{"rdata":"52.158.24.209","rrname":"db5eap.licensing.md.mp.microsoft.com.akadns.net","rrtype":"A","ttl":118}],"flags":"8180","grouped":{"A":["52.158.24.209"],"CNAME":["licensing.md.mp.microsoft.com.akadns.net","licensing-europeeap.md.mp.microsoft.com.akadns.net","db5eap.licensing.md.mp.microsoft.com.akadns.net"]},"id":46056,"qr":true,"ra":true,"rcode":"NOERROR","rd":true,"rrname":"licensing.mp.microsoft.com","rrtype":"A","type":"answer","version":2},"event_type":"dns","flow_id":1531231985458456,"in_iface":"ens33","proto":"UDP","src_ip":"192.168.0.60","src_port":62098,"timestamp":"2021-02-02T15:48:15.863301-0500"}
```

Notice the `flow_id` of `1531231985458456` and its `timestamp` value of `2021-02-02T15:48:15.863301-0500`. We will use the `flow_id` value to compare the event in Splunk.  

![Screenshot 2021-02-02 221954](https://user-images.githubusercontent.com/49796843/106664060-dd7e0e80-65a4-11eb-86bf-6b142b27ac45.png)

When the event arrives at the Splunk indexer, the event `time` metadata is set to `2/2/21 8:48:16.560 PM`. For reference, my server's clock is set to UTC. I believe Splunk is currently setting the `time` field meta value to ingest / receipt time.      

I'm not sure that the Vector agent should remove fields automatically. It seems like the tool already offers the capability to do so via transforms. It is my belief that event fields should not be touched by the agent unless done so via a config setting by the user. 

There are two ways to work with the Splunk `event` endpoint from my perspective. 
1) Let Splunk timestamp the events at event ingest / receipt time. This already works.  
2) Give the Splunk sink a clean way to set the value from the log/event data (Sink Config). 

I'm looking for solution two at the moment.  

 Thanks

**Comment by jszwedko** [comment]
Thanks for the additional details @modularinput !

For the `host_key` I think there is some confusion about the way this operates,. Vector will use the value of this option, in your case `dev`, to attempt to pull a field from the event with that key. In this case, your event does not have a `dev` key so it is left out of the payload set to Splunk. Note this is different from the `sourcetype` metadata keys which are templatable strings. I believe Splunk is then setting it automatically it due to its absence. I admit this is confusing since the metadata fields are similar but behave slightly differently.

In your case, I think you could use the `add_fields` transform to add a `host` key and remove the `host_key` option from the `splunk_hec` sink:

```
[transforms.add_fields]
   type = "add_fields"
   inputs = [ ... ]
   fields.host = "dev"
```

If you drop the `host_key` option from the `splunk_hec` sink, it will automatically pick up the `host` key from the event.

For the timestamp, there is some subtle behavior here that is leading to what you are seeing:

* The `json_parser` transform you have parses the JSON, including the `timestamp` field, but it is added as a string field rather than further parsing it as a timestamp
* The `splunk_hec` sink pulls the `timestamp` field, but, because it is a string and not a timestamp, it drops it and uses "now" as the time. I opened an issue a while back about handling this better: https://github.com/timberio/vector/issues/4774

In order to parse the timestamp from your suricata logs so that vector represents it internally as a timestamp, you can the `coercer` transform:

```toml
[transforms.coercer]
  type = "coercer"
  inputs = ["t_suricata_03"]
  types.timestamp = "timestamp|%Y-%m-%dT%H:%M:%S%.f%:z"
```

This will cause the string to be parsed into a timestamp internally, and this timestamp will be sent to Splunk as the "time" field.

I agree with you that your event should not have its timestamp dropped. We have some work happening right now around event metadata that I think will aid with this. I'll make a note to include this example as a reference.

Hopefully this helps! Let me know if anything isn't clear.

**Comment by modularinput** [comment]
@jszwedko 

Thanks for taking the time to answer my questions, it is appreciated. I did misunderstand the config for `host_key`, but it's existence makes me think there should also be a config for `host`, where you can statically set the value if you choose. 

**Dynamic Host**
`host_key = "json_key"` 

**Static Host**
`host = "dev"`

I'm not sure I followed you with your comment about `sourcetype`. The next section may prove that. 

Based on your comments about the `host_key` feature, I do think it would be nice to be able to have a `sourcetype_key` where the value can be dynamically extracted from the event. In the sample data I used earlier in the thread, I might use the `event_type` key to set the `sourcetype` to `dns`. 

Ultimately I'd love to be able to do something like this :

**Example 1**
`sourcetype_key = "suricata:(key)` 

result = suricata:dns    

**Example 2**
`sourcetype_key = "cisco:ios:(key|regex)`  

result = cisco:ios:net

key = "rrname"
rrname = "licensing.md.mp.microsoft.com.akadns.net"    
regex = ([^.]+$)
result = "net"

Bad example, but I hope you get the point. 

Maybe it's asking for too much, but what I would like to do is set the Splunk HEC metadata values in the Vector Sink. It would be super convent. From a Splunk perspective, the ability to dynamically set the sourcetype would also be handy. Of course it can be done in Splunk, but this would eliminate some pain points. 

Following this train of thought, I would want the same capability for setting the time value. 

`timestamp = "alert_timestamp|%Y-%m-%dT%H:%M:%S%.f%:z"`     

I really like what Vector is doing, so keep up the good work. In the meantime I will take your feedback and test it out. 

Thanks!

**Comment by jszwedko** [comment]
Thanks for the response!

> Thanks for taking the time to answer my questions, it is appreciated. I did misunderstand the config for `host_key`, but it's existence makes me think there should also be a config for `host`, where you can statically set the value if you choose.

:+1: I agree with this. I'll opened https://github.com/timberio/vector/issues/6352 to track it.

> **Example 1**
> `sourcetype_key = "suricata:(key)`

You can actually do this with something like `sourcetype = "suricata:{{ key }}"` where `key` will be pulled from the event. See https://vector.dev/docs/reference/templates/ for more details. These templates can be used for any field in vector marked as "templatable" in the docs.

> Following this train of thought, I would want the same capability for setting the time value.
> 
> `timestamp = "alert_timestamp|%Y-%m-%dT%H:%M:%S%.f%:z"`

I'm not sure I completely follow this one. You'd like set the `timestamp` to whatever `alert_timestamp` is? If so, I think https://github.com/timberio/vector/issues/6352 could also encompass that use-case. I'll note it there.

Let me know if that helps!

**Comment by modularinput** [comment]
Thanks for considering the feature. 

I'll try out the template reference soon. It would be nice if the template / partitioning supported regex so you could go after targeted subsections of a key value.

#### Regex Feedback

`host_key = "suricata:{{ key|regex }}"`

Where:
`key` eq `"source":"/mnt/syslog/firewall/cisco/phx01_ext_switch/20210204.log"` 
`regex` eq `^.*\/(.*?)\/\d{8}.log`   

**Sink Config**

`host_key = "{{source|^.*\/(.*?)\/\d{8}.log}}"`

**Splunk Index**

`host="phx01_ext_switch"`

The main point here is that the template function is great, but it needs some scissors (regex) to pull out sub patterns. For the Splunk HEC Sink, it would be something you could do on `host`, `source`, `sourcetype`.   

#### Timestamp Feedback

Two points here. 

1) I would like `time` to be a value you can set in the Splunk HEC Sink like `host`, `source`, `sourcetype`. 
2) It should have the ability to point to either strings or fields recognized as timestamps, but requires the user to identify the key name and timestamp formatting. 

`time = "key|%Y-%m-%dT%H:%M:%S%.f%:z"`  

#### Reference for future Google searches about populating dynamic metadata values using Vector's Splunk HEC Sink .

[Splunk Hec Partitioning / Template](https://vector.dev/docs/reference/sinks/splunk_hec/#partitioning)

**Comment by jszwedko** [comment]
> I'll try out the template reference soon. It would be nice if the template / partitioning supported regex so you could go after targeted subsections of a key value.

Agreed. We have been thinking about how to incorporate those sorts of manipulations in templates. https://github.com/timberio/vector/issues/2063 is the tracking issue for that.

> Two points here.
> 
>     1. I would like `time` to be a value you can set in the Splunk HEC Sink like `host`, `source`, `sourcetype`.
> 
>     2. It should have the ability to point to either strings or fields recognized as timestamps, but requires the user to identify the key name and timestamp formatting.
> 
> 
> `time = "key|%Y-%m-%dT%H:%M:%S%.f%:z"`

Also a good idea! I opened https://github.com/timberio/vector/issues/6368

**Comment by modularinput** [comment]
@jszwedko 

I don't have any additional feedback on the Splunk HEC Sink at this time. Should I close this out or leave it open?

**Comment by jszwedko** [comment]
Thanks for all of the feedback! I think we can close this in-lieu of the other issues.
