### ISSUE TITLE
Alpine Linux Install

### ISSUE THREAD

**Issue by krisread** [timberio/vector#630]
For those using docker images based on Alpine (extremely popular) what's the installation path?   Wondering if this is on the roadmap.

**Comment by binarylogic** [comment]
Hey @krisread, I believe we'll need to compile using musl to support Alpine Linux. We had issues compiling the `leveldb` and `rdkafka` libraries for that platform. To be specific, _I_ had issues, and this is a little outside of my expertise. It's very possible, and it something we will support, but unfortunately it wasn't something I could solve.

I'm in the process of finding someone to help with compiling these libraries across a number of platforms (including musl). If you can help, or know anyone, that would be very helpful. Otherwise, we expect to resolve this in the next few weeks.

**Comment by LucioFranco** [comment]
The other bigger issue is that `jemalloc` is not currently supported on musl either. Is there anyway you can use debian based images that are still pretty slim?

**Comment by krisread** [comment]
I understand this is tough.  I feel like the point of a log aggregator is to consistently collect logs from many potentially different images, OS-es, teams or projects.  So for a bigger company, they are bound to have different types of images in the wild, with many existing Dockerfiles that may have to be completely re-authored from scratch if switching OS, with incompatibilities to resolve in other dependencies or installing other packages on the image etc.   Odd choice to write Vector in a way that isn't portable from day 1 just my 2c.

**Comment by binarylogic** [comment]
Hey @krisread, we definitely agree. We _will_ support Alpine Linux as well as a variety of other targets. To be honest, we were not aware we'd have so much trouble with `leveldb` and `rdkafka`. We do know it is possible to compile those for a variety of targets, and we'll get that solved.

In the interim, we're probably going to release preliminary versions that have those features disabled, because a lot of use cases don't need them. We'll make that clear in the docs.

**Comment by binarylogic** [comment]
This is resolved now, but with the caveat that on-disk buffers and the `kafka` sink are not enabled, which should be fine for many use cases. A stop gap until we can get those resolved.

**Comment by binarylogic** [comment]
Hey @krisread, thanks to the excellent work over in #689 we have a single fully static binary and have released an alpine image. Hope that helps.
