### ISSUE TITLE
Add kubeval to checks and CI

### ISSUE THREAD

**Issue by MOZGIII** [timberio/vector#6413]
https://github.com/instrumenta/kubeval

**Comment by spencergilbert** [comment]
@jszwedko @binarylogic I had previously used https://github.com/yannh/kubeconform instead of kubeval, primarily due to auto-updating source of kubernetes schemas as well as some improvements around usability and test outputs. I'm not sure the test outputs are as relevant (I'm less familiar with how they may be integrated/displayed on GitHub PRs), but the more expansive selection of schemas may be useful to ensure the kubernetes resources are valid given a supported matrix of kubernetes versions.

I think there was a quiet period where kubeval wasn't getting any new commits, but it seems active again.

> It is inspired by, contains code from and is designed to stay close to Kubeval, but with the following improvements:
>
> high performance: will validate & download manifests over multiple routines, caching downloaded files in memory
> configurable list of remote, or local schemas locations, enabling validating Kubernetes custom resources (CRDs) and offline > validation capabilities
> uses by default a self-updating fork of the schemas registry maintained by the kubernetes-json-schema project - which > guarantees up-to-date schemas for all recent versions of Kubernetes.

**Comment by binarylogic** [comment]
Makes sense. I'm indifferent, it's your call. My obvious concern with kubeconform is its lack of popularity and risk of being abandoned. Neither projects seem to be getting a lot of activity. If it's easier to swap out then go with the one the brings the most current value.

**Comment by jszwedko** [comment]
Agreed, I defer to your judgement. It does seem not too difficult to switch if we need to and `kubeconform` seems like a superset of `kubeval`.

**Comment by spencergilbert** [comment]
They should be pretty straight swappable - I think since we're punting on testing across a number of different there's not a great benefit to switching tools right now. I'll mention it in the issue I open for validating our resources across a number of supported kubernetes versions.
