### ISSUE TITLE
Migrate and revive unit tests for VRL standard library

### ISSUE THREAD

**Issue by pablosichert** [timberio/vector#6492]
As part of #6353, almost all unit tests for the standard library functions were commented out.

These should be brought back and migrated accordingly.

**Comment by jszwedko** [comment]
@pablosichert I noticed tests that are still commented out:

https://github.com/timberio/vector/blob/234e4665ad0c80fee1c4dfeafe1887e97a012c7a/lib/vrl/stdlib/src/ipv6_to_ipv4.rs#L64-L107
https://github.com/timberio/vector/blob/234e4665ad0c80fee1c4dfeafe1887e97a012c7a/lib/vrl/stdlib/src/uuid_v4.rs#L41-L65

Was this intentional?

```
$ rg '//.*\#\[cfg\(test\)\]' lib/vrl/stdlib
lib/vrl/stdlib/src/merge.rs
58://     #[cfg(test)]

lib/vrl/stdlib/src/truncate.rs
106:// #[cfg(test)]

lib/vrl/stdlib/src/upcase.rs
51:// #[cfg(test)]

lib/vrl/stdlib/src/uuid_v4.rs
41:// #[cfg(test)]
```

**Comment by jszwedko** [comment]
Reopening just to track. We can close again if this was intentional.
