### ISSUE TITLE
Multiline unexpacted behavior with large java trace

### ISSUE THREAD

**Issue by alpi-ua** [timberio/vector#6855]
I have a java app with the huge output from errors, new events are starting with the DATE.
It seems, that in some cases file's input with multi line combining is not working properly.

```
vector 0.11.1 (v0.11.1 x86_64-unknown-linux-gnu 2020-12-17)
```

### Vector Configuration File

```
[sources.file_app]
  type = "file"
  include = ["/opt/app/*/logs/*/*.log"]
  fingerprint.strategy = "device_and_inode"

  [sources.file_app.multiline]
     start_pattern = '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
     mode = "halt_before"
     condition_pattern = '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
     timeout_ms = 60000

[transforms.app_filter]
  type = "filter"
  inputs = ["file_app"]
  condition.type = "check_fields"
  condition."message.not_contains" = "CONDITION"
  condition."message.not_regex" = " (INFO|DEBUG|TRACE) "

[sinks.solar_prod]
  type = "vector"
  inputs = ["app_filter","app_stderror"]
  address = "server.com:5001"
#  healthcheck = true

  buffer.max_size = 10100000
  buffer.type = "disk"
  buffer.when_full = "block"

```

### Debug Output
```

https://gist.github.com/alpi-ua/fb3a867b2f1fe1fab53dbb51fce096c6
```

### Expected Behavior
All events get combined with the multiline config settings

### Actual Behavior
Sometimes in Kibana i see that events are not get combined. 
It looks unpredictable to me, in 10 minutes, among tens of successfully combined events i have few which came to elasticsearch separately. 
I can't see any pattern in the trace output.

### Example Data
```Please, see a comment to Gist with a screenshot.```

**Comment by jszwedko** [comment]
Hi @alpi-ua !

Thanks for reporting this. Looking at your screenshot and logs it seems like vector encounters a line that it think stops the group and then continues to read the rest of the set as individual lines given they don't match `start_pattern`.

Would it be possible to share the set of lines that is not being combined properly? Feel free to strip out any sensitive data first, of course. The entire log file would be even better.

**Comment by alpi-ua** [comment]
Thank you for the fast reply. 
I also thought that some line is causing this. But was unable to find it.
Here a gist with the detailed log

> https://gist.github.com/alpi-ua/bb85ef41e88bef9bd9010564284a022e#file-vector-multiline-error-log-L58

It's strange, but last hour and half I changed timeout_ms = 999999999 and the issue has gone.
![зображення](https://user-images.githubusercontent.com/14225967/112068415-8216d880-8b72-11eb-83ef-15975b86f3d6.png)

I feel confused. Could you please explain this ?
I thought that 2000ms should be enough, but for some reason even 60s was not.

**Comment by jszwedko** [comment]
Comment from discord:

```
Just reading through some of the past github issues and an explanation by @jszwedko 
so the only line in my log file where the halt_before condition is not met( doesn't have another timestamp as EOF is hit) is the last line of the log, something like the following:
The problem is when this timeout is hit it breaks all the other lines which do have a valid
halt condition.
Funny thing is even though this is the last line of the file looks like somehow the timer starts as soon as we start reading the file( the default file start is beginning so confused what might be happening here)
```

It seems like Vector might not be maintaining the multiline behavior across file rotations.

**Comment by kartikv31** [comment]
Seeing the same issue as well
Mentioned this on discord.

Team , need some help with multiline logs and looks like there may be a bug with timeout_ms
### Configuration

```
[sources.xxxx_logs]
  type = "file"
  include = ["/home/kartikv/file.txt"]
  ignore_checkpoints = true
  oldest_first = true

  [sources.xxxx_logs.multiline]
    start_pattern = '^[0-9]{4}.[0-9]{2}.[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}:[0-9]{3} [A-Z]{3}'
    mode = "halt_before"
    condition_pattern = '^[0-9]{4}.[0-9]{2}.[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}:[0-9]{3} [A-Z]{3}'
    timeout_ms = 1000
```

The log lines are as follows. The multiline feature works well till we hit 1000 ms from the beginning of vector parsing these lines and then it stops combining multiple lines 


### Log file

```
2021.03.16 14:30:14:511 UTC | Info       | CallP | Call | +1xxxxxxx | D873934BE729A5EEE040 | callhalf-21028772723:1 | 726ce7c0-3123-482a-8b8c-5dac9f5448f1

        Event: com.broadsoft.events.callhalf.InvitationEvent
        Consumed by: com.broadsoft.services.dnh.DirectoryNumberHuntingServiceInstance

2021.03.16 14:30:14:511 UTC | Info       | SubscriberSubsystem | Main Identity | users | xxxxxx@ims.comcast.net | localHost1452895 | 726ce7c0-3123-482a-8b8c-5dac9f5448f1

        Processing event SubscriberAgentProfileSubscribeReadRequestEvent[xpath: /sub:broadworks/subscriber/users/entry[uniqueKey='xxxxxx@xxxx.net']]
```

The issue resolves if I give a higher value for timeout_ms . This works well for one file but lets say I am trying to process a bunch of files in a directory then combining multiline fails from the start of vector processing these lines, so even 10-15 min later I would run into this issue. I can keep increasing the timeout but do not understand the side effect( or we then buffering for a long time using up more memory or disk buffers) My understanding of this timeout was for a single multiline log event but seems a bug where the timer is never reset

so the only line in my log file where the halt_before condition is not met( doesn't have another timestamp as EOF is hit) is the last line of the log, something like the following:
The problem is when this timeout is hit it breaks all the other lines which do have a valid
halt condition.
Funny thing is even though this is the last line of the file looks like somehow the timer starts as soon as we start reading the file( the default file start ( read_from_ is beginning so confused what might be happening here).
Even if I add an OR condition for halt to recognize the last line , the timer still trips post the beginning of the file and I cannot see any thing in the file that would timeout on halt_before. 
 
```
2021.03.16 14:30:21:297 UTC | Notice     | Generic

        Last log in file.  Rotating Log File.Due to file size limitation.
```
