### ISSUE TITLE
Add a VRL function for parsing a user agent string

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#7077]
Requested by user in discord: https://discord.com/channels/742820443487993987/746070604192415834/830228189417963520

They'd like to parse a user-agent string to determine the device type (for example apple or android).

We should figure out what the requirements are here though. This python library could be used as an example: https://pypi.org/project/user-agents/

**Comment by StephenSorriaux** [comment]
Hello there,

Just came across your issue while working on a similar thing, if that can help somehow here a full list of regexes used by a well know analytics tracker: https://s3-eu-west-1.amazonaws.com/snowplow-hosted-assets/third-party/ua-parser/regexes-latest.yaml

**Comment by ktff** [comment]
@StephenSorriaux nice! Thanks.

**Comment by ktff** [comment]
### Problem
While the definition of how user agent string is constructed is well defined, meaning of individual fields is not. As a consequence there are two approaches to parsing:
* Data driven
* Meaning driven

Data driven just means that to parse all of the product and comment fields into arrays. While that can be done for any user agent string it provides limited usability to users since they need to continue parsing by hand to extract any usable information. Also, this kind of parsing can easily be done by a generic parser that can split by a whitespace. (ex. `parse_tokens` and `parse_regex`) For these reasons this isn't the path we are going.

Meaning driven means that the parser has knowledge of real world. It knows what `Apple`, `Xbox`, `Firefox`, etc. are. It knows that in
```
Mozilla/5.0 (Linux; U; Android 2.2.1; En-us; SBM005SH Build/S0900) AppleWebKit/533.1 (KHTML, Like Gecko) Version/4.0 Mobile Safari/533.1
```
`SBM005SH` is a model of a smartphone of brand `Sharp` so it can parse it accordingly. For these reasons our only practical option is to use libraries. Mentioned Python library parses like this.

### Libraries
So, there are two siginifcant ecosystems, that have a Rust crate, around parsing user agent strings:
* [Project Woothee](https://github.com/woothee/woothee), [crate](https://crates.io/crates/woothee)
* [uap](https://github.com/ua-parser/uap-core), [crate](https://crates.io/crates/uaparser)  (Mentioned Python library is a part of this ecosystem) 

There are two characteristics that are relevant for us, `Woothee` is significantly faster but `uap` can parse out significantly more cases. Both options are best in some cases and both are useless in some other:
* `Woothee` is much better when there is a high throughput of events with common user agent strings but is useless when it comes to more niche agent strings. 

* `uap` is much better when a more consistent/reliable parsing is needed, but is unusable when high throughput is needed. Think half of milisecond to parse a string.

### VRL Function
With that in mind 
```
parse_user_agent(value: <string>, mode: <string>) :: <object>
```
function would accept the user agent string but also a mode option. There would be three modes:
* `fast` 
     * This would only use `Woothee` parser.
     * Useful when throughput is a priority.
* `reliable` 
     * This would use `Woothee` parser and if it fails to parse any of the fields `uap` parser would be used.
     * Useful as a middle ground when more reliability and throughput is needed but in most cases it will be parsing common browser user agent strings.
 * `enriched`
     * Uses both `Woothee` and `uap`.
     * Useful when the priority is to extract as much information as possible.

Considering that for parsing user agent strings we can only provide best effort guarantee this function would be `infallible`.

To support easily switching modes a common return object schema is used:
```
{
    app: {
    	name:    String {ex. Firefox, Opera, Curl}
        version: String
        major:   String
    	minor:   String
    	patch:   String
    }
    os: {
    	name: 		 String {ex. Windows, Android, iOS}	
    	version: 	 String	
    	major: 		 String	
    	minor: 		 String	
    	patch: 		 String	
    	patch_minor:     String
    }
    device: {
    	category: String {smartphone, pc, mobilephone, appliance, misc, crawler}
    	family:   String		
    	brand: 	  String {ex. Acer, Apple, Sharp}
    	model: 	  String		
    }
}
```
Where only `enriched` mode would return the full schema. While `fast` and `reliable` will return the subset:
```
{
    app: {
    	name:    String
        version: String
    }
    os: {
    	name:    String	
    	version: String	
    }
    device: {
    	category: String
    }
}
``` 
This difference in what modes can return is a consequence of `Woothee` and `uap` different parsing capabilities. We could always return the full schema and set other values as `null` but by differentiating between them we are expressing what the user can and can not expect to be parsed out by a mode.

In the case of a field not being parsed out, `null` value would be set instead.

### References
* https://datatracker.ietf.org/doc/html/rfc2616#section-14.43
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

cc. @jszwedko

**Comment by jszwedko** [comment]
Thanks for this write-up @ktff !

Just to help me understand the problem better:

* Could we get raw benchmark numbers for both of those libraries?
* Could you provide some examples of things that Woothee handles that uap does not? Ideally it'd be nice to know the percentages of user-agents in the wild that could be handled by each, but I realize that may be difficult to tell 😄 

I agree, if we go this route, that the schema should be the same regardless of the mode.

**Comment by leebenson** [comment]
@vladimir-dd, is this relevant for our current Datadog parsing work?

**Comment by ktff** [comment]
@jszwedko here are the results
```
Examples All: 35124!
Woothee
    any 81.65%
    min 74.27%
    avg 68.57%
    0.551742328 sec
    15708 nanos per element

uap
    any 98.22%
    min 72.00%
    avg 53.58%
    34.792485958 sec
    990561 nanos per element

Both
    any 98.45%
    min 85.98%
    avg 57.99%
    30.761330995 sec
    875792 nanos per element
```

Lines with `sec` and `per element` should be self explanatory, while the others are:
- `any` parser was able to parse anything from user agent string
- `min` parser was able to parse at least one information for each `app`, `os`, `device` category
- `avg` on average parser was able to parse x% of fields that it can parse out
   - uap has 12 fields that we would use, Woothee 5, and Both has 15

Examples are a combination of uap, Woothee, and third party test suits. Where uap has 30k examples, Woothee 300, and third party 5k. All examples are unique.

It should also be taken into account that these percentages don't take into account that some strings simply don't have the information. ex. "SIE-M55C"

Benchmarked on a budget laptop. 

There are variation in time of execution as seen in the above results for `uap` and `Both` but even with that variation uap doesn't even come close to the speed of Woothee.

Examples from which nothing has been parsed:
* Woothee (but uap has)
   * "Mozilla/5.0 (Java; U; en-us; samsung-gt-c3262) AppleWebKit/530.13 (KHTML, like Gecko) UCBrowser/8.6.0.199/69/444/UCWEB Mobile, SAMSUNG-GT-C3262/C3262DDLHA Profile/MIDP-2.0 Configuration/CLDC-1.1 Untrusted/1.0"
   * "SAMSUNG-GT-M8800"
   * "Mozilla/5.0 (OpenBSD; en-US) Gecko/20030624 Netscape/7.2"
   * "LG-MG100a MIC/WAP2.0 MIDP-2.0/CLDC-1.0"

* uap (but Woothee has)
   * "Jakarta Commons-HttpClient/2.0.2"
   * "Mozilla/5.0 (Macintosh; U; PPC; en-US; rv:0.9.2) Gecko/2001"
   * "mixi-check/1.0 (http://mixi.jp/)"
   * "IE6.0,Java(TM) 2 Runtime Environment, Standard Edition"

* Both
   * "LTH Browser"
   * "Mozilla/4.7 [en] (Macintosh; I; PPC)"
   * "Mozilla/9.0 (Atari2600; U)"
   * "Netscape 7.02"
   * "w3m/0.3"

**Comment by jszwedko** [comment]
Thanks for the additional detail @ktff !

`uap` is definitely very slow comparatively. It seems like it would limit throughput to ~1k messages / second using that benchmark.

I was thinking it might be confusing to users to have this additional toggle to think about, but there does appear to be a real trade-off here in terms of performance and functionality that users may want to make the trade-off for. I think we should default to `fast` though.

**Comment by ktff** [comment]
>  I think we should default to fast though.

True, it's a good default..

**Comment by jszwedko** [comment]
@ktff I chatted with @vladimir-dd about how Datadog currently supports this. It sounds like they use the `ua-parser` regex suite to produce output like you see here: https://docs.datadoghq.com/logs/log_configuration/processors/?tab=ui#user-agent-parser

I believe this same regex set is supported by the `uap` crate you found? it looks like there is another crate too: [`user-agent-parser`](https://crates.io/crates/user-agent-parser). Maybe it is worth seeing if that one performs any better?

I think we should try to:

* Match the Datadog schema output if we can
* Ensure we support the same functionality; at least in an opt-in fashion like you suggested above

**Comment by vladimir-dd** [comment]
Thanks @ktff  

It would be nice indeed if we could at least provide an option to support `uap`-based parsing and match DD output schema, which is:
```
browser:
- family (taken from family_replacement) 
- major (v1_replacement)
- minor (v2_replacement)
- patch (match group 4)
 
os:
- family (os_replacement)
- major (os_v1_replacement)
- minor (os_v2_replacement)
- patch (os_v3_replacement)
- patch_minor  (match group 5)
  
device:
- family (device_replacement)
- brand (brand_replacement)
- model (model_replacement)
```

**Comment by ktff** [comment]
> I believe this same regex set is supported by the uap crate you found?

@jszwedko yep, they are based on the same project [`uap-core`](https://github.com/ua-parser/uap-core) and, if not configured differently, use the same regex set.

>  user-agent-parser. Maybe it is worth seeing if that one performs any better?

:+1:  I'll check it out.

> match DD output schema

@vladimir-dd that's easy since the proposed [schema](https://github.com/timberio/vector/issues/7077#issuecomment-859833619) is based on `uap` so just some fields need to be renamed to match DD schema. 
```
app -> browser
name -> family
```
while the extra fields `version` and `category` shouldn't be a problem.

>  provide an option to support uap-based parsing

that would be `enriched` mode which will always use `uap` parser. We can also mention in the documentation that `uap` parser is used so to better describe the functionality and draw parallels with DD. Actually we can be transparent on this and say which parsers are used in which mode since it seems they are well known, maybe even rename modes to something like `woothee`, `woothee_else_uap`, and `woothee_and_uap`.

That leaves us with the last functionality "decode the URL" that DD has which seems kinda out of scope for this function so we can leave that for later.

**Comment by jszwedko** [comment]
Makes sense thanks @ktff 👍 

> That leaves us with the last functionality "decode the URL" that DD has which seems kinda out of scope for this function so we can leave that for later.

Agreed.

**Comment by ktff** [comment]
> it looks like there is another crate too: user-agent-parser. Maybe it is worth seeing if that one performs any better?

It's slightly slower and less used.

**Comment by pront** [comment]
Recently changed with: https://github.com/vectordotdev/vrl/pull/1317
