### ISSUE TITLE
Add label from Kubernetes namespace to logs coming from pods in that namespace

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#7123]
Requested by a user. This was originally reported as https://github.com/timberio/vector/issues/6905 but there was some confusion about what they wanted so we closed that issue thinking we already supported their use cases.

The user has custom labels on their namespaces that they'd like to propagate to the log events coming from `kubernetes_logs` from pods in those namespaces.

This could be part of `kubernetes_logs` or a separate enrichment transform like `aws_ec2_metadata`.

They are currently using fluentbit for shipping logs. Fluentbit doesn't have direct support, so they maintain a mapping in fluentbit config to associate the desired labels, but this is a manual process to maintain the labels.

**Comment by mmerickel** [comment]
This is the only feature preventing me from trying to replace our fluentd setup with vector for sourcing logs from the cluster. We need the namespace labels to influence where logs are routed.

In fluentd I'm able to configure something that says "if namespace has a `$label_key`, then route logs to aws firehose, otherwise send logs directly to cloudwatch". Firehose then uses the label value to route things.

To avoid bloating the records, it might be desirable to be able to configure which labels/annotations we want picked up from the pod and namespace? Or that could be done with a filter transform downstream. I'd love to see `namespace_labels` included alongside the existing `pod_labels`.

**Comment by spencergilbert** [comment]
Discussed with @jszwedko a bit about if this should be built into the existing source or as a new transform. There's some desire for a standalone kubernetes enricher, but nothing planned in the near term.

I'll be adding this to the source unless there are serious objections

**Comment by spencergilbert** [comment]
Noting it's likely that #7589 can/should be solved by this work as well

**Comment by jszwedko** [comment]
🥳
