### ISSUE TITLE
Support sets in the prometheus sink

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#713]
Creating a follow up issue for https://github.com/timberio/vector/pull/675#discussion_r310926184

Currently the `prometheus` sink [does not support sets](https://github.com/timberio/vector/blob/3c36de2691c263dfbbda747d3d328b445ec174ff/src/sinks/prometheus.rs#L213). It appears we can support them by converting them to gauge / counters. We can address this separately in a follow up PR.

**Comment by ktff** [comment]
As you have said, I see two options:

1. Implement using counters.

**Comment by ktff** [comment]
@binarylogic 
As you have said, I see two options for implementation:

1. Using integer counters. 

   - Set will count unique occurrences, and in all other ways will behave like a counter. 

   - Simpler version.

2. Using integer gauges. 

   - Set will count unique occurrences, but the count can be reseted after some time. 

   - Configuration of max duration between resets can be added to prometheus sink configuration, or pulled from some configuration if it's already configured there. 

   - Default max duration is infinity, and as such will by default behave as version 1.  

   - More complex version, since it requires an additional future which would yield for max duration after which it would reset all gauges of sets, and repeat.

**Comment by binarylogic** [comment]
@ktff I think option 1 makes the most sense for now.

**Comment by ktff** [comment]
I agree.
I'll implement option 1 then.
