### ISSUE TITLE
potential security vulnerabilities in imported libraries

### ISSUE THREAD

**Issue by jeromekleinen-kbc** [timberio/vector#7146]
Hi guys,

$dayjob asked me to scan the source code of vector with Whitesource, a commercial library scanner, to detect if any known vulnerable versions are in use. I have attached the report for the current master branch. Whitesource believes 24 libraries are in use that could be vulnerable in one way or another. I am not too familiar with Whitesource or the quality it produces, so these could be false positives.

Thanks,

Jerome
[Vector-alerts-report.xlsx](https://github.com/timberio/vector/files/6325634/Vector-alerts-report.xlsx)

**Comment by jeromekleinen-kbc** [comment]
I've rescanned the source code after the big cargo upgrade. It has already resolved some of the findings.

I've sorted the report by crate name, as there are quite some duplicates with various versions supposedly in use.
[Vector-alerts-report_20210419.xlsx](https://github.com/timberio/vector/files/6336675/Vector-alerts-report_20210419.xlsx)

**Comment by jszwedko** [comment]
Thanks so much @jeromekleinen-kbc !

I took a look at these. Details below:

* `crossbeam-channel-0.4.4.crate`
  * `CVE-2020-15254`: indicates that `crossbeam-channel` 0.4.4, which we are using, is not affected; it is the first fixed version
* `crossbeam-queue-0.2.3.crate`
  * `CVE-2020-15254`: similar to `crossbeam-channel` 0.2.3 also seems to include the fix for this CVE
* `curl-sys-0.4.41+curl-7.75.0.crate`
  * `CVE-2021-22876`: fixed by https://github.com/timberio/vector/pull/7174
  * `CVE-2021-22890`: fixed by https://github.com/timberio/vector/pull/7174
* `failure-0.1.8.crate`
  * `CVE-2019-25010` indicates that the last affected version was 0.1.5 but we are using 0.1.8
* `krb5-src-0.2.4+1.18.2.crate`
  * `CVE-2020-28196` I opened https://github.com/timberio/vector/issues/7175 to track this
  * `CVE-2021-23358` seems to be for a nodejs package?
* `mio-0.6.23.crate`
  * `CVE-2020-35922`: It looks like only versions between 0.7.0 and 0.7.6 are affected (https://github.com/RustSec/advisory-db/blob/c71cfec8c3fe313c9445a9ab0ae9b7faedda850a/crates/mio/RUSTSEC-2020-0081.md). We are including both 0.6.23 and 0.7.11, neither of which should be affected.
* `onig_sys-69.1.0.crate`
  * `CVE-2019-13224`: Resolved by https://github.com/timberio/vector/pull/7176
  * `CVE-2019-13225`: Resolved by https://github.com/timberio/vector/pull/7176
  * `CVE-2019-16163`: Resolved by https://github.com/timberio/vector/pull/7176
  * `CVE-2019-19012`: Resolved by https://github.com/timberio/vector/pull/7176
  * `CVE-2019-19203`: Resolved by https://github.com/timberio/vector/pull/7176
  * `CVE-2019-19204`: Resolved by https://github.com/timberio/vector/pull/7176
  * `CVE-2019-19246`: Resolved by https://github.com/timberio/vector/pull/7176
* `openssl-src-111.15.0+1.1.1k.crate`
  * `CVE-2020-25657`: This seems to refer to a Python library, m2crypto?
* `prost-0.6.1.crate`
  * `CVE-2020-35858`: Indicates that prost 0.6.1 is the first fixed version so we should be unaffected.
* `prost-0.7.0.crate`:
  * `CVE-2020-35858`: Indicates that prost 0.6.1 is the first fixed version so we should be unaffected.
* `prost-derive-0.6.1.crate`
  * `CVE-2020-35858`: Indicates that prost 0.6.1 is the first fixed version so we should be unaffected.
* `prost-derive-0.7.0.crate`:
  * `CVE-2020-35858`: Indicates that prost 0.6.1 is the first fixed version so we should be unaffected.
* `rand_core-0.3.1.crate`
  * `CVE-2020-25576`: https://github.com/RustSec/advisory-db/blob/c71cfec8c3fe313c9445a9ab0ae9b7faedda850a/crates/rand_core/RUSTSEC-2019-0035.md indicates that 0.3.1 is also a fixed version so should be unaffected.
  * `CVE-2021-27378`: Indicates that versions prior to 0.6.0 are unaffected, which would include 0.3.1
* `rand_core-0.4.2.crate`
  * `CVE-2021-27378`: Indicates that versions prior to 0.6.0 are unaffected, which would include 0.4.2
* `rand_core-0.5.1.crate`
  * `CVE-2021-27378`: Indicates that versions prior to 0.6.0 are unaffected, which would include 0.5.1
* `rand_core-0.6.1.crate`
  * `CVE-2021-27378`: We are using 0.6.2 of rand_core, which includes this fix
* `raw-cpuid-6.1.0.crate`
  * `CVE-2021-26306`: Tracked as https://github.com/timberio/vector/issues/6223. The affected version of raw-cpuid is not included in released artifacts though, just custom builds enabling WASM.
  * `CVE-2021-26307`: Tracked as https://github.com/timberio/vector/issues/6223. The affected version of raw-cpuid is not included in released artifacts though, just custom builds enabling WASM.
* `raw-cpuid-7.0.4.crate`
  * `CVE-2021-26306`: Tracked as https://github.com/timberio/vector/issues/6223. The affected version of raw-cpuid is not included in released artifacts though, just custom builds enabling WASM.
  * `CVE-2021-26307`: Tracked as https://github.com/timberio/vector/issues/6223. The affected version of raw-cpuid is not included in released artifacts though, just custom builds enabling WASM.
* `rlua-0.17.0.crate`
  * `CVE-2019-6706`: Tracking as https://github.com/timberio/vector/issues/7177
  * `CVE-2020-15888`: Tracking as https://github.com/timberio/vector/issues/7177
  * `CVE-2020-15889`: It seems like only Lua 5.4.0 is affected which means our current bundled version of 5.3.5 is fine.
  * `CVE-2020-15945`: Tracking as https://github.com/timberio/vector/issues/7177
  * `CVE-2020-24342`: Tracking as https://github.com/timberio/vector/issues/7177
  * `CVE-2020-24369`: It seems like only Lua 5.4.0 is affected which means our current bundled version of 5.3.5 is fine.
  * `CVE-2020-24370`: It seems like only Lua 5.4.0 is affected which means our current bundled version of 5.3.5 is fine.
  * `CVE-2020-24371`: It seems like only Lua 5.4.0 is affected which means our current bundled version of 5.3.5 is fine.
* `sasl2-sys-0.1.14.crate`:
  * `CVE-2019-11358`: Seems to refer to a jQuery library?
  * `CVE-2019-19906`: There doesn't appear to be an available fix for Cyrus SASL yet. It also seems to be awaiting reanalysis.
  * `CVE-2020-11022`: Seems to refer to a jQuery library?
  * `CVE-2020-11023`: Seems to refer to a jQuery library?
* `wabt-sys-0.6.1.crate`
  * `CVE-2020-7760`: Seems to refer to a codemirror library?

**Comment by jszwedko** [comment]
I think some of the Javascript ones were flagged because the dependencies had JS in their repository. For example, for CVE-2020-7760 for the `wabt-sys` crate, it looks like `wabt` uses codemirror for its docs: https://github.com/WebAssembly/wabt/search?q=codemirror and for CVE-2021-23358 for the krb5-src crate, jquery is used for its docs:https://github.com/MaterializeInc/rust-krb5-src/search?q=jquery

**Comment by jeromekleinen-kbc** [comment]
Hi @jszwedko ,

Thanks for the elaborate investigation, sucks to see that the tool seems to report quite a bit of false positives. For what it's worth I have relayed this information to my colleagues so they can contact the vendor to fix their product.

Jerome

**Comment by jszwedko** [comment]
I'm going to close this out since we have follow-up issues for anything outstanding. Thanks for reporting this @jeromekleinen-kbc !
