### ISSUE TITLE
Allow executing Kubernetes tests on remote hardware when running locally

### ISSUE THREAD

**Issue by JeanMertz** [timberio/vector#7172]

**Comment by StephenWakely** [comment]
With the work in #7599 #7831 #7841 this has enabled the tests to run on remote hardware with minimal impact to whatever else is running on those clusters. I have successfully run these tests on AWS and Azure.

Following conversations with @MOZGIII, it is apparent that it may never be possible to achieve a full separation of the tests from the rest of the cluster. Whilst separate namespaces for each test goes a long way, it doesn't completely guarantee that there will not be any collission with the rest of the cluster. Uninstalling a helm chart doesn't completely guarantee that artifacts are not left on the cluster.

So whilst it is useful, and desirable to run our test suite on remote hardware, it is not really a solution for our CI since the only way  to guarantee that the tests are not influenced by external factors is to run from a new cluster. This is currently the way they work using minikube. Hopefully the word done for #7540 means this is now a much more pleasant process.
