### ISSUE TITLE
ERROR sink loki - vector::sinks::util::batch: Event larger than batch size

### ISSUE THREAD

**Issue by pgassmann** [timberio/vector#7395]
### Vector Version

```
vector 0.13.1 (v0.13.1 x86_64-unknown-linux-gnu 2021-04-29)
```

### Vector Configuration File

```toml
# Set global options
data_dir = "/var/lib/vector"

# Read logs from Docker API and Send to loki sink

[sources.docker-local]
  type = "docker_logs"
  docker_host = "/var/run/docker.sock"
  exclude_containers = []

  # Identify zero-width space as first line of a multiline block.
  multiline.condition_pattern = '^\x{200B}' # required
  multiline.mode = "halt_before" # required
  multiline.start_pattern = '^\x{200B}' # required
  multiline.timeout_ms = 1000 # required, milliseconds

[sinks.loki]
  # General
  type = "loki" # required
  inputs = ["docker-local"] # required
  endpoint = "https://logs.example.com:443" # required


  # Auth
  auth.strategy = "basic" # required
  auth.user = "" # required
  auth.password = "" # required

  # Encoding
  encoding.codec = "json" # required

  # Healthcheck
  healthcheck.enabled = true # optional, default


  # Labels
  labels.forwarder = 'vector'
  labels.host = '{{ host }}'
  labels.container_name = '{{ container_name }}'
  labels.compose_service = '{{ label.com\.docker\.compose\.service }}'
  labels.compose_project = '{{ label.com\.docker\.compose\.project }}'
  labels.source = '{{ stream }}'
  labels.category = 'dockerlogs'
```

### Debug Output

```
# journalctl -fu vector
May 10 19:12:09 prod1 vector[2810]: May 10 19:12:09.372  INFO vector::internal_events::docker_logs: Started watching for container logs. container_id=bbd15c220067ef5a1cb36efb08dce64631be2460754b4e6d2058736f7bdb2e31
May 10 19:12:29 prod1 vector[2810]: May 10 19:12:29.997 ERROR sink{component_kind="sink" component_name=loki component_type=loki}: vector::sinks::util::batch: Event larger than batch size, dropping. length=442475 internal_log_rate_secs=1
May 10 19:12:45 prod1 vector[2810]: May 10 19:12:45.391 ERROR sink{component_kind="sink" component_name=loki component_type=loki}: vector::sinks::util::batch: Event larger than batch size, dropping. length=3456229 internal_log_rate_secs=1

```

### Expected Behavior

* Vector should not drop logs
* Max batch size is documented

### Actual Behavior

Found that error in the logs. 
* [loki sink  batch](https://vector.dev/docs/reference/configuration/sinks/loki/#batch) has no `max_size` option, only `max_events`, but Error states a single Event is bigger than a size. 
* The number is not bigger than `buffer.max_size`
* It's not clear what the reason or necessary change is.

**Comment by jszwedko** [comment]
Removing this from the milestone, but we do have this work scheduled for next quarter.

**Comment by ktff** [comment]
> Max batch size is documented

It got documented at some point since then.

> The number is not bigger than buffer.max_size

True, but buffer and batch are different, and the event is larger than 100KiB which is the default value for `batch.max_bytes` for this sink.

Now regarding dropping the event, we can add a toggle option, like the one for buffers `buffer.when_full`, which would decide what happens with such events. Now the reason for this behavior is covered nicely by the original comments https://github.com/timberio/vector/pull/2866#issuecomment-646891090 and https://github.com/timberio/vector/pull/2866#issuecomment-646892252, but in short, downstream services can have limitation on the size of a request so `batch.max_bytes` can be used to keep requests under those limits. As a consequence, events larger than that limit are dropped.

### Solution
Adding option `batch.large_event` with two values:
* `drop`, default 
* `send`, with some documentation warning

This option would be added for all sinks that have batching. 

The default value would remain `drop`, but we can, in a later issue, go through each service and check if it makes sense to change it.

**Comment by jszwedko** [comment]
Ah, yeah, I see. Thanks for the explanation here @ktff .

I personally think, for this issue, we could just update the error message to include the batch size in it. Something like:

```
May 10 19:12:29 prod1 vector[2810]: May 10 19:12:29.997 ERROR sink{component_kind="sink" component_name=loki component_type=loki}: vector::sinks::util::batch: Event larger than batch max_bytes, dropping. batch_max_bytes=1024 length=442475 internal_log_rate_secs=1
```

Note the addition of `batch_max_bytes` there, also using `max_bytes` rather than `size` to more clearly link it to the config option name.

I do see that `batch.max_bytes` is documented on the `loki` sink now.

We could open a separate enhancement issue for changing the behavior of batching to allow for sending events larger than the batch size. Does that sound ok to you @ktff ?

**Comment by ktff** [comment]
@jszwedko it sounds good. I'll update the message and open the enhancement issue.
