### ISSUE TITLE
File source retains files on disk

### ISSUE THREAD

**Issue by marcbowes** [timberio/vector#763]
We're experimenting with vector as a replacement for our current log pusher.

The way ours system currently works is maybe a bit unexpected. Instead of doing conventional log rotation (e.g. my-log.log is copy-truncated to my-log.log.$TIMESTAMP), logs simply have the datetime appended to their name. After some time, a process comes and deletes them. Vector correctly finds these files but never closes them. As a result, the logs are never deleted off disk (on linux the space is only reclaimed after all readers have closed them).

lsof confirms this

```
vector  13487 me   28r   REG              259,1 186856628  40501267 /path/to/my_log.2019-08-16-19-51 (deleted)
vector  13487 me   29r   REG              259,1 119515494  40501279 /path/to/my_log.2019-08-16-19-46 (deleted)
vector  13487 me   30r   REG              259,1 113843033  40501266 /path/to/my_log.2019-08-16-19-45 (deleted)
vector  13487 me   31r   REG              259,1 161321082  40501303 /path/to/my_log.2019-08-16-19-47 (deleted)
vector  13487 me   33r   REG              259,1  86262666  40501302 /path/to/my_log.2019-08-16-19-43 (deleted)
vector  13487 me   34r   REG              259,1 108033600  40501310 /path/to/my_log.2019-08-16-19-44 (deleted)
vector  13487 me   36r   REG              259,1 181875679  40501334 /path/to/my_log.2019-08-16-19-52 (deleted)
vector  13487 me   38r   REG              259,1 170802922  40501329 /path/to/my_log.2019-08-16-19-48 (deleted)
vector  13487 me   39r   REG              259,1 189412379  40501309 /path/to/my_log.2019-08-16-19-50 (deleted)
vector  13487 me   40r   REG              259,1 174493378  40501296 /path/to/my_log.2019-08-16-19-49 (deleted)
```

**Comment by marcbowes** [comment]
The immediate workaround is to periodically bounce vector. In my case, that got my 700G back after about 24h of uptime.

**Comment by marcbowes** [comment]
https://github.com/timberio/vector/blob/e190e96e925d819d7460fab64f37fdb4241b88ad/lib/file-source/src/file_watcher.rs#L111
https://github.com/timberio/vector/blob/e190e96e925d819d7460fab64f37fdb4241b88ad/lib/file-source/src/file_server.rs#L215

I think the issue is that the `dead` status is not reachable because the file is always `findable`. I can't see any tests that demonstrate that that the "remove dead files" behavior actually works.

And, of course, this only fixes the issue if you are deleting files like we are. It'd be nice if vector was aware of this rotation strategy (maybe via config option) such that it stops polling files once a new file appears. But, for my specific use-case, fixing deletion is sufficient.

**Comment by binarylogic** [comment]
Thanks, @marcbowes! This is very helpful. And apologies for the trouble here, we're about to start a push to improve the `file` source and will include this. We expect to begin on Monday and will update as we make progress.

**Comment by marcbowes** [comment]
Don't thank me yet!

After posting this I read the file_server.rs code more carefully and I think I'm wrong on exactly where the bug is. But the symptoms are accurate at least :).

It was surprising to me the way the server works. It runs through each watched file and reads some bytes then sends them through the sink. So for example if I have a log file rotating minutely:

```
my-log.log.2019-08-19-18-00
my-log.log.2019-08-19-18-01
my-log.log.2019-08-19-18-02
```

then each file is pushed concurrently. This does more harm than good, in my opinion. For example, if one hits throttling in the sink (in my case, CloudWatch has a rate limit per stream) then each file competes for that capacity, each file making slow progress but new ones being discovered all the time.

I would suggest that the source be configurable to push newest first or oldest first and then try make progress against that policy as quickly as possible (even if it can't keep up). So this might be what I was seeing?

**Comment by lukesteensen** [comment]
Hi @marcbowes, sorry you're having issues! If I'm understanding your setup correctly, here's what _should_ be happening, from the beginning:

1. A new file shows up in an `include`'d directory with an unknown fingerprint, so we build a new watcher and stash it away: https://github.com/timberio/vector/blob/48778f848a8b3ee934a28c796d69589eab9b9242/lib/file-source/src/file_server.rs#L169

2. While the file is active it will show up in the `include` globs and our fingerprint map, which means we'll keep it marked as `findable`: https://github.com/timberio/vector/blob/48778f848a8b3ee934a28c796d69589eab9b9242/lib/file-source/src/file_server.rs#L116

3. Once your rotation period has passed, the file is no longer written to but remains on the file system like normal. Vector will continue watching for more data, but not care if there isn't more as long as the file is still sitting there normally (i.e. it shows up in an `include` glob).

4. Your cleanup process comes through and deletes the file.

5. Next time we scan the include patterns, the deleted file will not show up and its entry in the fingerprint map will remain marked as not findable: https://github.com/timberio/vector/blob/48778f848a8b3ee934a28c796d69589eab9b9242/lib/file-source/src/file_server.rs#L96

6. When we proceed to the read loop, we'll try to read more data from the file. The read will return zero bytes, see that the file is no longer marked as findable, and mark it as dead: https://github.com/timberio/vector/blob/48778f848a8b3ee934a28c796d69589eab9b9242/lib/file-source/src/file_watcher.rs#L110-L111

7. Once we're done reading we drop all dead entries from the fingerprint map, deallocating the reader and closing the file handle: https://github.com/timberio/vector/blob/48778f848a8b3ee934a28c796d69589eab9b9242/lib/file-source/src/file_server.rs#L213-L215

I've run some simple tests locally that show this behaving as expected, so there must be something else about your situation causing this different behavior.

> For example, if one hits throttling in the sink (in my case, CloudWatch has a rate limit per stream) then each file competes for that capacity, each file making slow progress but new ones being discovered all the time.

If you're getting rate limited upstream, that could lead to a situation where our "fair" reading strategy causes a pileup of open files we fail to finish reading from (i.e. read will never return zero, so they're legitimately not dead). We can definitely look into providing an option to adjust that reading strategy, since the original was written assuming different files were likely to be from different services and the fairness aspect would be desirable.

On the other hand, if you really are being limited by the upstream service to a throughput significantly less that what's being written to disk, you're likely to see a backup of open files even with a greedier reading strategy.

We can also spin up some performance tests for the cloudwatch logs sink to make sure we haven't overlooked a bottleneck there.

**Comment by lukesteensen** [comment]
With #810 now merged, we have a flag that adjusts our behavior to better match the rotation strategy you described. Hopefully that should be enough to address the pathological behavior you saw here, but we also have #841 to ensure that any rate limiting (which could lead to this issue) is clearly reported. 

Thanks again for the report @marcbowes and please do let us know when you're able to try out a version with these changes included! In the meantime I'm going to go ahead and close this.

**Comment by linc01n** [comment]
I have the same problem. I'm sinking to a vector service role. I tried adjusting the `oldest_first` and `max_read_bytes` but no luck.

**Comment by lukesteensen** [comment]
@linc01n Do you see the same issue if you replace the `vector` sink with a `blackhole` sink?

This behavior can happen in any case where the file source is trying to ingest data faster than the sink can send it. If the problem doesn't happen with `blackhole`, I can dig into the `vector` sink and see if there's any reason it could be slower than it should be.

**Comment by linc01n** [comment]
I replaced it with a `blackhole` sink still got the same issues in `lsof +L1`

**Comment by linc01n** [comment]
it is a host mount like this https://github.com/timberio/vector/issues/1053

**Comment by lukesteensen** [comment]
@linc01n So you're running vector in a docker container and mounting the logs directory from the host?

Are you mounting both the directory of symlinks and the directory of the log files themselves? I'm wondering if vector is trying to follow the symlinks and failing.

Are you getting any logs in the output at all?
