### ISSUE TITLE
Create a Datadog dashboard for soak tests

### ISSUE THREAD

**Issue by blt** [timberio/vector#7639]
In order for us to actually see how the soak tests are doing we need a dashboard to tell us. We can improve the dashboard over time so all we need is a proof of concept to get success here.

**Comment by tobz** [comment]
This is all set.

We have a dashboard in our internal Datadog account called Soak Test High Level Metrics which provides metrics such as CPU usage, memory used by Vector, network, and disk against hosts of a particular soak test. The dashboard shows these metrics separately for both "source" and "sink" hosts, so that we can see both sides of the equation e.g. a client spewing logs over TCP to a Vector host, or a Vector aggregator situation where Vector is running on both side.

The dashboard is tooled to allow showing the metrics for a particular soak test, which is derived from special instance tags we apply to VMs created for a given soak test. Developers can copy/paste the soak test skeleton code and tweak the tags as needed.
