### ISSUE TITLE
Land a soak test proof of concept

### ISSUE THREAD

**Issue by blt** [timberio/vector#7643]
We want to be able to provide soak testing generally to the team, so that means both a diagnostic suite -- see #7641, #7640, #7639 -- but also the ability to modify existing tests, create new ones. Success here is a mechanism by which the broader vector team can introduce new soak tests or modify an existing one. It doesn't need to be hooked into CI/CD.

**Comment by tobz** [comment]
This is all set.

We have a dashboard in our internal Datadog account called `Soak Test High Level Metrics` which provides metrics such as CPU usage, memory used by Vector, network, and disk against hosts of a particular soak test.  The dashboard shows these metrics separately for both "source" and "sink" hosts, so that we can see both sides of the equation e.g. a client spewing logs over TCP to a Vector host, or a Vector aggregator situation where Vector is running on both side.

The dashboard is tooled to allow showing the metrics for a particular soak test, which is derived from special instance tags we apply to VMs created for a given soak test.  Developers can copy/paste the soak test skeleton code and tweak the tags as needed.

**Comment by blt** [comment]
Addressed by https://github.com/timberio/resources/pull/50
