### ISSUE TITLE
BatchNotifier should support partial failures.

### ISSUE THREAD

**Issue by tobz** [timberio/vector#7724]
Currently, `BatchNotifier` can be attached to multiple events, but it does not report partial failures.  This means that even if only one event in a batch fails, the entire batch could be marked as a failure.

In order to not only unlock higher-performance acknowledgement via batching, but to provide maximally correct processing, `BatchNotifier` should be modified/extended to support tracking the status of individual events that have been attached to it.

**Comment by bruceg** [comment]
I had initially written in selective acking to the notification framework, and then backed it out to a single result because none of the sources I was aware of could notify the external source of individual event status. If there is a source that can acknowledge events individually, this can be retrofitted relatively easily on a source-by-source basis.

However, I have to ask how this works in the context of the `aws_s3` source. What will the source do when part of the batch is failed or errored? Is the intent that vector will re-read the data from S3 after the error or after a restart? I ask partly because the error handling part of notifications doesn't seem particularly useful for sources that scrape external data, and partly because it was a question I had when looking at the `kafka` source as well and will have to look at with the `file` source(s).

**Comment by tobz** [comment]
Hmmm, this is actually a good point.

One message in SQS relates to one file being added into S3.  That file may have multiple lines, and so it could actually turn into multiple events being generated.  Thus, even if we knew the batch partially failed, we would have a hard time selectively rereading just that event from the file.

So, yeah, this actually wouldn't help here with the S3 source.  Do you want to leave it open as you search for the answer to whether or not we need it for the sources you mentioned?  Happy to close it otherwise.

**Comment by bruceg** [comment]
I think this does not matter until there are sources that can make use of selective acknowledgements, at which point we will re-open it as part of supporting that.
