### ISSUE TITLE
Add support for podman as an alternative to docker

### ISSUE THREAD

**Issue by bruceg** [timberio/vector#781]
"[Podman](https://podman.io/) is a daemonless container engine for developing, managing, and running OCI Containers on your Linux System. Containers can either be run as root or in rootless mode. Simply put: `alias docker=podman`"

See also [Podman: A more secure way to run containers](https://opensource.com/article/18/10/podman-more-secure-way-run-containers)

Adding support for podman to build and test our containers would be a useful addition for those who don't want to give access to the docker daemon to random users. For most cases, this is a matter of trivially substituting `podman` for `docker` in scripts and testing.

Podman also includes "pod" management functionality, similar to Docker Compose or Kubernetes. This would the bigger part of the work, since it's not a straight conversion.

**Comment by jdoss** [comment]
Podman 2.x now has an API that can be used like Docker. 

https://docs.podman.io/en/latest/_static/api.html

This most likely could be used to add in Podman support without having to reinvent too many wheels in Vector.

**Comment by jamtur01** [comment]
Chatting with @Hoverbear about this and wanted to add a thought. Firstly, podman is probably a better choice than docker/docker-compose from a security/operational perspective. However, as podman is fairly immature on OSX, certainly lacking the Docker Desktop-style ease of use, then I think it'll be hard for folks developing on OSX to adopt podman without some fiddling. I'd suggest we park this for now until podman is easier to use on all the platforms we expect folks to be developing on.

**Comment by jdoss** [comment]
If you folks are waiting for Podman to have native OS X support we're going to be waiting a long time. Could I help by shoving  podman in a Linux VM to aid in in development?

**Comment by jamtur01** [comment]
Not looking for native OSX support, specifically Docker Desktop-like ease-of-use.

**Comment by jdoss** [comment]
I don't think you will see that level of ease-of-use since Podman is a Linux only container engine and I don't think the Podman team has any plans to get it running in a Docker Desktop setup. You could use https://github.com/boot2podman/boot2podman to get a instance of Podman running on your laptop pretty easily however. It just got deprecated [7 days ago](https://github.com/boot2podman/boot2podman/commit/6dff8996189652d4bc32a1864edb5574659c70d0) and I am not sure o the exact Podman version. We'd need Podman 2.0.x or greater.

If I assume what you folks are looking for it would be easy access to the new [https://docs.podman.io/en/latest/_static/api.html](Podman API) on your mac? That should be pretty easy to replicate with a Vagrant VM if you are open to that. I am more than willing to help set that up so it is easy for you folks to use as target practice against in development.

**Comment by binarylogic** [comment]
This was closed with #3622
