### ISSUE TITLE
Will kafka sources type  topic support  pattern ?  

### ISSUE THREAD

**Issue by yujinqiu** [timberio/vector#819]
Hi, 
vector's performance is really impressive and I want to migrate my logstash to vector.   logstash's current functionality is  consumer data from  kafka topic and sink to  ES. 

```
    input {
      kafka {
        codec => 'json'
        bootstrap_servers => '<ip:port>'
        group_id => 'logstash-indexer'
        consumer_threads => 3
        topics_pattern => '(beats|filebeat-kubernetes)-.+'
      }
    }
```

And  I browse  vector's 

```

topics | [string] | The Kafka topics names to read events from.required example: (see above)

```
From:  https://github.com/timberio/vector/blob/0f72a2b1669a97e4838d3ca852d2f68a878915f4/docs/usage/configuration/sources/kafka.md

Is it possible to configure  topics like this 

```
topics = ['(beats|filebeat-kubernetes)-.+']
```

**Comment by lukesteensen** [comment]
Hi @yujinqiu! This is actually supported today, but with a slight wrinkle because of the way the underlying kafka library ([librdkafka](https://github.com/edenhill/librdkafka)) works. See the comment [here](https://github.com/confluentinc/confluent-kafka-python/issues/56#issuecomment-261073017).

The gist is that librdkafka looks for a `^` prefix to determine when a topic name should be considered a regex pattern. In your case, the following should behave the way you want:

```toml
topics = ['^(beats|filebeat-kubernetes)-.+']
```

**Comment by yujinqiu** [comment]
@lukesteensen  awsome,  thanks .
