### ISSUE TITLE
Documentation - NewRelic Sink missing information

### ISSUE THREAD

**Issue by B3DTech** [timberio/vector#8316]
NewRelic Sink - errors when using the basic template.   First error, encoding is missing defaults: 
ERROR vector::cli: Configuration error. error=missing field encoding for key sinks.newRelic at line 69 column 1
so I put in encoding.timestamp_format = "rfc3339"  and that error went away. 

Second Error:
ERROR vector::cli: Configuration error. error=missing field codec for key sinks.newRelic at line 69 column 1

There is no mention of a codec field in the NewRelic Sink documentation and clearly no default.

The encoding field is not shown in the basic or advanced configurations, and is not mentioned as a required field.

It also asks for the encoding coded, which is resolved with this line, also not mentioned in the documentation.
encoding = "json"

**Comment by jszwedko** [comment]
Ah, yes, apologies @B3DTech . This is actually fixed by #7870 . That was an oversight when we switched around the encoding defaults. This is fixed in the latest nightly build, but will also be a part of the next release this week.

I'll close this out, but let me know if that doesn't resolve it for you!
