### ISSUE TITLE
Support ARMv7

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#859]
To ensure Vector can be used on IOT devices like Raspberry PI we should provide pre-built ARMv7 archives. The tricky part will be supporting `leveldb` as well as `rdkafka`.

I'm unsure exactly which target triple we need to support for this, and I'd like to lightly spec this out before beginning work to ensure we're supporting the right target.

**Comment by a-rodin** [comment]
On ARMv7 there are two targets supported by Rust where it would make sense to run Vector, `armv7-unknown-linux-gnueabihf` and `armv7-unknown-linux-musleabihf`. They are fully analogous to `x86_64-unknown-linux-gnu` and `x86_64-unknown-linux-musl` correspondingly.

## Native builds

On-device build with all features for `armv7-unknown-linux-gnueabihf` is analogous to build for `x86_64-unknown-linux-gnu`, just take long time. However, building for `armv7-unknown-linux-musleabihf` on device similarly to the build for `x86_64-unknown-linux-musl` is probably not possible because the builder needs to build LLVM and it is necessary more than 4GB of RAM to link Clang, which cannot be satisfied on a 32-bit platform.

Additionally, Circle CI [doesn't support ARM executors](https://ideas.circleci.com/ideas/CCI-I-900), although it could be worked around by self-hosting some CI system on AWS [A1 instances](https://aws.amazon.com/ec2/instance-types/a1/).

## Cross-compilation

So it might be a more robust solution to cross-compile for ARMv7. One simple approach is to start from tweaking the builder for `x86_64-unknown-linux-musl` and add cross-compilation flags there. The resulting builder would be able to produce static binaries for `armv7-unknown-linux-musleabihf` from CI.

## Bindings for rdkafka
At the moment, `rdkafka` crate cannot be compiled out of box for `armv7-unknown-linux-gnueabihf` (and, consequentially, for `armv7-unknown-linux-gnueabihf`) because C bindings in `rdkafka-sys` are platform-specific and need to be regenerated. It is not a big problem to regenerate them, but it might be necessary to create Vector’s own fork of `rdkafka-sys` crate to do it unless the changes are upstreamed.

## Conclusion
So to start providing ARMv7 binaries there are two necessary steps:
* Generate bindings in `rdkafka-sys` and create a fork and/or have new bindings merged to upstream.
* Modify the builder for `x86_64-unknown-linux-musl` to allow cross-compilation for `armv7-unknown-linux-musleabihf`.

**Comment by binarylogic** [comment]
Excellent write-up! Thank you. The conclusion steps make sense to me.
