### ISSUE TITLE
Is vector usable in windows?

### ISSUE THREAD

**Issue by mamcx** [timberio/vector#879]
I know vector docs not talk for windows, but wonder if is possible?

I try cross-compiling master branch(I already compile for windows in my machine my own utilities):

cargo build --target=x86_64-pc-windows-gnu --release

 ```
Compiling thread_local v0.3.6
error: failed to run custom build command for `miniz-sys v0.1.12`

Caused by:
  process didn't exit successfully: `/Users/mamcx/Proyectos/basura/vector/target/release/build/miniz-sys-60d52d94d622815c/build-script-build` (exit code: 1)
--- stdout
TARGET = Some("x86_64-pc-windows-gnu")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
TARGET_CC = None
CC = None
CROSS_COMPILE = None
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
running: "x86_64-w64-mingw32-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-DMINIZ_NO_STDIO" "-DMINIZ_NO_ARCHIVE_APIS" "-DMINIZ_NO_ARCHIVE_WRITING_APIS" "-DMINIZ_NO_TIME" "-DMINIZ_NO_ZLIB_COMPATIBLE_NAMES" "-o" "/Users/mamcx/Proyectos/basura/vector/target/x86_64-pc-windows-gnu/release/build/miniz-sys-65c49ea27529a975/out/miniz.o" "-c" "miniz.c"

--- stderr


error occurred: Failed to find tool. Is `x86_64-w64-mingw32-gcc` installed?
```

**Comment by binarylogic** [comment]
Hi @mamcx , thanks for asking. Currently, it is not, but we are about to start work in [milestone 18](https://github.com/timberio/vector/milestone/18), which aims to support more targets. I've created #880 to represent this work. I'll close this in favor of that issue.

**Comment by LucioFranco** [comment]
@mamcx two things, here you probably want to compile for MSVC toolchain instead of the gnu version. Second, you also probably want to compile the entire thing as `cargo build --no-default-features` which will disable a lot of the C/C++ dependencies. The only required dependency I think beyond that is `openssl`. Otherwise, this _should_ work though there are no guarantees since we don't have anyone actively developing vector on a windows machine right now.
