### ISSUE TITLE
Support Windows as a release target

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#880]
This is a follow up to https://github.com/timberio/vector/issues/879. We've received this request a few times and I'd like to start by reviewing exactly how difficult this would be and then determining if we'd like to proceed or not.

**Comment by a-rodin** [comment]
I’m not sure how satisfactory it would be, but it looks like MUSL binary for Linux [should just work on WSL](https://docs.microsoft.com/en-us/windows/wsl/interop#run-linux-tools-from-a-windows-command-line). I don’t have a Windows machine at hand now to test it though. If it works and if supporting only Windows systems with WSL is fine, we can additionally make a [Chocolatier](https://chocolatey.org/) package to install a wrapper to make it possible to invoke just `vector` instead of `wsl ./vector`.

Alternatively, we can try to compile natively. It probably would be easiest to do with MinGW (needs to be checked in native dependencies build scripts), although it would link to some LGPL libraries. I’m not sure would MSVC community license allow us to use it for Vector,  but if it would, it it is also a question do all native dependencies support building with MSVC tools instead of `make` and POSIX-compatible C compiler command line interface. An interesting venue to explore is creation of a new target triple based on Clang, which is something [not reported to be done yet](https://users.rust-lang.org/t/can-i-compile-on-windows-using-nothing-but-the-llvm-toolchain).

**Comment by mchesser** [comment]
I had a go at compiling on Windows using MSVC, and it mostly works though I had to disable several features (namely file sources/sinks, signal handling, and leveldb persistence). 

The metrics library (hotmic) is also problematic (causes an infinite loop on windows) because it uses an outdated version of crossbeam-channel that suffers from an issue in the atomic cell implementation (see: crossbeam-rs/crossbeam#388).

My fork here: (https://github.com/mchesser/vector) should compile and appears to work (though I didn't really perform any amount of testing) when compiling with `--default-features=false`.

**Comment by a-rodin** [comment]
I experimented with compilation on Vector on Windows under MSYS2/MINGW64. There were a few problems:

* `file` source uses Unix-specific features (see #1101 for details)
* `file` sink [uses `OsStrExt`](https://github.com/timberio/vector/blob/616d14abf59ac6e29c356fbf43e108dd7a438d35/src/sinks/file/file.rs#L153) - probably, can be worked around
* `syslog` uses Unix-specific features too, but I'm not sure should it be supported on Window or not
* Signal handling in `main.rs` is Unix-specific, I think it should be put behind `#[cfg(unix)]`

Status of the dependencies behind feature flags:
* The version of `leveldb` crate from our fork was compiled successfully.
* `librdkafka` is reported to have Windows support, but only for MSVC. With some tweaking of its C code I was able to compile it with MINGW, but not link (there were a lot of errors about duplicated symbols and also missing symbols) .
* There were issues with compiling `jemalloc`, but I didn't investigate them in my opinion `jemalloc` feature is more optional than others.
