### ISSUE TITLE
New `prometheus` source

### ISSUE THREAD

**Issue by binarylogic** [timberio/vector#991]
A `prometheus` source would scrape one or more targets as metrics input.

This has the potential to get somewhat complicated if we want to support auto-discovery and tag augmentation when scraping targets. Before we begin work we should:

1. Determine how deep we want to go with scraping. Ex: autodiscovery, tagging, and so on.
2. Define the steps. What is the simplest first step and what does the journey look like supporting all of the features we want to support?

**Comment by loony-bean** [comment]
Looking at how Datadog [is doing Prometheus scrapes](https://github.com/DataDog/integrations-core/blob/master/prometheus/datadog_checks/prometheus/data/conf.yaml.example) I think that the simplest first step would be to ask user for:
- Prometheus url in form of e.g. `http://localhost:10055/metrics`
- Time interval to wait between requests

So basically we will start from autodiscovery as default behaviour.

I don't think we need to do any kind of tags augmentation in the source, because this could be done in downstream transforms. And we don't need to manipulate namespaces, because we normally do that in sinks.

Next steps would look like adding more granular control over which metrics to include or exclude, and supporting aggregated histograms.

/cc @lukesteensen

**Comment by binarylogic** [comment]
@lukesteensen do you mind reviewing? I'd like to prioritize this since T-Mobile asked for it and I'd like to use it for our own use cases. When you're done reviewing can you remove yourself and the `meta: needs review` label?

**Comment by lukesteensen** [comment]
I agree with @loony-bean's comment above. We'll probably want to accept a list of URLs to scrape instead of just one, but I don't think we need to get any fancier than that for the first version.

Eventually we'll probably want some integration with service discovery systems to find hosts to scrape, but that's something that can be added later.
